Repository coreshop/CoreShop, pull requests merged in 2018-06, with the labels that each got.

#449 WIP: Embedded ClassEditable introduces a new embedded class editable
  src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/EmbeddedClassController.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/EmbeddedClass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/css/pimcore.css
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/img/icons/embedded_class.svg
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/data/coreShopEmbeddedClass.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/embeddedClassContainer.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/embeddedClassItemContainer.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopEmbeddedClass.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Pimcore/DataObject/EditmodeHelper.php
Labels: new feature

#431 Quick Open Feature
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/list.js
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
Labels: PR-Ready, enhancement, new feature

#435 [CategoryConditions] implement 'recursive' flag for category condition
  features/product/price_rules/category_condition.feature
  features/shipping/shipping_rules/category_condition.feature
  src/CoreShop/Behat/Context/Setup/CategoryContext.php
  src/CoreShop/Behat/Context/Setup/ProductPriceRuleContext.php
  src/CoreShop/Behat/Context/Setup/ShippingContext.php
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Rule/Condition/CategoriesConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/CategoryRepository.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-price-rules.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/product.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/shipping.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/pricerule/conditions/categories.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/conditions/categories.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/Condition/CategoriesConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/conditions/categories.js
  src/CoreShop/Bundle/ProductBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/ProductBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Core/Cart/Rule/Condition/CategoriesConditionChecker.php
  src/CoreShop/Component/Core/Product/Rule/Condition/CategoriesConditionChecker.php
  src/CoreShop/Component/Core/Product/Rule/Condition/CurrenciesConditionChecker.php
  src/CoreShop/Component/Core/Product/Rule/Condition/QuantityConditionChecker.php
  src/CoreShop/Component/Core/Repository/CategoryRepositoryInterface.php
  src/CoreShop/Component/Core/Rule/Condition/CategoriesConditionCheckerTrait.php
  src/CoreShop/Component/Core/Shipping/Rule/Condition/CategoriesConditionChecker.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/Product/PriceRule.php
Labels: enhancement, new feature

#463 [Category Sorting] sort categories the same way as Pimcore does
  src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/CategoryRepository.php
  src/CoreShop/Bundle/ProductBundle/Pimcore/Repository/CategoryRepository.php
Labels: enhancement, new feature

#473 [ExchangeRate] increase decimal scale to 10
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180615074917.php
  src/CoreShop/Bundle/CurrencyBundle/Form/Type/ExchangeRateType.php
  src/CoreShop/Bundle/CurrencyBundle/Resources/config/doctrine/model/ExchangeRate.orm.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/exchangeRate/panel.js
Labels: enhancement

#471 [Payment] refactor payment model to return order object directly
  src/CoreShop/Behat/Context/Setup/PaymentContext.php
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/PaymentWorkflowListener.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180614132413.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Payment.orm.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_payment.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/config/services.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/_header.html.twig
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderPaymentController.php
  src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_invoice.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_order.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_payment.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_shipment.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/payment.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/workflow.yml
  src/CoreShop/Bundle/OrderBundle/Workflow/OrderStateHistoryLogger.php
  src/CoreShop/Bundle/PayumBundle/Action/ConfirmOrderAction.php
  src/CoreShop/Bundle/PayumBundle/Action/Offline/ConfirmOrderAction.php
  src/CoreShop/Bundle/PayumBundle/Action/Offline/ResolveNextRouteAction.php
  src/CoreShop/Bundle/PayumBundle/Action/ResolveNextRouteAction.php
  src/CoreShop/Bundle/PayumBundle/Controller/PaymentController.php
  src/CoreShop/Bundle/PayumBundle/Extension/UpdateOrderStateExtension.php
  src/CoreShop/Bundle/PayumBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PayumBundle/Resources/config/services/extension.yml
  src/CoreShop/Bundle/PayumBundle/composer.json
  src/CoreShop/Component/Core/Model/Payment.php
  src/CoreShop/Component/Core/Model/PaymentInterface.php
  src/CoreShop/Component/Core/Notification/Rule/Condition/StoresChecker.php
  src/CoreShop/Component/Order/Model/OrderPaymentInterface.php
  src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php
  src/CoreShop/Component/Order/Payment/OrderPaymentProviderInterface.php
  src/CoreShop/Component/Payment/Model/Payment.php
  src/CoreShop/Component/Payment/Model/PaymentInterface.php
Labels: enhancement

#484 Index category
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_category_select.html.twig
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionCategorySelectType.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/css/index.css
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/img/filter-category-select.svg
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/category_select.js
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Core/Index/Extensions/ProductClassExtension.php
  src/CoreShop/Component/Index/Filter/CategorySelectConditionProcessor.php
Labels: enhancement

#481 [Timespan Conditions] use todays date. fixes
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/conditions/timespan.js
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/conditions/timespan.js
Labels: enhancement

#490 Order overview improvements
  docs/02_User_Documentation/06_Order/01_Orders.md
  docs/03_Development/06_Order/08_OrderList/01_Filter.md
  docs/03_Development/06_Order/08_OrderList/02_Action.md
  docs/03_Development/06_Order/README.md
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/grid_config.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/settings.yml
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/grid_config.yml
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/list.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/plugin/salesListContextMenu.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/quote/list.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/list.js
  src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/GridController.php
  src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterGridActionPass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterGridFilterPass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/PimcoreBundle/EventListener/Grid/ObjectListFilterListener.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/grid.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/plugin/grid.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/PimcoreBundle/composer.json
  src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php
  src/CoreShop/Component/Pimcore/DataObject/Grid/GridActionInterface.php
  src/CoreShop/Component/Pimcore/DataObject/Grid/GridFilterInterface.php
Labels: enhancement

#486 [Order] Order mail event
  src/CoreShop/Bundle/CoreBundle/EventListener/Order/OrderMailNoteEventListener.php
  src/CoreShop/Bundle/CoreBundle/Order/OrderMailProcessor.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/notification.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/PimcoreBundle/Event/MailEvent.php
  src/CoreShop/Bundle/PimcoreBundle/Events.php
  src/CoreShop/Bundle/PimcoreBundle/Mail/MailProcessor.php
  src/CoreShop/Bundle/PimcoreBundle/Mail/MailProcessorInterface.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
  src/CoreShop/Component/Notification/Rule/Action/MailActionProcessor.php
  src/CoreShop/Component/Pimcore/Mail.php
Labels: enhancement, new feature

#480 [OrderMailDocuments] use documents correct state for sending via mail
  src/CoreShop/Bundle/CoreBundle/Order/OrderMailProcessor.php
  src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/AbstractOrderDocumentRepository.php
  src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderInvoiceRepository.php
  src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderShipmentRepository.php
  src/CoreShop/Component/Order/Repository/OrderDocumentRepositoryInterface.php
Labels: bug

#485 [Notification] allow to skip sending mail to designated recipient
  src/CoreShop/Bundle/CoreBundle/Form/Type/Notification/Action/OrderMailConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Notification/Action/StoreMailConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Order/OrderMailProcessor.php
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/actions/orderMail.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/actions/storeMail.js
  src/CoreShop/Bundle/NotificationBundle/Form/Type/Rule/Action/MailActionConfigurationType.php
  src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/rule/actions/mail.js
  src/CoreShop/Bundle/NotificationBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/NotificationBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Core/Notification/Rule/Action/Order/OrderMailActionProcessor.php
  src/CoreShop/Component/Core/Notification/Rule/Action/Order/StoreOrderMailActionProcessor.php
  src/CoreShop/Component/Notification/Rule/Action/MailActionProcessor.php
Labels: enhancement

#500 [OrderBundle, CoreBundle] implement ready state for shipment and invoice
  CHANGELOG.md
  docs/03_Development/06_Order/05_Invoice/01_Invoice_Creation.md
  docs/03_Development/06_Order/06_Shipment/01_Shipment_Creation.md
  features/order/order_invoice.feature
  features/order/order_shipment.feature
  features/order/order_states.feature
  features/order/order_workflow.feature
  src/CoreShop/Behat/Context/Setup/OrderContext.php
  src/CoreShop/Behat/Context/Setup/OrderInvoiceContext.php
  src/CoreShop/Behat/Context/Setup/OrderShipmentContext.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180626083954.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderInvoiceController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderShipmentController.php
  src/CoreShop/Bundle/OrderBundle/Pimcore/GridColumnConfig/Operator/OrderState.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_invoice.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_order_invoice.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_order_shipment.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_shipment.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Order/OrderInvoiceTransitions.php
  src/CoreShop/Component/Order/OrderShipmentTransitions.php
Labels: task

#505 Implement custom redirect for item adding
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php
Labels: enhancement

#506 Processable Items Extension
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/invoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/payment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/shipment.js
  src/CoreShop/Component/Order/Processable/ProcessableOrderItems.php
Labels: enhancement

#514 [All] Move RegisterRegistryPasses to PimcoreBundle
  src/CoreShop/Bundle/AddressBundle/DependencyInjection/Compiler/CompositeCountryContextPass.php
  src/CoreShop/Bundle/AddressBundle/DependencyInjection/Compiler/CompositeRequestResolverPass.php
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterPortletsPass.php
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterReportsPass.php
  src/CoreShop/Bundle/CurrencyBundle/DependencyInjection/Compiler/CompositeCurrencyContextPass.php
  src/CoreShop/Bundle/CustomerBundle/DependencyInjection/Compiler/CompositeCustomerContextPass.php
  src/CoreShop/Bundle/CustomerBundle/DependencyInjection/Compiler/CompositeRequestResolverPass.php
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterColumnTypePass.php
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterFilterConditionTypesPass.php
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterGetterPass.php
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterIndexWorkerPass.php
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterInterpreterPass.php
  src/CoreShop/Bundle/LocaleBundle/DependencyInjection/Compiler/CompositeLocaleContextPass.php
  src/CoreShop/Bundle/NotificationBundle/DependencyInjection/Compiler/AbstractNotificationRulePass.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Compiler/CartPriceRuleActionPass.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Compiler/CartPriceRuleConditionPass.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Compiler/RegisterCartContextsPass.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Compiler/RegisterCartProcessorPass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/PrioritizedCompositeServicePass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterGridActionPass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterGridFilterPass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterRegistryTypePass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterSimpleRegistryTypePass.php
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Compiler/ProductPriceRuleActionPass.php
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Compiler/ProductPriceRuleConditionPass.php
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Compiler/ProductSpecificPriceRuleActionPass.php
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Compiler/ProductSpecificPriceRuleConditionPass.php
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Compiler/ProductValidPriceRuleFetcherPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/PrioritizedCompositeServicePass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterRegistryTypePass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterSimpleRegistryTypePass.php
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/Compiler/CompositeShippableValidatorPass.php
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/Compiler/ShippingRuleActionPass.php
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/Compiler/ShippingRuleConditionPass.php
  src/CoreShop/Bundle/StoreBundle/DependencyInjection/Compiler/CompositeRequestResolverPass.php
  src/CoreShop/Bundle/StoreBundle/DependencyInjection/Compiler/CompositeStoreContextPass.php
  src/CoreShop/Bundle/TrackingBundle/DependencyInjection/Compiler/TrackerPass.php
Labels: bug

#513 [OrderBundle] fix order detail glitch
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/header.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/panel.js
Labels: bug

#508 [All] change all resource combo-boxes to load the store 'async'.
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/country.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/state.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/zone.js
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/resource/currency.js
  src/CoreShop/Bundle/StoreBundle/Resources/public/pimcore/js/resource/store.js
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/resource/taxRate.js
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/resource/taxRuleGroup.js
Labels: bug
