Repository coreshop/CoreShop, pull requests merged in 2018-07, with the labels that each got.

#520 [JMSSerializer config] fix wrong configurations
  src/CoreShop/Bundle/ConfigurationBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/RuleBundle/Resources/config/app/config.yml
  src/CoreShop/Bundle/RuleBundle/Resources/config/app/coreshop_rule.yml
  src/CoreShop/Bundle/RuleBundle/Resources/config/pimcore/config.yml
Labels: bug

#524 [ProductBundle] delete product specific price rules on product deletion
  src/CoreShop/Bundle/ProductBundle/EventListener/ProductDeleteListener.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/services.yml
Labels: bug

#522 [CoreBundle] apply almost same params for every customer notification event
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/CustomerListener.php
Labels: bug

#515 [Pimcore Document Tags] allow CoreShop Resources as Document tags
  src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/AddressBundle/Resources/config/services.yml
  src/CoreShop/Bundle/AddressBundle/Resources/config/services/pimcore.yml
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/coreExtension/document/coreShopCountry.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/coreExtension/document/coreShopState.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/coreExtension/document/coreShopZone.js
  src/CoreShop/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CurrencyBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/config/services/pimcore.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/coreExtension/document/coreShopCountry.js
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/pimcore.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/coreExtension/document/coreShopFilter.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/coreExtension/document/coreShopIndex.js
  src/CoreShop/Bundle/PaymentBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/PaymentBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/config/services/pimcore.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/public/pimcore/js/coreExtension/document/coreShopPaymentProvider.js
  src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterImplementationLoaderPass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterPimcoreDocumentTagImplementationLoaderPass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterPimcoreDocumentTagPass.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Extension/AbstractPimcoreExtension.php
  src/CoreShop/Bundle/PimcoreBundle/Loader/DependencyInjectionImplementationLoader.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/pimcore.yml
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Document/Select.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/coreExtension/document/select.js
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services/pimcore.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/coreExtension/document/coreShopCarrier.js
  src/CoreShop/Bundle/StoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/StoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/StoreBundle/Resources/config/services/pimcore.yml
  src/CoreShop/Bundle/StoreBundle/Resources/public/pimcore/js/coreExtension/document/coreShopStore.js
  src/CoreShop/Bundle/TaxationBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/TaxationBundle/Resources/config/services.yml
  src/CoreShop/Bundle/TaxationBundle/Resources/config/services/pimcore.yml
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/coreExtension/document/coreShopTaxRate.js
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/coreExtension/document/coreShopTaxRuleGroup.js
  src/CoreShop/Component/Pimcore/Document/DocumentTagFactoryInterface.php
  src/CoreShop/Component/Resource/Pimcore/ResourceDocumentTagFactory.php
Labels: new feature, task

#521 [PimcoreBundle] move dynamicDropdown from custom bundle to PimcoreBundle
  src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdown.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdownMultiple.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/ItemSelector.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/SuperBoxSelect.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/dynamic_dropdown.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/css/pimcore.css
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/img/icons/clear-filter.svg
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/img/icons/dynamic-dropdown-multiple.svg
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/img/icons/dynamic-dropdown.svg
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/img/icons/item-selector.svg
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/img/icons/super-box-select.svg
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/data/coreShopDynamicDropdown.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/data/coreShopDynamicDropdownMultiple.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/data/coreShopItemSelector.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/data/coreShopSuperBoxSelect.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopDynamicDropdown.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopDynamicDropdownMultiple.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopItemSelector.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopSuperBoxSelect.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/ext/ClearButton.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/translations/admin.en.yml
Labels: enhancement, new feature

#518 [FrontendBundle] fix search
  src/CoreShop/Bundle/FrontendBundle/Controller/SearchController.php
Labels: bug

#525 [RuleBundle] fix for nested condition and checker including a behat test
  features/product/specific_price_rules/nested_condition.feature
  src/CoreShop/Behat/Context/Setup/ProductSpecificPriceRuleContext.php
  src/CoreShop/Component/Rule/Condition/NestedConditionChecker.php
Labels: bug

#530 [Behat] add tests for static resources
  features/pimcore/test_static_files.feature
  src/CoreShop/Behat/Context/Domain/PimcoreContext.php
  src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
  src/CoreShop/Behat/Resources/config/suites/domain/pimcore.yml
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Extension/AbstractPimcoreExtension.php
Labels: enhancement

#532 store voucher usages
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_order.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
  src/CoreShop/Component/Order/Modifier/VoucherModifier.php
  src/CoreShop/Component/Order/Modifier/VoucherModifierInterface.php
Labels: bug

#529 [All] fix install configuration node type
  src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CustomerBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/FrontendBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Configuration.php
Labels: bug

#527 Price rule outdater
  docs/02_User_Documentation/03_Price_Rules/README.md
  docs/02_User_Documentation/10_Automation/README.md
  docs/02_User_Documentation/README.md
  docs/03_Development/04_Cart/05_Commands.md
  docs/03_Development/14_Events/README.md
  docs/03_Development/17_State_Machine/03_Things_To_Know.md
  src/CoreShop/Bundle/CoreBundle/EventListener/Rule/AvailabilityCheckMaintenanceListener.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/commands.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.CartPriceRule.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.ProductPriceRule.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/specificprice/object/item.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/panel.js
  src/CoreShop/Bundle/RuleBundle/Assessor/RuleAvailabilityAssessor.php
  src/CoreShop/Bundle/RuleBundle/Command/RuleAvailabilityProcessorCommand.php
  src/CoreShop/Bundle/RuleBundle/CoreShopRuleBundle.php
  src/CoreShop/Bundle/RuleBundle/DependencyInjection/Compiler/RuleAvailabilityAssessorPass.php
  src/CoreShop/Bundle/RuleBundle/Event/RuleAvailabilityCheckEvent.php
  src/CoreShop/Bundle/RuleBundle/Processor/RuleAvailabilityProcessor.php
  src/CoreShop/Bundle/RuleBundle/Processor/RuleAvailabilityProcessorInterface.php
  src/CoreShop/Bundle/RuleBundle/Resources/config/services.yml
  src/CoreShop/Bundle/RuleBundle/Resources/config/services/commands.yml
  src/CoreShop/Bundle/RuleBundle/Resources/config/services/rule_active_validator.yml
  src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/css/rule.css
  src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/panel.js
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services/shipping-rules.yml
  src/CoreShop/Component/Rule/Assessor/RuleAvailabilityAssessorInterface.php
Labels: enhancement, new feature

#537 [IndexBundle] make index-command more performant
  src/CoreShop/Bundle/IndexBundle/Command/IndexCommand.php
Labels: enhancement

#538 [ResourceBundle] improve Pimcore ObjectManager
  src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php
Labels: enhancement

#545 [Index] Relational select
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/css/index.css
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/relational_select.js
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Index/Filter/RelationalSelectConditionProcessor.php
Labels: new feature

#535 [OrderBundle, CoreBundle] fix Order creation for inherited values
  src/CoreShop/Bundle/CoreBundle/Controller/CoreSaleCreationTrait.php
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleController.php
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleCreationController.php
Labels: bug

#536 [CoreBundle, ProductBundle] Lazy Loading Core Extensions
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180719151524.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/Product/SpecificPrice.php
Labels: enhancement

#557 [All] remove all usages of pimcore_id from container
  src/CoreShop/Behat/Extension/CoreShopExtension.php
  src/CoreShop/Behat/Listener/SetupCacheClearListener.php
  src/CoreShop/Behat/Resources/config/profiles/default.yml
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180409073455.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180410050946.php
  src/CoreShop/Bundle/CoreBundle/Report/AbandonedCartsReport.php
  src/CoreShop/Bundle/CoreBundle/Report/CarriersReport.php
  src/CoreShop/Bundle/CoreBundle/Report/CartsReport.php
  src/CoreShop/Bundle/CoreBundle/Report/CategoriesReport.php
  src/CoreShop/Bundle/CoreBundle/Report/CustomersReport.php
  src/CoreShop/Bundle/CoreBundle/Report/PaymentProvidersReport.php
  src/CoreShop/Bundle/CoreBundle/Report/ProductsReport.php
  src/CoreShop/Bundle/CoreBundle/Report/SalesReport.php
  src/CoreShop/Bundle/CoreBundle/Report/VouchersReport.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_customer.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_order.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_product.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/reports.yml
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/OrderBundle/Controller/QuoteController.php
  src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterPimcoreRepositoriesPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterPimcoreResourcesPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackClassesPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Driver/Pimcore/PimcoreDriver.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Extension/AbstractModelExtension.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreGridConfigInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/PimcoreRepository.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepository.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services/installer.yml
  src/CoreShop/Component/Resource/Repository/PimcoreRepositoryInterface.php
Labels: BC break

#551 [Order Creation] UI improvements
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/sale/create/step/base.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/base.js
  src/CoreShop/Bundle/StoreBundle/Resources/public/pimcore/js/item.js
Labels: bug

#565 Fix issue with calling delete on array
  src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php
Labels: bug
