Repository coreshop/CoreShop, pull requests merged in 2018-10, with the labels that each got.

#664 [TrackingBundle] fix template notation for tracking
  src/CoreShop/Bundle/TrackingBundle/Tracker/AbstractEcommerceTracker.php
  src/CoreShop/Bundle/TrackingBundle/Tracker/Google/AnalyticsEnhancedEcommerce.php
  src/CoreShop/Bundle/TrackingBundle/Tracker/Google/GlobalSiteTagEnhancedEcommerce.php
  src/CoreShop/Bundle/TrackingBundle/Tracker/Google/TagManager/TagManagerClassicEcommerce.php
  src/CoreShop/Bundle/TrackingBundle/Tracker/Google/TagManager/TagManagerEnhancedEcommerce.php
  src/CoreShop/Bundle/TrackingBundle/Tracker/Google/UniversalEcommerce.php
  src/CoreShop/Bundle/TrackingBundle/Tracker/Matomo/Matomo.php
Labels: bug

#666 [FixtureBundle] refactor fixture-bundle to be a resource-bundle
  src/CoreShop/Bundle/FixtureBundle/CoreShopFixtureBundle.php
  src/CoreShop/Bundle/FixtureBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/FixtureBundle/DependencyInjection/CoreShopFixtureExtension.php
  src/CoreShop/Bundle/FixtureBundle/Fixture/Loader/DataFixturesLoader.php
  src/CoreShop/Bundle/FixtureBundle/Fixture/UpdateDataFixturesFixture.php
  src/CoreShop/Bundle/FixtureBundle/Model/DataFixture.php
  src/CoreShop/Bundle/FixtureBundle/Model/DataFixtureInterface.php
  src/CoreShop/Bundle/FixtureBundle/Repository/DataFixtureRepository.php
  src/CoreShop/Bundle/FixtureBundle/Repository/DataFixtureRepositoryInterface.php
  src/CoreShop/Bundle/FixtureBundle/Resources/config/doctrine/model/DataFixture.orm.yml
  src/CoreShop/Bundle/FixtureBundle/Resources/config/services.yml
  src/CoreShop/Bundle/FixtureBundle/composer.json
Labels: enhancement

#663 [ResourceBundle] properly configure jms-serializer
  src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
Labels: bug

#667 [Setup] change setup command to only install CoreShop tables
  src/CoreShop/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
  src/CoreShop/Bundle/ResourceBundle/Command/CreateDatabaseTablesCommand.php
  src/CoreShop/Bundle/ResourceBundle/Command/DropDatabaseTablesCommand.php
Labels: bug, enhancement

#672 Quotes folder is created during installation and Quotes menu works wi…
  src/CoreShop/Bundle/CoreBundle/Installer/Executor/FolderInstallerProvider.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/installer.yml
Labels: enhancement

#673 [Currency] fix save currency
  src/CoreShop/Bundle/CurrencyBundle/Form/Type/CurrencyType.php
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/currency/item.js
Labels: bug

#675 Use decimal as column type instead of double
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
Labels: bug

#676 Check if value is instance of Carbon already
  src/CoreShop/Component/Index/Interpreter/TimestampInterpreter.php
Labels: bug

#677 Keep notification param in MailActionProcessor
  src/CoreShop/Bundle/CoreBundle/EventListener/Order/OrderMailNoteEventListener.php
  src/CoreShop/Component/Notification/Rule/Action/MailActionProcessor.php
Labels: bug

#681 [Pimcore] introduce batch list helper
  etc/_scripts/phpunit
  phpunit.xml.dist
  src/CoreShop/Component/Pimcore/BatchProcessing/BatchListing.php
  tests/lib/CoreShop/Test/PHPUnit/Component/Pimcore/BatchListingTest.php
  tests/lib/CoreShop/Test/PHPUnit/Component/Pimcore/Suite.php
Labels: enhancement

#668 [Travis] use right version for Pimcore tests
  .travis.yml
  etc/_scripts/ecs
  etc/_setup/install
  etc/travis/setup/ecs/install
  src/CoreShop/Behat/Context/Hook/PimcoreDaoContext.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Component/Address/Formatter/AddressFormatter.php
  src/CoreShop/Component/Core/Shipping/Rule/Action/DiscountAmountActionProcessor.php
  tests/lib/CoreShop/Test/Setup.php
Labels: bug
