Repository coreshop/CoreShop, pull requests merged in 2018-08, with the labels that each got.

#568 [FrontendBundle] show order-detail in revise and thank-you page
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180731140144.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/thank-you.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/order_detail.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/order_detail.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Order/revise.html.twig
Labels: enhancement

#569 [CoreBundle] further improve persisting time of StorePrices
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
Labels: enhancement

#570 [PimcoreBundle] add BC layer to Pimcore 5.4.0
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopItemSelector.js
Labels: bug

#571 [OrderBundle] fix OrderState grid operator
  src/CoreShop/Bundle/OrderBundle/Pimcore/GridColumnConfig/Operator/OrderState.php
Labels: bug

#586 [Core, Locale] fix usage of LocaleService
  src/CoreShop/Component/Core/Translation/TranslatableEntityPimcoreLocaleAssigner.php
  src/CoreShop/Component/Locale/Context/PimcoreLocaleContext.php
Labels: bug

#587 Cart price rule issues
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180814081956.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopCartItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopCartItem.json
  src/CoreShop/Bundle/OrderBundle/Validator/Constraints/CartPriceRuleValidator.php
  src/CoreShop/Component/Core/Cart/Rule/Action/DiscountAmountActionProcessor.php
  src/CoreShop/Component/Core/Cart/Rule/Action/DiscountPercentActionProcessor.php
  src/CoreShop/Component/Core/Cart/Rule/Applier/DiscountApplier.php
  src/CoreShop/Component/Core/Cart/Rule/Applier/DiscountApplierInterface.php
  src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartRuleAutoRemoverProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartTaxProcessor.php
  src/CoreShop/Component/Order/Cart/Rule/CartPriceRuleProcessor.php
  src/CoreShop/Component/Order/Distributor/ProportionalIntegerDistributor.php
  src/CoreShop/Component/Order/Distributor/ProportionalIntegerDistributorInterface.php
  src/CoreShop/Component/Order/Model/CartItem.php
  src/CoreShop/Component/Order/Model/ProposalItemInterface.php
  src/CoreShop/Component/Order/Model/ProposalPriceRuleTrait.php
  src/CoreShop/Component/Order/Model/SaleItemInterface.php
  src/CoreShop/Component/Rule/Condition/TraceableRuleConditionsValidationProcessor.php
  src/CoreShop/Component/Taxation/Collector/TaxCollector.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/CartPriceRule.php
Labels: bug

#597 Fix orderState check in payum extension
  src/CoreShop/Bundle/PayumBundle/Extension/UpdateOrderStateExtension.php
Labels: bug

#596 [CoreBundle, ProductBundle] remove unused product grid
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/grid.js
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/resource.js
Labels: bug

#595 [Inventory] check tracked inventory for all items including those in cart
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/summary.html.twig
Labels: bug

#594 [Notification] add actual workflow-name for State Transition Checker
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/OrderWorkflowListener.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/notification.yml
  src/CoreShop/Component/Core/Notification/Rule/Condition/StateTransitionChecker.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/NotificationRule.php
Labels: bug

#593 [Order, Core] fix cart rule condition checker signature with opt param
  src/CoreShop/Component/Core/Cart/Rule/Condition/CarriersConditionChecker.php
  src/CoreShop/Component/Core/Cart/Rule/Condition/CategoriesConditionChecker.php
  src/CoreShop/Component/Core/Cart/Rule/Condition/CountriesConditionChecker.php
  src/CoreShop/Component/Core/Cart/Rule/Condition/CurrenciesConditionChecker.php
  src/CoreShop/Component/Core/Cart/Rule/Condition/CustomerGroupsConditionChecker.php
  src/CoreShop/Component/Core/Cart/Rule/Condition/CustomersConditionChecker.php
  src/CoreShop/Component/Core/Cart/Rule/Condition/ProductsConditionChecker.php
  src/CoreShop/Component/Core/Cart/Rule/Condition/StoresConditionChecker.php
  src/CoreShop/Component/Core/Cart/Rule/Condition/ZonesConditionChecker.php
  src/CoreShop/Component/Order/Cart/Rule/Condition/AmountConditionChecker.php
  src/CoreShop/Component/Order/Cart/Rule/Condition/CartRuleConditionCheckerInterface.php
  src/CoreShop/Component/Order/Cart/Rule/Condition/TimeSpanConditionChecker.php
  src/CoreShop/Component/Order/Cart/Rule/Condition/VoucherConditionChecker.php
Labels: BC break

#558 [OrderBundle] improve order creation view confirmation message #548
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/sale/create/step/shipping.js
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleCreationController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderCreationController.php
  src/CoreShop/Bundle/OrderBundle/Controller/QuoteCreationController.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/css/order.css
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/create/panel.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/abstractStep.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/panel.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/address.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/base.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/payment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/products.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/totals.js
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
Labels: enhancement

#599 [ResourceBundle] improve document installer
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDocumentsInstaller.php
Labels: enhancement

#600 [CoreBundle] rename InstallClasses Command to InstallResources
  src/CoreShop/Bundle/CoreBundle/Command/InstallCommand.php
  src/CoreShop/Bundle/CoreBundle/Command/InstallResourcesCommand.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/commands.yml
Labels: enhancement

#559 [OrderBundle, CoreBundle] add manually created flag for order/sale
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Notification/Condition/BackendCreatedConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180726131622.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/notification.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuote.json
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/css/core.css
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/img/orders-backend.svg
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/order/backendCreated.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleCreationController.php
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuote.json
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/totals.js
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Core/Notification/Rule/Condition/Order/BackendCreatedChecker.php
  src/CoreShop/Component/Order/Model/Sale.php
  src/CoreShop/Component/Order/Model/SaleInterface.php
Labels: enhancement, new feature

#602 [Non-CoreShop-Sites] allow CoreShop to co-exist along none CoreShop Sites
  src/CoreShop/Bundle/AddressBundle/Collector/CountryCollector.php
  src/CoreShop/Bundle/AddressBundle/Resources/views/Collector/country.html.twig
  src/CoreShop/Bundle/CoreBundle/EventListener/RequestCartAvailability.php
  src/CoreShop/Bundle/CoreBundle/EventListener/RequestCartRecalculation.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
  src/CoreShop/Bundle/CoreBundle/Resources/views/Collector/currency.html.twig
  src/CoreShop/Bundle/OrderBundle/Collector/CartCollector.php
  src/CoreShop/Bundle/OrderBundle/Resources/views/Collector/cart.html.twig
  src/CoreShop/Bundle/RuleBundle/Resources/views/Collector/rule.html.twig
  src/CoreShop/Bundle/StoreBundle/Collector/StoreCollector.php
  src/CoreShop/Bundle/StoreBundle/Resources/views/Collector/store.html.twig
Labels: bug

#603 [Installer] remove assets:install command and also mark the installer version as migrated
  src/CoreShop/Bundle/CoreBundle/Command/AssetsInstallCommand.php
  src/CoreShop/Bundle/CoreBundle/Command/InstallCommand.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/commands.yml
Labels: task

#605 Adjustments
  CHANGELOG.md
  app/TestAppKernel.php
  phpunit.xml.dist
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180825142227.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180825163827.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopCart.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopCartItem.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderItem.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuote.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuoteItem.json
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_summary.html.twig
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopCart.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopCartItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuote.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuoteItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/fieldcollections/CoreShopAdjustment.json
  src/CoreShop/Component/Core/Model/Cart.php
  src/CoreShop/Component/Core/Model/CartInterface.php
  src/CoreShop/Component/Core/Order/Processor/CartPriceRuleProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartShippingProcessor.php
  src/CoreShop/Component/Core/Order/Transformer/CartToSaleTransformer.php
  src/CoreShop/Component/Order/Factory/AdjustmentFactory.php
  src/CoreShop/Component/Order/Factory/AdjustmentFactoryInterface.php
  src/CoreShop/Component/Order/Model/AbstractProposal.php
  src/CoreShop/Component/Order/Model/AdjustableInterface.php
  src/CoreShop/Component/Order/Model/AdjustableTrait.php
  src/CoreShop/Component/Order/Model/Adjustment.php
  src/CoreShop/Component/Order/Model/AdjustmentInterface.php
  src/CoreShop/Component/Order/Model/BaseAdjustableInterface.php
  src/CoreShop/Component/Order/Model/BaseAdjustableTrait.php
  src/CoreShop/Component/Order/Model/Cart.php
  src/CoreShop/Component/Order/Model/CartInterface.php
  src/CoreShop/Component/Order/Model/CartItem.php
  src/CoreShop/Component/Order/Model/CartItemInterface.php
  src/CoreShop/Component/Order/Model/ProposalInterface.php
  src/CoreShop/Component/Order/Model/ProposalItemInterface.php
  src/CoreShop/Component/Order/Model/Sale.php
  src/CoreShop/Component/Order/Model/SaleInterface.php
  src/CoreShop/Component/Order/Model/SaleItem.php
  src/CoreShop/Component/Order/Model/SaleItemInterface.php
  src/CoreShop/Component/Order/Transformer/AbstractCartItemToSaleItemTransformer.php
  src/CoreShop/Component/Order/Transformer/AbstractCartToSaleTransformer.php
  tests/behat-bootstrap.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/CartPriceRule.php
Labels: BC break, enhancement

#610 [Expression] refactor expression engine to be extendable via services
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/ExpressionLanguageServicePass.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
  src/CoreShop/Component/Index/Interpreter/ExpressionInterpreter.php
  src/CoreShop/Component/Pimcore/ExpressionLanguage/ExpressionLanguage.php
  src/CoreShop/Component/Pimcore/ExpressionLanguage/PHPFunctionsProvider.php
  src/CoreShop/Component/Pimcore/ExpressionLanguage/PimcoreLanguageProvider.php
  src/CoreShop/Component/Pimcore/Placeholder/Expression.php
Labels: enhancement

#616 [ResourceBundle] fix getClassIds for StackRepository
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackRepositoryPass.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepository.php
Labels: bug

#615 [All] change the way of defining the js/css files
  src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/AddressBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/AddressBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CurrencyBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/CustomerBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CustomerBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/MoneyBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/MoneyBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/MoneyBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/NotificationBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/NotificationBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/NotificationBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/PaymentBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/PaymentBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/RuleBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/RuleBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/RuleBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ShippingBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/StoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/StoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/StoreBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/TaxationBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/TaxationBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/TaxationBundle/Resources/config/pimcore/config.yml
Labels: bug

#608 [All] refine constraints for certain conditions/actions
  features/shipping/default_carrier_customer.feature
  src/CoreShop/Bundle/OrderBundle/Form/Type/Action/DiscountAmountConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Action/DiscountPercentConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Condition/AmountConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Action/DiscountAmountConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Action/DiscountPercentConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/AdditionAmountActionConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/AdditionPercentActionConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/DiscountAmountActionConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/DiscountPercentActionConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/AmountConfigurationType.php
Labels: bug

#607 [Pimcore] implement field renamer for better migrations
  src/CoreShop/Component/Pimcore/DataObject/AbstractDefinitionUpdate.php
  src/CoreShop/Component/Pimcore/DataObject/ClassDefinitionFieldReNamer.php
  src/CoreShop/Component/Pimcore/DataObject/ClassUpdate.php
  src/CoreShop/Component/Pimcore/DataObject/ClassUpdateRenameInterface.php
  src/CoreShop/Component/Pimcore/DataObject/DefinitionFieldReNamerInterface.php
Labels: new feature
