Repository coreshop/CoreShop, pull requests merged in 2018-03, with the labels that each got.

#356 [OrderDetail] Improve Order Detail Block Loader
  docs/03_Development/06_Order/09_AdditionalData.md
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/order/detail.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/order/detail/blocks/carriage.js
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/helper.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/comments.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/correspondence.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/customer.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/header.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/info.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/invoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/payment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/shipment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/panel.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/shipment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/state/changeState.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/quote/detail/panel.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/panel.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/abstractBlock.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/correspondence.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/customer.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/header.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/info.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/panel.js
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/eventManager.js
Labels: coreshop2, enhancement, new feature

#332 Translate tax display
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/detail.html.twig
Labels: coreshop2, task

#381 [Customer] implement roles like members-bundle does and remove deprec…
  src/CoreShop/Bundle/CoreBundle/Customer/RegistrationService.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180326090909.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/app/security.yml
  src/CoreShop/Bundle/CustomerBundle/CoreExtension/Provider/RoleOptionsProvider.php
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomerGroup.json
  src/CoreShop/Component/Customer/Model/Customer.php
  src/CoreShop/Component/Customer/Model/CustomerGroup.php
  src/CoreShop/Component/Customer/Model/CustomerGroupInterface.php
  src/CoreShop/Component/Customer/Model/CustomerInterface.php
Labels: bug, coreshop2

#385 Default Carrier Resolver
  features/shipping/default_carrier.feature
  src/CoreShop/Behat/Context/Domain/CartContext.php
  src/CoreShop/Behat/Context/Domain/ShippingContext.php
  src/CoreShop/Behat/Context/Setup/ShippingContext.php
  src/CoreShop/Bundle/CoreBundle/Checkout/Step/ShippingCheckoutStep.php
  src/CoreShop/Bundle/CoreBundle/EventListener/CartBlamerListener.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/CoreShopShippingExtension.php
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services.yml
  src/CoreShop/Component/Core/Order/Processor/CartShippingProcessor.php
  src/CoreShop/Component/Core/Provider/AddressProviderInterface.php
  src/CoreShop/Component/Core/Provider/StoreBasedAddressProvider.php
  src/CoreShop/Component/Shipping/Exception/UnresolvedDefaultCarrierException.php
  src/CoreShop/Component/Shipping/Resolver/CheapestDefaultCarrierResolver.php
  src/CoreShop/Component/Shipping/Resolver/DefaultCarrierResolverInterface.php
  tests/lib/CoreShop/Test/Data.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/AllTests.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/Cart.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/CartPriceRule.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/Customer.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/Product.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/Product/Index.php
Labels: coreshop2, new feature
