Repository coreshop/CoreShop, pull requests merged in 2018-12, with the labels that each got.

#739 [Tests] fix scruitinizer setup
  .scrutinizer.yml
Labels: task

#740 Fix for StoreMailActionProcessor exception in Notification Rule.
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/CustomerListener.php
Labels: bug

#742 Utf8 safely path for folders
  src/CoreShop/Bundle/CoreBundle/Customer/RegistrationService.php
Labels: enhancement

#744 Fix Filter Query
  src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
Labels: bug

#738 [OrderBundle] fix order-document state-resolvers when a document is cancelled
  features/order/order_workflow_when_invoice_cancelled.feature
  features/order/order_workflow_when_shipment_cancelled.feature
  src/CoreShop/Bundle/OrderBundle/StateResolver/OrderInvoiceStateResolver.php
  src/CoreShop/Bundle/OrderBundle/StateResolver/OrderShippingStateResolver.php
Labels: bug

#735 Remove login customer after successfully registration
  src/CoreShop/Bundle/CoreBundle/Customer/CustomerLoginService.php
  src/CoreShop/Bundle/CoreBundle/Customer/CustomerLoginServiceInterface.php
  src/CoreShop/Bundle/CoreBundle/Customer/RegistrationService.php
  src/CoreShop/Bundle/CoreBundle/EventListener/CustomerLoginListener.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/customer.yml
Labels: enhancement

#741 [Shipping] shipping is valid when no shipping rule is configured
  features/shipping/carrier_with_no_shipping_rules_valid.feature
  src/CoreShop/Behat/Context/Domain/ShippingContext.php
  src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
  src/CoreShop/Component/Shipping/Checker/CarrierShippingRuleChecker.php
Labels: bug

#746 [CoreBundle] remove cascading of store deletetions for countries
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Store.orm.yml
Labels: bug
