Repository coreshop/CoreShop, pull requests merged in 2018-04, with the labels that each got.

#389 [Shipping] remove Range Behaviour feature entirely
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/CarrierFixture.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/CarrierType.php
  src/CoreShop/Bundle/ShippingBundle/Resources/config/doctrine/model/Carrier.orm.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/serializer/Model.Carrier.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/validation/Carrier.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/carrier/item.js
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Shipping/Model/Carrier.php
  src/CoreShop/Component/Shipping/Model/CarrierInterface.php
  tests/lib/CoreShop/Test/Data.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/Carrier.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/ShippingRule.php
Labels: coreshop2

#392 Proposal: Product display restriction by store
  src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php
Labels: coreshop2, enhancement

#403 Refactor Locale Code Properties to unify them
  src/CoreShop/Bundle/CoreBundle/Customer/RegistrationService.php
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/OrderCommentsListener.php
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/OrderWorkflowListener.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180408091435.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180410050946.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180410063351.php
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCustomer.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopCart.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuote.json
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomer.json
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleCreationController.php
  src/CoreShop/Bundle/OrderBundle/Renderer/OrderDocumentPdfRenderer.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopCart.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuote.json
  src/CoreShop/Bundle/PayumBundle/Action/Offline/ResolveNextRouteAction.php
  src/CoreShop/Bundle/PayumBundle/Action/ResolveNextRouteAction.php
  src/CoreShop/Component/Core/Context/StoreBasedCartContext.php
  src/CoreShop/Component/Core/Notification/Rule/Action/Order/OrderMailActionProcessor.php
  src/CoreShop/Component/Customer/Model/Customer.php
  src/CoreShop/Component/Customer/Model/CustomerInterface.php
  src/CoreShop/Component/Customer/composer.json
  src/CoreShop/Component/Locale/Context/PimcoreLocaleContext.php
  src/CoreShop/Component/Locale/Model/LocaleAwareInterface.php
  src/CoreShop/Component/Order/Model/AbstractProposal.php
  src/CoreShop/Component/Order/Model/CartInterface.php
  src/CoreShop/Component/Order/Model/Order.php
  src/CoreShop/Component/Order/Model/OrderInterface.php
  src/CoreShop/Component/Order/Model/ProposalInterface.php
  src/CoreShop/Component/Order/Model/Quote.php
  src/CoreShop/Component/Order/Model/SaleInterface.php
  src/CoreShop/Component/Order/Transformer/AbstractCartToSaleTransformer.php
  src/CoreShop/Component/Order/composer.json
Labels: coreshop2

#366 [Index] refactor index class helpers to index extensions
  docs/03_Development/08_Index_and_Filters/01_Index/02_Extension.md
  docs/03_Development/11_Stores/02_Context.md
  src/CoreShop/Bundle/CoreBundle/CoreShopCoreBundle.php
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterIndexProductExtensionPass.php
  src/CoreShop/Bundle/IndexBundle/Condition/MysqlRenderer.php
  src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterExtensionsPass.php
  src/CoreShop/Bundle/IndexBundle/Extension/MysqlIndexQueryExtensionInterface.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing/Dao.php
  src/CoreShop/Component/Core/Index/Extensions/ProductClassExtension.php
  src/CoreShop/Component/Index/Condition/Condition.php
  src/CoreShop/Component/Index/Extension/IndexColumnsExtensionInterface.php
  src/CoreShop/Component/Index/Extension/IndexExtensionInterface.php
  src/CoreShop/Component/Index/Worker/WorkerInterface.php
Labels: coreshop2, new feature

#407 Add prefix to mysql worker listing
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing/Dao.php
Labels: coreshop2

#408 [Beta.1] Prepare Release
  CHANGELOG.md
  src/CoreShop/Bundle/CoreBundle/Application/RegisterBundleHelper.php
Labels: coreshop2

#417 [CoreBundle] reset original value of store prices on save
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopStorePrice.js
Labels: bug, coreshop2

#416 [IndexBundle] fix issue with storing boolean false values
  features/index/boolean_column.feature
  src/CoreShop/Behat/Context/Domain/IndexContext.php
  src/CoreShop/Behat/Context/Setup/PimcoreClassContext.php
  src/CoreShop/Behat/Context/Transform/PimcoreClassContext.php
  src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
Labels: bug, coreshop2

#424 wkHtmlToPdf Improvements
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/OrderBundle/Controller/OrderInvoiceController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderShipmentController.php
  src/CoreShop/Bundle/OrderBundle/Renderer/AssetOrderDocumentPdfRenderer.php
  src/CoreShop/Bundle/OrderBundle/Renderer/Pdf/WkHtmlToPdf.php
  src/CoreShop/Component/Core/Order/OrderMailProcessor.php
Labels: task
