Repository coreshop/CoreShop, pull requests merged in 2018-02, with the labels that each got.

#315 Fixed search condition filtering only products set as active
  src/CoreShop/Bundle/FrontendBundle/Controller/SearchController.php
Labels: bug

#341 [Order, OrderBundle] Discount Actions: total or subtotal
  src/CoreShop/Bundle/OrderBundle/Form/Type/Action/DiscountAmountConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Action/DiscountPercentConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/actions/discountAmount.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/actions/discountPercent.js
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Order/Cart/Rule/Action/DiscountAmountActionProcessor.php
  src/CoreShop/Component/Order/Cart/Rule/Action/DiscountPercentActionProcessor.php
Labels: coreshop2, enhancement, new feature

#340 CustomerAndStoreBasedCartContext should only get applied in login route
  src/CoreShop/Bundle/CoreBundle/EventListener/CartBlamerListener.php
  src/CoreShop/Bundle/OrderBundle/Context/CustomerAndStoreBasedCartContext.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/context.yml
Labels: task

#338 Refactor Country Context
  src/CoreShop/Bundle/AddressBundle/Form/Type/CountryChoiceType.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php
  src/CoreShop/Bundle/CoreBundle/Form/Extension/CountryTypeExtension.php
  src/CoreShop/Bundle/CoreBundle/Form/Extension/StoreTypeExtension.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20180226085136.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Country.orm.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Store.orm.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/serializer/Model.Store.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/context.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/address/country/item.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/store/item.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleCreationController.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepository.php
  src/CoreShop/Component/Address/Model/CountriesAwareInterface.php
  src/CoreShop/Component/Address/Model/CountriesAwareTrait.php
  src/CoreShop/Component/Core/Context/CartBasedCountryResolver.php
  src/CoreShop/Component/Core/Context/Country/StoreAwareCountryContext.php
  src/CoreShop/Component/Core/Context/Currency/CountryAwareCurrencyContext.php
  src/CoreShop/Component/Core/Context/Currency/StorageBasedCurrencyContext.php
  src/CoreShop/Component/Core/Context/Currency/StoreAwareCurrencyContext.php
  src/CoreShop/Component/Core/Context/StoreBasedCountryResolver.php
  src/CoreShop/Component/Core/Model/Store.php
  src/CoreShop/Component/Core/Model/StoreInterface.php
  src/CoreShop/Component/Order/Factory/CartFactory.php
  tests/lib/CoreShop/Test/Data.php
Labels: coreshop2, enhancement
