Repository coreshop/CoreShop, pull requests merged in 2018-09, with the labels that each got.

#617 [CoreBundle] Updated the Tracking ItemBuilder to use configured product class
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/tracking.yml
  src/CoreShop/Bundle/CoreBundle/Tracking/Builder/ItemBuilder.php
Labels: potential bug

#621 fix wishlist findTemplate() parameter
  src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php
Labels: bug

#625 [Locale] only return a valid locale
  src/CoreShop/Component/Locale/Context/PimcoreLocaleContext.php
Labels: bug

#633 [NotificationBundle] Fix coreshop_path and inherited product getters …
  src/CoreShop/Bundle/CoreBundle/Pimcore/LinkGenerator/DataObjectLinkGenerator.php
  src/CoreShop/Component/Notification/Rule/Action/MailActionProcessor.php
Labels: bug

#631 [Pimcore] Introduce a new Image Thumbnail Twig Extension
  src/CoreShop/Component/Pimcore/Twig/Extension/ImageThumbnailExtension.php
  src/CoreShop/Component/Pimcore/Twig/Extension/ObjectHelperExtensions.php
Labels: enhancement, new feature

#629 [CoreExtensions] stay compatible with Pimcore 5.5
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/EmbeddedClass.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Multiselect.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php
Labels: bug

#624 [CartRules] fix usage of multiple rules with different vouchers per cart
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/OrderBundle/Validator/Constraints/CartPriceRuleValidator.php
  src/CoreShop/Component/Core/Cart/Rule/Action/DiscountAmountActionProcessor.php
  src/CoreShop/Component/Core/Cart/Rule/Applier/DiscountApplier.php
  src/CoreShop/Component/Core/Order/Processor/CartAdjustmentClearer.php
  src/CoreShop/Component/Core/Order/Processor/CartPriceRuleVoucherProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartRuleAutoProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartRuleAutoRemoverProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartShippingProcessor.php
  src/CoreShop/Component/Order/Cart/Rule/CartPriceRuleProcessor.php
  src/CoreShop/Component/Order/Cart/Rule/CartPriceRuleProcessorInterface.php
  src/CoreShop/Component/Order/Cart/Rule/CartPriceRuleUnProcessor.php
  src/CoreShop/Component/Order/Cart/Rule/Condition/VoucherConditionChecker.php
  src/CoreShop/Component/Order/Cart/Rule/ProposalCartPriceRuleCalculator.php
  src/CoreShop/Component/Order/Model/CartInterface.php
  src/CoreShop/Component/Order/Model/ProposalPriceRuleTrait.php
  src/CoreShop/Component/Order/Model/SaleInterface.php
Labels: BC break, bug, enhancement

#639 add StorePrice CSV import/export feature; resolve #637
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
Labels: enhancement

#644 [fix] StorePrice CSV import: check for JSON decode errors
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
Labels: bug

#650 [FrontendBundle] implement locale switcher
  src/CoreShop/Bundle/FrontendBundle/Controller/LanguageController.php
  src/CoreShop/Bundle/FrontendBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/FrontendBundle/Resources/config/services.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Language/_widget.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/_header.html.twig
  src/CoreShop/Bundle/FrontendBundle/Twig/LocaleSwitcherExtension.php
Labels: enhancement
