Repository coreshop/CoreShop, pull requests merged in 2019-02, with the labels that each got.

#794 [Rules] allow variants in price-rules
  features/cart/rules/product_variant_condition.feature
  features/product/price_rules/product_variant_condition.feature
  features/shipping/shipping_rules/product_variant_condition.feature
  src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
  src/CoreShop/Behat/Context/Setup/ProductContext.php
  src/CoreShop/Behat/Context/Setup/ProductPriceRuleContext.php
  src/CoreShop/Behat/Context/Setup/ShippingContext.php
  src/CoreShop/Behat/Context/Transform/ProductContext.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Rule/Condition/ProductsConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/ProductRepository.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/shipping.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/pricerule/conditions/products.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/conditions/products.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Condition/ProductsConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/conditions/products.js
  src/CoreShop/Component/Core/Cart/Rule/Condition/ProductsConditionChecker.php
  src/CoreShop/Component/Core/Product/Rule/Condition/ProductsConditionChecker.php
  src/CoreShop/Component/Core/Repository/ProductVariantRepositoryInterface.php
  src/CoreShop/Component/Core/Rule/Condition/ProductVariantsCheckerTrait.php
  src/CoreShop/Component/Core/Shipping/Rule/Condition/ProductsConditionChecker.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/Product/PriceRule.php
Labels: enhancement

#796 [#795] fix cart-rule action gift product and add behat tests for it
  features/cart/rules/gift_product_action.feature
  src/CoreShop/Behat/Context/Domain/CartContext.php
  src/CoreShop/Behat/Context/Setup/CartContext.php
  src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
  src/CoreShop/Bundle/CoreBundle/Report/AbandonedCartsReport.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/OrderBundle/Form/Type/CartItemType.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php
  src/CoreShop/Component/Core/Cart/Rule/Condition/ProductsConditionChecker.php
  src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php
  src/CoreShop/Component/Core/Shipping/Rule/Condition/ProductsConditionChecker.php
  src/CoreShop/Component/Order/Cart/CartModifier.php
  src/CoreShop/Component/Order/Cart/Rule/CartPriceRuleUnProcessor.php
  src/CoreShop/Component/Order/Cart/Rule/ProposalCartPriceRuleCalculator.php
  src/CoreShop/Component/Order/Factory/CartItemFactory.php
  src/CoreShop/Component/Order/Factory/CartItemFactoryInterface.php
  src/CoreShop/Component/Order/Model/Cart.php
Labels: bug

#803 [Index] introduce new abstract function to allow handling array data better for other providers
  src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
Labels: enhancement

#804 [CoreBundle] implement dirty detection for store-price
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
Labels: enhancement

#805 [All] replace intval with (int), casting is way faster than intval
  src/CoreShop/Behat/Context/Domain/CurrencyContext.php
  src/CoreShop/Behat/Context/Domain/ExchangeRateContext.php
  src/CoreShop/Behat/Context/Domain/IndexContext.php
  src/CoreShop/Behat/Context/Domain/ProductContext.php
  src/CoreShop/Behat/Context/Domain/ShippingContext.php
  src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
  src/CoreShop/Behat/Context/Setup/ExchangeRateContext.php
  src/CoreShop/Behat/Context/Setup/ProductPriceRuleContext.php
  src/CoreShop/Behat/Context/Setup/ProductSpecificPriceRuleContext.php
  src/CoreShop/Behat/Context/Setup/ShippingContext.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductFixture.php
  src/CoreShop/Bundle/CoreBundle/Report/CarriersReport.php
  src/CoreShop/Bundle/CoreBundle/Report/PaymentProvidersReport.php
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderPaymentController.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php
  src/CoreShop/Component/Index/Interpreter/SoundexInterpreter.php
  src/CoreShop/Component/Index/Worker/FilterGroupHelper.php
Labels: enhancement

#807 Store price dirty detection
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
Labels: enhancement

#809 [Pimcore] add object_method twig function
  src/CoreShop/Component/Pimcore/Twig/Extension/ObjectHelperExtensions.php
Labels: enhancement

#808 [Release] 2.0.3
  CHANGELOG-2.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#810 Update CompositeTracker::trackCheckoutStep
  src/CoreShop/Component/Tracking/Tracker/CompositeTracker.php
Labels: bug

#813 [QuantityRules] merge ItemQuantityRangePriceProcessor with CartItemsProcessor
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/product-quantity-price-rules.yml
  src/CoreShop/Component/Core/Order/Processor/CartItemQuantityRangePriceProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php
Labels: enhancement

#815 [ResourceBundle] move settings icon to resource-bundle
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/css/core.css
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/css/index.css
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/img/services.svg
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/css/resource.css
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/img/services.svg
Labels: bug, enhancement

#818 [ResourceBundle] add serialization for pimcore types
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/Serialization/PimcoreAssetHandler.php
  src/CoreShop/Bundle/ResourceBundle/Serialization/PimcoreDocumentHandler.php
  src/CoreShop/Bundle/ResourceBundle/Serialization/PimcoreSiteHandler.php
Labels: enhancement

#822 Fix dead link
  src/CoreShop/Bundle/FixtureBundle/README.md
Labels: docs

#826 Add Paginator To All Reports
  src/CoreShop/Bundle/CoreBundle/Report/CategoriesReport.php
  src/CoreShop/Bundle/CoreBundle/Report/CustomersReport.php
  src/CoreShop/Bundle/CoreBundle/Report/ManufacturerReport.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/reports.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/categories.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/customers.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/manufacturer.js
Labels: enhancement

#824 Fix State Labels
  src/CoreShop/Bundle/OrderBundle/Pimcore/GridColumnConfig/Operator/OrderState.php
Labels: bug

#828 Reports Grid Sorting
  src/CoreShop/Bundle/CoreBundle/Report/CategoriesReport.php
  src/CoreShop/Bundle/CoreBundle/Report/CustomersReport.php
  src/CoreShop/Bundle/CoreBundle/Report/ManufacturerReport.php
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/abstract.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/categories.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/customers.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/manufacturer.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/products.js
Labels: enhancement

#821 [Core] fix for cart-item digital product never set
  src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
Labels: bug

#829 [JS] Split JS Helpers into several regions of usability
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/helpers.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/helpers.js
  src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/helpers.js
Labels: bug, enhancement

#812 [Cart] implement add-to-cart as Symfony Form
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_product_quantity_price_rules.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/validators.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/validation/AddToCartCommand.yml
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/AddToCartAvailability.php
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/AddToCartAvailabilityValidator.php
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/QuantityRangePriceCurrencyAware.php
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/QuantityRangePriceCurrencyAwareValidator.php
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_grid.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_list.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Form/theme.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/_addToCart.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/_preview.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/detail.html.twig
  src/CoreShop/Bundle/OrderBundle/DTO/AddToCart.php
  src/CoreShop/Bundle/OrderBundle/DTO/AddToCartInterface.php
  src/CoreShop/Bundle/OrderBundle/Factory/AddToCartFactory.php
  src/CoreShop/Bundle/OrderBundle/Factory/AddToCartFactoryInterface.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/AddToCartType.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/forms.yml
Labels: enhancement

#833 [Order] fix code-generator length
  src/CoreShop/Component/Order/Generator/CartPriceRuleVoucherCodeGenerator.php
Labels: bug

#834 [Release] 2.0.4
  CHANGELOG-2.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#838 [ResourceBundle] introduce more basic form types
  src/CoreShop/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
  src/CoreShop/Bundle/ResourceBundle/Form/DataTransformer/PimcoreResourceDataTransformer.php
  src/CoreShop/Bundle/ResourceBundle/Form/Type/PimcoreResourceSelectionType.php
Labels: enhancement

#836 [AddressBundle] add translation for addresses
  src/CoreShop/Bundle/AddressBundle/Resources/translations/admin.en.yml
Labels: enhancement

#845 [ResourceBundle] fix for resource selection type
  src/CoreShop/Bundle/ResourceBundle/Form/Type/PimcoreResourceSelectionType.php
Labels: enhancement

#846 Fix autoloader paths -> wrong directory for namespace
  src/CoreShop/Behat/Model/Index/TestEnableIndex.php
  src/CoreShop/Behat/Model/Index/TestIndex.php
  src/CoreShop/Behat/Model/Index/TestIndexFields.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/ConfigurationFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CurrencyFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/NotificationRulesFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/StoreFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/ZoneFixture.php
  src/CoreShop/Bundle/CustomerBundle/Form/Type/ChangePasswordType.php
  src/CoreShop/Bundle/CustomerBundle/Form/Type/CustomerLoginType.php
  src/CoreShop/Bundle/CustomerBundle/Form/Type/CustomerType.php
  src/CoreShop/Bundle/CustomerBundle/Form/Type/RequestResetPasswordType.php
  src/CoreShop/Bundle/CustomerBundle/Form/Type/ResetPasswordType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Action/DiscountAmountConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Action/DiscountPercentConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/AmountConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/NestedConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/TimespanConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/VoucherConfigurationType.php
  src/CoreShop/Bundle/ResourceBundle/Validator/Constraints/Active.php
  src/CoreShop/Bundle/ResourceBundle/Validator/Constraints/ActiveValidator.php
  src/CoreShop/Bundle/ResourceBundle/Validator/Constraints/UniqueEntity.php
  src/CoreShop/Bundle/ResourceBundle/Validator/Constraints/UniqueEntityValidator.php
  src/CoreShop/Component/Address/Model/Address.php
  src/CoreShop/Component/Core/Model/Cart.php
  src/CoreShop/Component/Core/Model/Category.php
  src/CoreShop/Component/Core/Model/Customer.php
  src/CoreShop/Component/Core/Model/Order.php
  src/CoreShop/Component/Core/Model/Product.php
  src/CoreShop/Component/Core/Model/ProposalItemTrait.php
  src/CoreShop/Component/Core/Model/SaleItemTrait.php
  src/CoreShop/Component/Customer/Model/Customer.php
  src/CoreShop/Component/Customer/Model/CustomerGroup.php
  src/CoreShop/Component/Order/Model/AbstractProposal.php
  src/CoreShop/Component/Order/Model/AdjustableTrait.php
  src/CoreShop/Component/Order/Model/Adjustment.php
  src/CoreShop/Component/Order/Model/BaseAdjustableTrait.php
  src/CoreShop/Component/Order/Model/Cart.php
  src/CoreShop/Component/Order/Model/CartItem.php
  src/CoreShop/Component/Order/Model/Order.php
  src/CoreShop/Component/Order/Model/OrderInvoice.php
  src/CoreShop/Component/Order/Model/OrderInvoiceItem.php
  src/CoreShop/Component/Order/Model/OrderShipment.php
  src/CoreShop/Component/Order/Model/OrderShipmentItem.php
  src/CoreShop/Component/Order/Model/ProposalCartPriceRuleItem.php
  src/CoreShop/Component/Order/Model/ProposalPriceRuleTrait.php
  src/CoreShop/Component/Order/Model/Quote.php
  src/CoreShop/Component/Order/Model/Sale.php
  src/CoreShop/Component/Order/Model/SaleItem.php
  src/CoreShop/Component/Product/Model/Category.php
  src/CoreShop/Component/Product/Model/Manufacturer.php
  src/CoreShop/Component/Product/Model/Product.php
  src/CoreShop/Component/Resource/Exception/ImplementedByPimcoreException.php
  src/CoreShop/Component/Taxation/Model/TaxItem.php
Labels: bug
