Repository coreshop/CoreShop, pull requests merged in 2019-04, with the labels that each got.

#909 Address Type Identifier
  src/CoreShop/Bundle/AddressBundle/CoreExtension/AddressIdentifier.php
  src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/AddressBundle/Form/Type/AddressIdentifierChoiceType.php
  src/CoreShop/Bundle/AddressBundle/Form/Type/AddressIdentifierType.php
  src/CoreShop/Bundle/AddressBundle/Form/Type/AddressType.php
  src/CoreShop/Bundle/AddressBundle/Resources/config/doctrine/model/AddressIdentifier.orm.yml
  src/CoreShop/Bundle/AddressBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/AddressBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/AddressBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/AddressBundle/Resources/config/serializer/Model.AddressIdentifier.yml
  src/CoreShop/Bundle/AddressBundle/Resources/config/services.yml
  src/CoreShop/Bundle/AddressBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/AddressBundle/Resources/config/validation/Address.yml
  src/CoreShop/Bundle/AddressBundle/Resources/install/pimcore/classes/CoreShopAddress.json
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/css/address.css
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/img/address_identifier.svg
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/coreExtension/data/coreShopAddressIdentifier.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopAddressIdentifier.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/AddressBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/AddressBundle/Validator/Constraints/ValidAddressIdentifier.php
  src/CoreShop/Bundle/AddressBundle/Validator/Constraints/ValidAddressIdentifierValidator.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/AddressIdentifierFixture.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/AddressChoiceType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190329100025.php
  src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/public/static/js/shop.js
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/address.html.twig
  src/CoreShop/Component/Address/Model/Address.php
  src/CoreShop/Component/Address/Model/AddressIdentifier.php
  src/CoreShop/Component/Address/Model/AddressIdentifierInterface.php
  src/CoreShop/Component/Address/Model/AddressInterface.php
Labels: new feature

#912 [ProductBundle] re-add active to list serializer group
  src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.AbstractPriceRule.yml
Labels: bug

#913 [AddressBundle] AddressIdentifier Follow-up
  src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/AddressBundle/Doctrine/ORM/AddressIdentifierRepository.php
  src/CoreShop/Bundle/AddressBundle/Form/Type/AddressType.php
  src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
  src/CoreShop/Component/Address/Repository/AddressIdentifierRepositoryInterface.php
Labels: bug

#916 [CoreBundle] serialize relational values (product and store) as relation
  src/CoreShop/Bundle/CoreBundle/Resources/config/serializer/Model.ProductStoreValues.yml
Labels: bug

#923 Revert "[Core] don't overwrite interfaces"
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_customer.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_order.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_product.yml
Labels: bug

#914 [Pimcore] make CoreShop 2.0 compatible with Pimcore 5.7.2
  .travis.yml
  composer.json
  phpstan.neon
  src/CoreShop/Bundle/CoreBundle/composer.json
  src/CoreShop/Bundle/ProductBundle/composer.json
  src/CoreShop/Component/Pimcore/BCLayer/LazyLoadedFields.php
Labels: bug

#919 Ignore Toolbar Route
  src/CoreShop/Bundle/CoreBundle/EventListener/RequestCartAvailability.php
  src/CoreShop/Bundle/CoreBundle/EventListener/RequestCartRecalculation.php
  src/CoreShop/Bundle/OrderBundle/EventListener/SessionCartSubscriber.php
Labels: enhancement

#918 Clone AdditionalData Line By Line
  src/CoreShop/Component/Core/Order/Transformer/CartToSaleTransformer.php
Labels: bug

#917 Fixed not passing full configuration for Store based Mail.
  src/CoreShop/Component/Core/Notification/Rule/Action/Order/StoreMailActionProcessor.php
Labels: bug

#915 [Pimcore] make CoreShop 2.1 compatible with Pimcore 5.7.2
  .travis.yml
  src/CoreShop/Behat/Context/Domain/IndexContext.php
  src/CoreShop/Behat/Context/Hook/PimcoreDaoContext.php
  src/CoreShop/Behat/Resources/config/services/contexts/hook.yml
  src/CoreShop/Bundle/AddressBundle/composer.json
  src/CoreShop/Bundle/ConfigurationBundle/composer.json
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Bundle/CoreBundle/composer.json
  src/CoreShop/Bundle/CurrencyBundle/composer.json
  src/CoreShop/Bundle/CustomerBundle/composer.json
  src/CoreShop/Bundle/IndexBundle/composer.json
  src/CoreShop/Bundle/MoneyBundle/composer.json
  src/CoreShop/Bundle/NotificationBundle/composer.json
  src/CoreShop/Bundle/OrderBundle/composer.json
  src/CoreShop/Bundle/PaymentBundle/composer.json
  src/CoreShop/Bundle/PayumBundle/composer.json
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
  src/CoreShop/Bundle/ProductBundle/composer.json
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/composer.json
  src/CoreShop/Bundle/ResourceBundle/composer.json
  src/CoreShop/Bundle/StoreBundle/composer.json
  src/CoreShop/Bundle/ThemeBundle/composer.json
  src/CoreShop/Bundle/TrackingBundle/composer.json
  src/CoreShop/Bundle/WorkflowBundle/composer.json
  src/CoreShop/Component/Locale/composer.json
  src/CoreShop/Component/Pimcore/composer.json
  src/CoreShop/Component/Resource/composer.json
Labels: bug

#925 only return single address identifier in repository
  src/CoreShop/Bundle/AddressBundle/Doctrine/ORM/AddressIdentifierRepository.php
Labels: bug

#932 [Release] prepare 2.0.6 release
  CHANGELOG-2.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#939 [AddressBundle] use isoCode fallback if there is no language translation
  src/CoreShop/Bundle/AddressBundle/Resources/config/serializer/Model.Country.yml
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/country/panel.js
Labels: bug

#943 [Translations] allow some translations to be null
  src/CoreShop/Bundle/AddressBundle/Resources/config/doctrine/model/CountryTranslation.orm.yml
  src/CoreShop/Bundle/AddressBundle/Resources/config/doctrine/model/StateTranslation.orm.yml
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190410183520.php
  src/CoreShop/Bundle/TaxationBundle/Resources/config/doctrine/model/TaxRateTranslation.orm.yml
Labels: bug

#944 [AddressBundle] follow-up on #939
  src/CoreShop/Bundle/AddressBundle/Resources/config/serializer/Model.Country.yml
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/country/panel.js
Labels: bug

#911 Product Unit fixtures
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/AbstractProductFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductUnitFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductWithUnitFixture.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinition.orm.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinitionPrice.orm.yml
Labels: bug, enhancement

#921 [CoreBundle] don't persist the cart on user-login event
  src/CoreShop/Bundle/CoreBundle/EventListener/CartBlamerListener.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
Labels: bug

#946 [Product] introduce stop propagation flag for price-rules
  features/product/price_rules/stop_propagation.feature
  src/CoreShop/Behat/Context/Setup/ProductPriceRuleContext.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190412074654.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/ProductPriceRuleType.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/ProductSpecificPriceRuleType.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductPriceRule.orm.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductSpecificPriceRule.orm.yml
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/item.js
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/specificprice/object/item.js
  src/CoreShop/Bundle/ProductBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/ProductBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Product/Model/AbstractPriceRule.php
  src/CoreShop/Component/Product/Model/PriceRuleInterface.php
  src/CoreShop/Component/Product/Rule/Calculator/ProductPriceRuleCalculator.php
Labels: enhancement, new feature

#950 check store values availability
  src/CoreShop/Component/Core/Product/Calculator/StoreProductUnitDefinitionPriceCalculator.php
Labels: bug

#951 add missing interface definitions
  src/CoreShop/Component/Core/Model/Product.php
  src/CoreShop/Component/Core/Model/QuantityRangeInterface.php
  src/CoreShop/Component/ProductQuantityPriceRules/Model/QuantityRangePriceAwareInterface.php
Labels: bug

#953 [Product][#952] allow price rule labels to be null and fix error with two trait constructors
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190418150640.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductPriceRuleTranslation.orm.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductSpecificPriceRuleTranslation.orm.yml
  src/CoreShop/Component/Product/Model/AbstractPriceRule.php
  src/CoreShop/Component/Resource/Model/TranslatableTrait.php
  src/CoreShop/Component/Rule/Model/RuleTrait.php
Labels: bug

#954 allow one-step ranges
  src/CoreShop/Bundle/CoreBundle/Form/Extension/ProductQuantityRangeCollectionTypeExtension.php
  src/CoreShop/Component/Core/ProductQuantityPriceRules/Calculator/UnitVolumeCalculator.php
  src/CoreShop/Component/ProductQuantityPriceRules/Calculator/VolumeCalculator.php
Labels: enhancement

#955 [Serializer] Update JMS Serializer Bundle to 2.0
  composer.json
  src/CoreShop/Bundle/CoreBundle/Controller/PortletsController.php
  src/CoreShop/Bundle/ResourceBundle/composer.json
  src/CoreShop/Bundle/RuleBundle/Resources/config/pimcore/config.yml
Labels: enhancement

#957 [WholesaleCalculator] introduce purchasable wholesale calculator
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190425105238.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190425111940.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderItem.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuoteItem.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopMoneyCurrency.js
  src/CoreShop/Bundle/OrderBundle/CoreShopOrderBundle.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Compiler/PurchasableWholesalePriceCalculatorsPass.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/purchasable.yml
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuoteItem.json
  src/CoreShop/Component/Core/Model/Product.php
  src/CoreShop/Component/Core/Order/Processor/CartItemsWholesaleProcessor.php
  src/CoreShop/Component/Order/Calculator/CompositePurchasableWholesalePriceCalculator.php
  src/CoreShop/Component/Order/Calculator/PurchasableWholesalePriceCalculator.php
  src/CoreShop/Component/Order/Calculator/PurchasableWholesalePriceCalculatorInterface.php
  src/CoreShop/Component/Order/Exception/NoPurchasableWholesalePriceFoundException.php
  src/CoreShop/Component/Order/Model/PurchasableInterface.php
  src/CoreShop/Component/Order/Model/SaleItemInterface.php
  src/CoreShop/Component/Order/Transformer/AbstractCartItemToSaleItemTransformer.php
Labels: new feature

#956 [CurrencyBundle] fix money-currency extension
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopMoneyCurrency.js
Labels: bug

#958 [Currency] validation fixes for MoneyCurrency
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
  src/CoreShop/Component/Currency/Model/Money.php
Labels: bug

#959 [Core] strip_tags for meta description in category
  src/CoreShop/Component/Core/Model/Category.php
Labels: bug
