Repository coreshop/CoreShop, pull requests merged in 2019-01, with the labels that each got.

#758 [IndexBundle] implement optional inclusion into ProcessManager
  composer.json
  phpstan.neon
  src/CoreShop/Bundle/IndexBundle/Command/IndexCommand.php
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/CoreShopIndexExtension.php
  src/CoreShop/Bundle/IndexBundle/ProcessManager/Form/Type/CoreShopIndexProcessType.php
  src/CoreShop/Bundle/IndexBundle/ProcessManager/IndexListener.php
  src/CoreShop/Bundle/IndexBundle/ProcessManager/IndexProcess.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/commands.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/process_manager.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/css/index.css
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/IndexBundle/composer.json
Labels: enhancement, new feature

#765 [CoreBundle] add js event for menu-ready (to append more menu entries)
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
Labels: enhancement

#766 [ResourceBundle] add JMS Serializer Handler for Pimcore Objects
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/Serialization/PimcoreObjectHandler.php
Labels: enhancement

#767 [Core] fix bugs in Tracking Extractors
  src/CoreShop/Component/Core/Tracking/Extractor/OrderItemExtractor.php
  src/CoreShop/Component/Core/Tracking/Extractor/ProductExtractor.php
Labels: bug

#768 [Release] 2.0.2
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#772 [OrderBundle] add event to prepare sale in order to better extend details
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
Labels: enhancement

#771 [OrderBundle, Pimcore] extract DataLoader from Controller to be used oustide
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleController.php
  src/CoreShop/Component/Pimcore/DataObject/DataLoader.php
  src/CoreShop/Component/Pimcore/DataObject/DataLoaderInterface.php
Labels: enhancement

#770 [Core, Order] also apply discounts to cart-items in order to have the…
  src/CoreShop/Component/Core/Cart/Rule/Applier/DiscountApplier.php
  src/CoreShop/Component/Core/Order/Processor/CartAdjustmentClearer.php
  src/CoreShop/Component/Order/Model/AdjustableInterface.php
  src/CoreShop/Component/Order/Model/AdjustableTrait.php
  src/CoreShop/Component/Order/Model/BaseAdjustableInterface.php
  src/CoreShop/Component/Order/Model/BaseAdjustableTrait.php
Labels: enhancement

#773 [WorkflowBundle, OrderBundle] always load all available coreshop states into js
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/WorkflowBundle/DependencyInjection/CoreShopWorkflowExtension.php
Labels: enhancement

#775 [Order] make accessor protected for OrderDocument Processor
  src/CoreShop/Component/Order/Processable/ProcessableOrderItems.php
Labels: enhancement

#784 Cart item processor extract
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php
  src/CoreShop/Component/Order/Processor/CartItemProcessorInterface.php
Labels: enhancement

#786 [CoreBundle] fix wkhtml invoice settings
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/settings.js
Labels: bug
