Repository coreshop/CoreShop, pull requests merged in 2019-03, with the labels that each got.

#848 [Order] introduce options for order-document-items
  src/CoreShop/Component/Order/Transformer/OrderDocumentItemTransformerInterface.php
  src/CoreShop/Component/Order/Transformer/OrderItemToInvoiceItemTransformer.php
  src/CoreShop/Component/Order/Transformer/OrderItemToShipmentItemTransformer.php
  src/CoreShop/Component/Order/Transformer/OrderToInvoiceTransformer.php
  src/CoreShop/Component/Order/Transformer/OrderToShipmentTransformer.php
Labels: enhancement

#835 [WorkflowBundle] refactor state change logging
  CHANGELOG-2.0.x.md
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190225140315.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/OrderBundle/Pimcore/GridColumnConfig/Operator/Factory/OrderStateFactory.php
  src/CoreShop/Bundle/OrderBundle/Pimcore/GridColumnConfig/Operator/OrderState.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/grid_config.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/workflow.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/OrderBundle/Templating/Helper/OrderStateHelper.php
  src/CoreShop/Bundle/OrderBundle/Workflow/OrderHistoryLogger.php
  src/CoreShop/Bundle/OrderBundle/Workflow/OrderStateHistoryLogger.php
  src/CoreShop/Bundle/OrderBundle/Workflow/WorkflowStateManager.php
  src/CoreShop/Bundle/WorkflowBundle/History/HistoryLogger.php
  src/CoreShop/Bundle/WorkflowBundle/History/HistoryLoggerInterface.php
  src/CoreShop/Bundle/WorkflowBundle/History/HistoryRepository.php
  src/CoreShop/Bundle/WorkflowBundle/History/HistoryRepositoryInterface.php
  src/CoreShop/Bundle/WorkflowBundle/History/StateHistoryLogger.php
  src/CoreShop/Bundle/WorkflowBundle/History/StateHistoryLoggerInterface.php
  src/CoreShop/Bundle/WorkflowBundle/Notes.php
  src/CoreShop/Bundle/WorkflowBundle/Resources/config/services/workflow.yml
  src/CoreShop/Bundle/WorkflowBundle/Resources/config/translations/admin.de.yml
  src/CoreShop/Bundle/WorkflowBundle/Resources/config/translations/admin.en.yml
  src/CoreShop/Bundle/WorkflowBundle/StateManager/WorkflowStateInfoManager.php
  src/CoreShop/Bundle/WorkflowBundle/StateManager/WorkflowStateInfoManagerInterface.php
Labels: enhancement

#852 [OrderBundle, CoreBundle] revise create-shipment/create-invoice form in extjs
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/order/shipment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/shipment.js
Labels: enhancement

#853 [OrderBundle] remove usage of deprecated order-state-history service
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_invoice.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_order.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_payment.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_shipment.yml
Labels: enhancement

#855 Permissions
  src/CoreShop/Bundle/AddressBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/AddressBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/ProductBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/ProductBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/StoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/StoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/TaxationBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/TaxationBundle/Resources/translations/admin.en.yml
Labels: enhancement

#856 [Index] introduce advanced sorting
  features/filter/order/simple_order.feature
  src/CoreShop/Behat/Context/Domain/FilterContext.php
  src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterOrderRendererTypesPass.php
  src/CoreShop/Bundle/IndexBundle/Order/Mysql/AbstractMysqlDynamicRenderer.php
  src/CoreShop/Bundle/IndexBundle/Order/Mysql/SimpleOrderRenderer.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/order_renderer.yml
  src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
  src/CoreShop/Component/Index/Listing/OrderAwareListingInterface.php
  src/CoreShop/Component/Index/Order/DynamicOrderRendererInterface.php
  src/CoreShop/Component/Index/Order/OrderInterface.php
  src/CoreShop/Component/Index/Order/OrderRenderer.php
  src/CoreShop/Component/Index/Order/OrderRendererInterface.php
  src/CoreShop/Component/Index/Order/SimpleOrder.php
Labels: enhancement, new feature

#859 [Frontend] remove unused property in detail template
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/detail.html.twig
Labels: bug

#858 [Checkout] validate cart before submitting the order
  src/CoreShop/Bundle/CoreBundle/Checkout/Step/SummaryCheckoutStep.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/checkout.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary.html.twig
Labels: bug

#862 [All] remove PHP5 quick fix for sorts
  src/CoreShop/Bundle/AddressBundle/Form/Type/CountryChoiceType.php
  src/CoreShop/Bundle/AddressBundle/Form/Type/StateChoiceType.php
  src/CoreShop/Bundle/AddressBundle/Form/Type/ZoneChoiceType.php
  src/CoreShop/Bundle/CurrencyBundle/Form/Type/CurrencyChoiceType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/IndexChoiceType.php
  src/CoreShop/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/CarrierChoiceType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/ShippingRuleChoiceType.php
  src/CoreShop/Bundle/StoreBundle/Form/Type/StoreChoiceType.php
  src/CoreShop/Bundle/TaxationBundle/Form/Type/TaxRateChoiceType.php
  src/CoreShop/Bundle/TaxationBundle/Form/Type/TaxRuleGroupChoiceType.php
Labels: enhancement

#863 [Core] if cart has no shippables, don't force carriage calculation
  src/CoreShop/Component/Core/Order/Processor/CartShippingProcessor.php
Labels: bug

#864 Refactor add to cart
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/AddToCartAvailabilityValidator.php
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/_addToCart.html.twig
  src/CoreShop/Bundle/OrderBundle/DTO/AddToCart.php
  src/CoreShop/Bundle/OrderBundle/DTO/AddToCartInterface.php
  src/CoreShop/Bundle/OrderBundle/Factory/AddToCartFactory.php
  src/CoreShop/Bundle/OrderBundle/Factory/AddToCartFactoryInterface.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/AddToCartType.php
  src/CoreShop/Component/Order/Cart/CartModifier.php
  src/CoreShop/Component/Order/Factory/CartItemFactory.php
  src/CoreShop/Component/Order/Factory/CartItemFactoryInterface.php
  src/CoreShop/Component/StorageList/SimpleStorageListModifier.php
  src/CoreShop/Component/StorageList/StorageListModifierInterface.php
Labels: BC break, enhancement

#866 Refactor how we identify CartItem - Product
  CHANGELOG-2.1.x.md
  docs/02_Components/StorageList_Component.md
  src/CoreShop/Behat/Context/Domain/CartContext.php
  src/CoreShop/Behat/Context/Setup/CartContext.php
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/AddToCartAvailabilityValidator.php
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/config/services/wishlist.yml
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleCreationController.php
  src/CoreShop/Component/Order/Cart/CartModifier.php
  src/CoreShop/Component/Order/Model/Cart.php
  src/CoreShop/Component/Order/Model/CartItem.php
  src/CoreShop/Component/Order/Model/Sale.php
  src/CoreShop/Component/Order/Model/SaleInterface.php
  src/CoreShop/Component/StorageList/Model/StorageList.php
  src/CoreShop/Component/StorageList/Model/StorageListInterface.php
  src/CoreShop/Component/StorageList/Model/StorageListItem.php
  src/CoreShop/Component/StorageList/Model/StorageListItemInterface.php
  src/CoreShop/Component/StorageList/Model/StorageListProductInterface.php
  src/CoreShop/Component/StorageList/SessionStorageListModifier.php
  src/CoreShop/Component/StorageList/SimpleStorageListModifier.php
  src/CoreShop/Component/StorageList/StorageListModifierInterface.php
  tests/lib/CoreShop/Test/Data.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/Cart.php
  tests/lib/CoreShop/Test/PHPUnit/Suites/StorageList.php
Labels: BC break

#869 [All] fixes for Pimcore 5.7
  .travis.yml
  phpstan.neon
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Bundle/ResourceBundle/Installer/SqlInstaller.php
  src/CoreShop/Component/Pimcore/BCLayer/GridHelperService.php
  src/CoreShop/Component/Pimcore/BCLayer/LazyLoadedFields.php
  src/CoreShop/Component/Pimcore/DataObject/Migrate.php
Labels: bug

#872 [Behat] the cart tests haven't been ran since the theme-bundle was introduced
  src/CoreShop/Behat/Resources/config/suites/domain/theme.yml
Labels: bug

#873 [Release] 2.0.5
  CHANGELOG-2.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#854 [MenuBundle] introduce menu-bundle to define the menu-structure in php
  bin/subtree-release
  bin/subtree-split
  composer.json
  docs/02_Bundles/Menu_Bundle.md
  features/menu/menu.feature
  src/CoreShop/Behat/Context/Domain/MenuContext.php
  src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
  src/CoreShop/Behat/Resources/config/suites.yml
  src/CoreShop/Behat/Resources/config/suites/domain/menu.yml
  src/CoreShop/Bundle/CoreBundle/CoreShopCoreBundle.php
  src/CoreShop/Bundle/CoreBundle/Menu/MainMenuBuilder.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/menu.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/css/core.css
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/CoreBundle/composer.json
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/CoreShopIndexExtension.php
  src/CoreShop/Bundle/IndexBundle/Menu/IndexMenuBuilder.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/menu.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/MenuBundle/Builder.php
  src/CoreShop/Bundle/MenuBundle/Builder/MenuBuilderInterface.php
  src/CoreShop/Bundle/MenuBundle/Controller/MenuController.php
  src/CoreShop/Bundle/MenuBundle/CoreShopMenuBundle.php
  src/CoreShop/Bundle/MenuBundle/DependencyInjection/CompilerPass/MenuBuilderPass.php
  src/CoreShop/Bundle/MenuBundle/DependencyInjection/CoreShopMenuExtension.php
  src/CoreShop/Bundle/MenuBundle/Guard/PimcoreGuard.php
  src/CoreShop/Bundle/MenuBundle/LICENSE.md
  src/CoreShop/Bundle/MenuBundle/README.md
  src/CoreShop/Bundle/MenuBundle/Renderer/JsonRenderer.php
  src/CoreShop/Bundle/MenuBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/MenuBundle/Resources/config/services.yml
  src/CoreShop/Bundle/MenuBundle/Resources/views/knp_menu.js.twig
  src/CoreShop/Bundle/MenuBundle/Resources/views/menu.js.twig
  src/CoreShop/Bundle/MenuBundle/composer.json
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/helper.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource.js
Labels: enhancement

#876 don't load menu via compiled resources -> load it direct
  src/CoreShop/Bundle/CoreBundle/CoreShopCoreBundle.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/admin.yml
Labels: bug

#877 [SaleUnit] introduce a more easier function to get store-values
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Component/Core/Model/Product.php
  src/CoreShop/Component/Core/Model/ProductInterface.php
Labels: enhancement

#878 [MenuBundle] introduce sorting of menu entries
  src/CoreShop/Bundle/CoreBundle/Menu/MainMenuBuilder.php
  src/CoreShop/Bundle/MenuBundle/Renderer/JsonRenderer.php
Labels: enhancement

#880 [MenuBundle] fix product price rules menu entry
  src/CoreShop/Bundle/CoreBundle/Menu/MainMenuBuilder.php
Labels: bug

#892 Use Price Calculator Interface in ProductExtractor
  src/CoreShop/Component/Core/Tracking/Extractor/ProductExtractor.php
Labels: bug

#890 dont use private method in product controller
  src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php
Labels: enhancement

#886 [CoreBundle] fix notification rule settings for order mail action
  src/CoreShop/Bundle/CoreBundle/Form/Type/Notification/Action/OrderMailConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Notification/Action/StoreMailConfigurationType.php
Labels: bug

#883 remove usage of store-price in favour of new storeValues
  src/CoreShop/Component/Core/Product/Calculator/StoreProductPriceCalculator.php
Labels: enhancement

#732 Disable Customer Deletion if bounded Orders are available
  features/order/customer_deletion.feature
  src/CoreShop/Behat/Context/Domain/CustomerContext.php
  src/CoreShop/Behat/Resources/config/suites/domain/order.yml
  src/CoreShop/Bundle/CoreBundle/EventListener/CustomerOrderDeletionListener.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
  src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php
  src/CoreShop/Component/Order/Repository/OrderRepositoryInterface.php
Labels: bug, enhancement

#894 [CoreBundle] fix cart-stock validation
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/CartStockAvailabilityValidator.php
  src/CoreShop/Component/Core/Order/Modifier/CartItemQuantityModifier.php
Labels: bug

#897 Check Unit Definition Layout Availability Before Processing
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductUnitDefinitions.js
Labels: enhancement

#896 Make StoreValues Extension Inheritable
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopStoreValues.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/storevalues/items/price.js
Labels: enhancement

#898 [ProductQuantityPriceRules] make calculation behaviour required
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Form/Type/ProductQuantityPriceRuleType.php
Labels: bug

#901 Fix NotificationRule Model Namespace Typo
  src/CoreShop/Bundle/NotificationBundle/Resources/config/serializer/Model.NotificationRule.yml
Labels: bug

#899 [Core] don't overwrite interfaces
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_customer.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_order.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_product.yml
Labels: bug

#900 Implement UnitIdentifier for Order and Sale Item
  src/CoreShop/Bundle/CoreBundle/Controller/OrderController.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190226122625.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190315140631.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190325142544.php
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderItem.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuoteItem.json
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnit.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/data/coreShopProductUnit.js
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductUnit.js
  src/CoreShop/Bundle/ProductBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Core/Model/SaleItemInterface.php
  src/CoreShop/Component/Core/Model/SaleItemTrait.php
  src/CoreShop/Component/Core/Order/Transformer/CartItemToSaleItemTransformer.php
Labels: enhancement

#902 [CoreBundle] fix bug in assigning store-values
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
Labels: bug

#906 [Adjustments] fix typo in OrderItem and QuoteItem
  CHANGELOG-2.0.x.md
  features/order/create_order_with_discount.feature
  src/CoreShop/Behat/Resources/config/suites/domain/order.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderItem.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuoteItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuoteItem.json
Labels: bug

#907 [StorageList] StorageList are not Pimcore Objects per se
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Wishlist/summary.html.twig
  src/CoreShop/Component/StorageList/Model/StorageList.php
  src/CoreShop/Component/StorageList/Model/StorageListInterface.php
  src/CoreShop/Component/StorageList/Model/StorageListItem.php
  src/CoreShop/Component/StorageList/Model/StorageListItemInterface.php
Labels: bug

#910 Address Redirect Fix
  src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
Labels: bug

#908 fix layout crash if price rule is inactive
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/specificprice/object/item.js
Labels: bug
