Repository coreshop/CoreShop, pull requests merged in 2019-05, with the labels that each got.

#961 [CoreBundle] remove result cache for store price -> it causes issues with inheritance
  src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/ProductStorePriceRepository.php
Labels: bug

#962 [CoreBundle] add index to StorePrice Entity for better performance
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190430134834.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/ProductStorePrice.orm.yml
Labels: enhancement

#964 [CurrencyBundle] MoneyCurrency Type: Don't check validity when empty and not mandatory.
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
Labels: bug

#965 [IndexBundle] improve standalone usage
  src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/CoreShopIndexExtension.php
  src/CoreShop/Bundle/IndexBundle/Installer.php
  src/CoreShop/Bundle/IndexBundle/Menu/IndexMenuBuilder.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/installer.yml
  src/CoreShop/Bundle/IndexBundle/composer.json
Labels: enhancement

#967 [Migration] only add indices to store_price table if table actually e…
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190430134834.php
Labels: enhancement

#972 [Taxation] fix tax collection on gross values
  features/cart/cart_taxation_gross_rounding.feature
  src/CoreShop/Component/Core/Cart/Rule/Applier/DiscountApplier.php
  src/CoreShop/Component/Core/Order/Processor/CartItemTaxProcessor.php
  src/CoreShop/Component/Taxation/Collector/TaxCollector.php
  src/CoreShop/Component/Taxation/Collector/TaxCollectorInterface.php
Labels: bug

#974 [Taxation] fix tax collection on gross values - 2.1
  features/cart/cart_taxation_gross_rounding.feature
  src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php
  src/CoreShop/Component/Core/Order/Processor/CartItemTaxProcessor.php
  src/CoreShop/Component/Taxation/Collector/TaxCollector.php
  src/CoreShop/Component/Taxation/Collector/TaxCollectorInterface.php
Labels: bug

#975 [Release] prepare 2.0.7
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#976 [All] move translations into the right bundle
  src/CoreShop/Bundle/AddressBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/AddressBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.sv.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/translations/admin.sv.yml
Labels: bug

#977 [Pimcore] make coreshop compatible with Pimcore 5.8
  src/CoreShop/Bundle/CoreBundle/Form/Type/AddressChoiceType.php
Labels: bug

#980 [CoreBundle] persist customer on login if the cart has an id
  src/CoreShop/Bundle/CoreBundle/EventListener/CartBlamerListener.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
Labels: bug

#984 [ResourceBundle] don't serialize Carbon
  src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/serializer/Carbon.yml
Labels: bug

#982 [CoreBundle] introduce store-preview for products
  src/CoreShop/Bundle/CoreBundle/Controller/ProductPreviewController.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/settings.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/preview.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
Labels: new feature

#983 [Release] prepare 2.0.8
  CHANGELOG-2.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#973 [All] require min Pimcore 5.8 and PHP 7.2
  .travis.yml
  composer.json
  src/CoreShop/Bundle/AddressBundle/composer.json
  src/CoreShop/Bundle/ConfigurationBundle/composer.json
  src/CoreShop/Bundle/CoreBundle/composer.json
  src/CoreShop/Bundle/CurrencyBundle/composer.json
  src/CoreShop/Bundle/CustomerBundle/composer.json
  src/CoreShop/Bundle/FixtureBundle/composer.json
  src/CoreShop/Bundle/FrontendBundle/composer.json
  src/CoreShop/Bundle/IndexBundle/composer.json
  src/CoreShop/Bundle/InventoryBundle/composer.json
  src/CoreShop/Bundle/LocaleBundle/composer.json
  src/CoreShop/Bundle/MenuBundle/composer.json
  src/CoreShop/Bundle/MoneyBundle/composer.json
  src/CoreShop/Bundle/NotificationBundle/composer.json
  src/CoreShop/Bundle/OrderBundle/composer.json
  src/CoreShop/Bundle/PaymentBundle/composer.json
  src/CoreShop/Bundle/PayumBundle/composer.json
  src/CoreShop/Bundle/PimcoreBundle/composer.json
  src/CoreShop/Bundle/ProductBundle/composer.json
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/composer.json
  src/CoreShop/Bundle/ResourceBundle/composer.json
  src/CoreShop/Bundle/RuleBundle/composer.json
  src/CoreShop/Bundle/SEOBundle/composer.json
  src/CoreShop/Bundle/SequenceBundle/composer.json
  src/CoreShop/Bundle/ShippingBundle/composer.json
  src/CoreShop/Bundle/StoreBundle/composer.json
  src/CoreShop/Bundle/TaxationBundle/composer.json
  src/CoreShop/Bundle/ThemeBundle/composer.json
  src/CoreShop/Bundle/TrackingBundle/composer.json
  src/CoreShop/Bundle/WorkflowBundle/composer.json
  src/CoreShop/Component/Address/composer.json
  src/CoreShop/Component/Configuration/composer.json
  src/CoreShop/Component/Core/composer.json
  src/CoreShop/Component/Currency/composer.json
  src/CoreShop/Component/Customer/composer.json
  src/CoreShop/Component/Index/composer.json
  src/CoreShop/Component/Inventory/composer.json
  src/CoreShop/Component/Locale/composer.json
  src/CoreShop/Component/Notification/composer.json
  src/CoreShop/Component/Order/composer.json
  src/CoreShop/Component/Payment/composer.json
  src/CoreShop/Component/Pimcore/composer.json
  src/CoreShop/Component/Product/composer.json
  src/CoreShop/Component/ProductQuantityPriceRules/composer.json
  src/CoreShop/Component/Registry/composer.json
  src/CoreShop/Component/Resource/composer.json
  src/CoreShop/Component/Rule/composer.json
  src/CoreShop/Component/SEO/composer.json
  src/CoreShop/Component/Sequence/composer.json
  src/CoreShop/Component/Shipping/composer.json
  src/CoreShop/Component/StorageList/composer.json
  src/CoreShop/Component/Store/composer.json
  src/CoreShop/Component/Taxation/composer.json
  src/CoreShop/Component/Tracking/composer.json
Labels: enhancement

#986 [Maintenance] refactor to use new maintenance task from pimcore 5.8
  src/CoreShop/Bundle/CoreBundle/Maintenance/ProposalExpireTask.php
  src/CoreShop/Bundle/CoreBundle/Maintenance/RuleAvailabilityTask.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
Labels: enhancement

#990 use default unit quanity in onhold inventory
  src/CoreShop/Component/Core/Inventory/Operator/OrderInventoryOperator.php
Labels: bug

#993 [ProductBundle, CoreBundle] set itemQuantityFactor min value to null
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopProduct.json
Labels: bug

#995 [ResourceBundle] remove create-object-class command
  src/CoreShop/Bundle/ResourceBundle/Command/CreateObjectClassCommand.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services/commands.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/skeleton/model/Resource.php.twig
Labels: BC break, bug

#997 [FrontendBundle] fix wishlist remove and allow purchasables
  src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php
  src/CoreShop/Component/StorageList/Model/StorageListItem.php
Labels: bug

#1000 [ResourceBundle] add connection interface into Pimcore Repository
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackRepositoryPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Driver/Pimcore/PimcoreDriver.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/PimcoreRepository.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepository.php
Labels: enhancement

#1001 [Index, IndexBundle] allow options for the listing load function
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/IndexBundle/Worker/AbstractListing.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
  src/CoreShop/Component/Index/Listing/ListingInterface.php
Labels: BC break, enhancement

#1004 always load product unit definitions
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinitions.orm.yml
  src/CoreShop/Component/Product/Model/ProductUnitDefinitions.php
Labels: enhancement

#1006 show discount/surcharge label in order overview
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/helpers.js
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
Labels: bug, enhancement
