Repository coreshop/CoreShop, pull requests merged in 2019-07, with the labels that each got.

#1040 [PimcoreBundle] fix dynamic-dropdown for pimcore-6
  src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/dynamic_dropdown.yml
Labels: bug

#1025 [All] make CoreShop stores more async, don't load them initially
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/country.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/state.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/zone.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/cart/pricerules/conditions/carriers.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopStorePrice.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/invoice/invoiceState.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/order/carriers.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/payment/paymentState.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/shipment/shipmentState.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/order/shipment.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/settings.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/conditions/countries.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/conditions/currencies.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/conditions/zones.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/store/item.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/taxation/taxrulegroup/item.js
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/exchangeRate/panel.js
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/resource/currency.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/item.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/panel.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/iterator.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nested.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/item.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/objecttype/abstract.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/panel.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/payment.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/global.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/comboBox.js
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/carrier/item.js
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/shippingrule/actions/shippingRule.js
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/shippingrule/conditions/shippingRule.js
  src/CoreShop/Bundle/StoreBundle/Resources/public/pimcore/js/resource/store.js
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/resource/taxRate.js
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/resource/taxRuleGroup.js
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/taxrulegroup/item.js
Labels: enhancement

#1050 [CoreExtensions] don't allow any diff until properly implemented
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
  src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/SerializedData.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Multiselect.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php
Labels: bug

#1051 [CoreExtensions] don't allow any diff until properly implemented 2.1
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
  src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/SerializedData.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnit.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Multiselect.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php
Labels: bug

#1043 [Order] introduce checkout events
  src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
  src/CoreShop/Bundle/OrderBundle/EventListener/CheckoutCartLocaleAssignerListener.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/checkout_listener.yml
  src/CoreShop/Component/Order/CheckoutEvents.php
  src/CoreShop/Component/Order/Event/CheckoutEvent.php
Labels: bug, enhancement

#1045 [ProductBundle] specific price rules: keep id on save
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductSpecificPriceRules.js
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/specificprice/object/item.js
Labels: bug

#1053 fix total tax in tag manager tracker
  .travis.yml
  features/tracking/analytics_enhanced.feature
  features/tracking/global_site_tag.feature
  features/tracking/tag_manager_classic.feature
  features/tracking/tag_manager_enhanced.feature
  features/tracking/universal_ecommerce.feature
  src/CoreShop/Bundle/TrackingBundle/Tracker/Google/GlobalSiteTagEnhancedEcommerce.php
  src/CoreShop/Bundle/TrackingBundle/Tracker/Matomo/Matomo.php
  src/CoreShop/Component/Core/Tracking/Extractor/OrderExtractor.php
Labels: bug

#1054 [IndexBundle] fix iterator and nested interpreter
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/iterator.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nested.js
Labels: bug

#1058 Add Decimal Precision to Order Extractor
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/tracking.yml
  src/CoreShop/Component/Core/Tracking/Extractor/OrderExtractor.php
Labels: bug
