Repository coreshop/CoreShop, pull requests merged in 2019-06, with the labels that each got.

#1015 add more carrier price options
  src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/CarrierType.php
Labels: enhancement

#1017 Add group to ThumbnailInstaller
  src/CoreShop/Bundle/ResourceBundle/Installer/Configuration/ImageThumbnailConfiguration.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreImageThumbnailsInstaller.php
Labels: enhancement

#1019 [Product] remove getIsAvailableWhenOutOfStock and setIsAvailableWhenOutOfStock
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20171209154519.php
  src/CoreShop/Component/Product/Model/Product.php
Labels: bug

#1023 [CurrencyBundle] fix for money-currency editable when data comes from pimcore editmode
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
Labels: bug

#1028 [CoreBundle] fix inheritance for store-values
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
Labels: bug

#1030 Introduce configurable decimal precision and factor
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/AbstractProductFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductWithUnitFixture.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/tracking.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/dashboard/portlets/sales.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/helpers.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/storevalues/items/price.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/storevalues/items/unitPrice.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/productquantitypricerules/ranges.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/sales.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/actions/additionAmount.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/actions/price.js
  src/CoreShop/Bundle/CurrencyBundle/Controller/CurrencyController.php
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
  src/CoreShop/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CurrencyBundle/DependencyInjection/CoreShopCurrencyExtension.php
  src/CoreShop/Bundle/CurrencyBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
  src/CoreShop/Bundle/MoneyBundle/Form/Transformer/MoneyToIntegerTransformer.php
  src/CoreShop/Bundle/MoneyBundle/Form/Type/MoneyType.php
  src/CoreShop/Bundle/MoneyBundle/Formatter/MoneyFormatter.php
  src/CoreShop/Bundle/MoneyBundle/Resources/config/services.yml
  src/CoreShop/Bundle/MoneyBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/OrderBundle/Controller/OrderPaymentController.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/payment.yml
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/actions/discountAmount.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/actions/surchargeAmount.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/conditions/amount.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/payment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/editInvoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/editPayment.js
  src/CoreShop/Bundle/ProductBundle/Form/Type/Unit/ProductUnitDefinitionPriceType.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/services/units.yml
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/actions/discountAmount.js
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/actions/price.js
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/services/actions.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/shippingrule/conditions/amount.js
  src/CoreShop/Component/Core/Cart/Rule/Action/DiscountPercentActionProcessor.php
  src/CoreShop/Component/Core/Tracking/Extractor/OrderExtractor.php
  src/CoreShop/Component/Core/Tracking/Extractor/OrderItemExtractor.php
  src/CoreShop/Component/Core/Tracking/Extractor/ProductExtractor.php
  src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php
Labels: new feature

#1032 change db type for pricing fields to BIGINT
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190617082805.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/ProductStoreValues.orm.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/QuantityRange.orm.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinitionPrice.orm.yml
Labels: enhancement

#1038 [PimcoreBundle] use reflection to get class methods
  src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php
Labels: bug

#1039 Fix missing coreshop.helper namespace
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/helpers.js
Labels: bug
