Repository coreshop/CoreShop, pull requests merged in 2019-10, with the labels that each got.

#1119 [Tests] exit code
  etc/suites/application
  etc/suites/codestyle
  etc/suites/stan
Labels: bug

#1121 allow price range ordering
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/public/pimcore/js/productQuantityPriceRules/ranges.js
Labels: enhancement

#1122 [FQCN] makes aliases for resource installers public
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services/installer.yml
Labels: bug

#1126 [ResourceBundle, OrderBundle, CoreBundle] introduce more memory efficient
  src/CoreShop/Bundle/CoreBundle/Resources/config/serializer/Model.Cart.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/serializer/Model.CartItem.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/serializer/Model.Order.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/serializer/Model.OrderItem.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/serializer/Model.Quote.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/serializer/Model.QuoteItem.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/config/serializer/Model.Customer.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/config/serializer/Model.CustomerGroup.yml
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
  src/CoreShop/Bundle/OrderBundle/Controller/CartController.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/CoreShopOrderExtension.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.AbstractProposal.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.Adjustment.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.Cart.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.CartItem.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.Order.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.OrderItem.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.Quote.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.QuoteItem.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.Sale.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.SaleItem.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.Product.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/serializer/Model.AbstractModel.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/serializer/Model.DataObject.AbstractObject.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/serializer/Model.DataObject.Fieldcollection.Data.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/Serialization/CarbonHandler.php
  src/CoreShop/Bundle/ResourceBundle/Serialization/Driver/PimcoreDataObjectDriver.php
  src/CoreShop/Component/Order/Model/Cart.php
  src/CoreShop/Component/Order/Model/SaleItem.php
Labels: BC break, bug

#1128 remove decimal factor multiplier in order extractor
  src/CoreShop/Component/Core/Tracking/Extractor/OrderExtractor.php
Labels: bug

#1123 Move migration for Quantity Rule Range Unit to Sales Unit migration
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190226122625.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190528090625.php
Labels: bug

#1133 [2.0.10] prepare release
  CHANGELOG-2.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1138 [ThemeBundle] add missing dependency to pimcore-bundle
  src/CoreShop/Bundle/ThemeBundle/composer.json
Labels: bug

#1140 [ThemeBundle] use pimcore-bundle 2.1
  src/CoreShop/Bundle/ThemeBundle/composer.json
Labels: bug

#1142 [IndexBundle] use doctrine schema-config to create index-table schema
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
Labels: bug

#1141 [FrontendBundle] allow usage of auto-wired Frontend Controllers
  src/CoreShop/Bundle/FrontendBundle/CoreShopFrontendBundle.php
  src/CoreShop/Bundle/FrontendBundle/DependencyInjection/CompilerPass/RegisterFrontendControllerPass.php
  src/CoreShop/Bundle/FrontendBundle/DependencyInjection/CoreShopFrontendExtension.php
  src/CoreShop/Bundle/FrontendBundle/Resources/config/services.yml
Labels: bug

#1144 [OrderBundle] CartItem Quantity has to be > 0
  src/CoreShop/Bundle/OrderBundle/Form/Type/CartItemType.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/validation/CartItem.yml
Labels: bug

#1147 [2.1.0] prepare release
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE
