Repository coreshop/CoreShop, pull requests merged in 2020-06, with the labels that each got.

#1418 [CoreBundle] fix typo in query condition to fetch product variants
  src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/ProductRepository.php
Labels: bug

#1417 [FrontendBundle] add italian translations
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/documents.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
Labels: bug

#1416 [IndexBundle] fix range filter condition
  src/CoreShop/Component/Index/Filter/RangeFilterConditionProcessor.php
Labels: bug

#1415 [IndexBundle] fix saving of nested filters
  src/CoreShop/Bundle/IndexBundle/Resources/config/validation/FilterCondition.yml
Labels: bug

#1413 [Installer] fix output of thumbnail installer
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreImageThumbnailsInstaller.php
Labels: bug

#1412 [ProductBundle] fix quantity price rule condition
  features/product/price_rules/quantity_condition.feature
  src/CoreShop/Behat/Context/Setup/ProductPriceRuleContext.php
  src/CoreShop/Behat/Resources/config/suites/domain/product.yml
  src/CoreShop/Behat/Resources/config/suites/domain/recycle_bin.yml
  src/CoreShop/Behat/Resources/config/suites/domain/version.yml
  src/CoreShop/Component/Core/Product/Rule/Condition/QuantityConditionChecker.php
Labels: bug

#1407 [DoctrineBundle] fix deprecation notes
  composer.json
  src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/ResourceBundle/composer.json
Labels: enhancement

#1411 [All] remove usage of ItemKeyTransformer Service and use DataObject\Service directly
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/order_invoice.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/order_shipment.yml
  src/CoreShop/Component/Core/Order/Committer/OrderCommitter.php
  src/CoreShop/Component/Core/Order/Committer/QuoteCommitter.php
  src/CoreShop/Component/Order/Transformer/OrderToInvoiceTransformer.php
  src/CoreShop/Component/Order/Transformer/OrderToShipmentTransformer.php
Labels: enhancement

#1419 re-add id reset on entity clone
  src/CoreShop/Component/Product/Model/ProductUnitDefinitions.php
  src/CoreShop/Component/ProductQuantityPriceRules/Model/ProductQuantityPriceRule.php
  src/CoreShop/Component/ProductQuantityPriceRules/Model/QuantityRange.php
Labels: bug

#1422 [OrderBundle] Fix order expire command
  src/CoreShop/Bundle/OrderBundle/Command/OrderExpireCommand.php
Labels: bug

#1421 [OrderBundle][CoreBundle] Fix currency formatting in sale detail related components
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/order/detail/blocks/carriage.js
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractCartCreationController.php
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
  src/CoreShop/Bundle/OrderBundle/Controller/CartController.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/detail/blocks/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/invoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/payment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/editInvoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/shipment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/products.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/totals.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/header.js
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services.yml
Labels: bug, enhancement

#1424 [git] ignore tests and docs for relases
  .gitattributes
Labels: enhancement

#1423 [2.2.2] prepare release
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1430 [Fixtures] update fixtures version and fix Deprecation message
  composer.json
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/AddressIdentifierFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/ConfigurationFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CurrencyFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/NotificationRulesFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/StoreFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/ZoneFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/AbstractProductFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/CarrierFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/CategoryFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/PaymentProviderFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductUnitFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductWithUnitFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ShippingRuleFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ShippingRuleGroupFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/TaxRateFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/TaxRuleGroupFixture.php
  src/CoreShop/Bundle/FixtureBundle/Fixture/UpdateDataFixturesFixture.php
  src/CoreShop/Bundle/FixtureBundle/composer.json
Labels: enhancement

#1426 Fix typo in the docs
  docs/02_Bundles/Resource_Bundle/03_Installation.md
Labels: docs

#1433 [OrderBundle] Values should be zero, if amount should not be defined
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/AmountConfigurationType.php
Labels: bug

#1435 [Core] create default address if customer doesn't have one
  src/CoreShop/Component/Core/Customer/Address/AddressAssignmentManager.php
Labels: enhancement

#1434 [FrontendBundle] apply confirm and pay transition for orders with value of 0
  src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
Labels: bug

#1436 [OrderBundle] Add currency property
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.Sale.yml
Labels: bug, enhancement
