Repository coreshop/CoreShop, pull requests merged in 2020-03, with the labels that each got.

#1310 [Pimcore] Compatibility with Pimcore 6.5.3
  app/config/config_behat.yml
  composer.json
  src/CoreShop/Bundle/AddressBundle/composer.json
  src/CoreShop/Bundle/ConfigurationBundle/composer.json
  src/CoreShop/Bundle/CoreBundle/composer.json
  src/CoreShop/Bundle/CurrencyBundle/composer.json
  src/CoreShop/Bundle/CustomerBundle/composer.json
  src/CoreShop/Bundle/IndexBundle/composer.json
  src/CoreShop/Bundle/MenuBundle/composer.json
  src/CoreShop/Bundle/MoneyBundle/composer.json
  src/CoreShop/Bundle/NotificationBundle/composer.json
  src/CoreShop/Bundle/OrderBundle/composer.json
  src/CoreShop/Bundle/PaymentBundle/composer.json
  src/CoreShop/Bundle/PayumBundle/composer.json
  src/CoreShop/Bundle/ProductBundle/composer.json
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/composer.json
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDocumentsInstaller.php
  src/CoreShop/Bundle/ResourceBundle/composer.json
  src/CoreShop/Bundle/StoreBundle/composer.json
  src/CoreShop/Bundle/ThemeBundle/composer.json
  src/CoreShop/Bundle/TrackingBundle/composer.json
  src/CoreShop/Bundle/WorkflowBundle/composer.json
  src/CoreShop/Component/Locale/composer.json
  src/CoreShop/Component/Pimcore/composer.json
  src/CoreShop/Component/Resource/composer.json
Labels: bug

#1283 feature: calculate shipping tax using cart items
  features/cart/cart_shipping_tax_by_cart_items_gross.feature
  features/cart/cart_shipping_tax_by_cart_items_net.feature
  features/cart/cart_shipping_tax_rate_gross.feature
  features/cart/cart_shipping_tax_rate_net.feature
  src/CoreShop/Behat/Context/Setup/ShippingContext.php
  src/CoreShop/Behat/Context/Transform/CartContext.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200213132916.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Carrier.orm.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/shipping-taxation.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/shipping.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/store/item.js
  src/CoreShop/Bundle/ShippingBundle/Controller/CarrierController.php
  src/CoreShop/Bundle/ShippingBundle/CoreShopShippingBundle.php
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/Compiler/ShippingTaxCalculationStrategyPass.php
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/CoreShopShippingExtension.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/CarrierType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/ShippingTaxCalculationStrategyChoiceType.php
  src/CoreShop/Bundle/ShippingBundle/Resources/config/doctrine/model/Carrier.orm.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/serializer/Model.Carrier.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services/shipping-rules.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services/shipping-taxation.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/validation/Carrier.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/carrier/item.js
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/carrier/panel.js
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Core/Order/Processor/CartTaxProcessor.php
  src/CoreShop/Component/Core/Shipping/Calculator/TaxedCarrierPriceRuleCalculator.php
  src/CoreShop/Component/Core/Shipping/Calculator/TaxedShippingCalculatorInterface.php
  src/CoreShop/Component/Core/Shipping/Taxation/TaxCalculationStrategyCartItems.php
  src/CoreShop/Component/Core/Shipping/Taxation/TaxCalculationStrategyTaxRule.php
  src/CoreShop/Component/Shipping/Calculator/TaxedShippingCalculatorInterface.php
  src/CoreShop/Component/Shipping/Model/Carrier.php
  src/CoreShop/Component/Shipping/Model/CarrierInterface.php
  src/CoreShop/Component/Shipping/Taxation/TaxCalculationStrategyInterface.php
Labels: enhancement, new feature

#1313 Fixes the category items-per-page dropdown in the frontend (didn't wo…
  src/CoreShop/Bundle/FrontendBundle/Resources/public/static/js/shop.js
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/index.html.twig
Labels: bug

#1312 Add Documentation for Unit Definitions
  docs/03_Development/03_Products/06_Unit_Definitions.md
  docs/03_Development/03_Products/README.md
Labels: docs

#1315 [Customer] fix missing username field
  docs/03_Development/12_Customers/04_Registration_Types.md
  src/CoreShop/Bundle/CoreBundle/Form/Type/CustomerRegistrationType.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200211120529.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCustomer.json
  src/CoreShop/Bundle/CustomerBundle/Form/Type/CustomerType.php
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomer.json
  src/CoreShop/Component/Customer/Model/Customer.php
  src/CoreShop/Component/Customer/Model/CustomerInterface.php
Labels: bug

#1309 [FrontendBundle/CoreBundle] prevent _fragment calls by using ACL's
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/security.yml
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/FrontendBundle/EventListener/PartialProtectionListener.php
  src/CoreShop/Bundle/FrontendBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/Installer/Configuration/RouteConfiguration.php
Labels: bug

#1021 [Payment] decouple Payment from Payum and consider decimal factor
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200224164328.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Payment.orm.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.yml
  src/CoreShop/Bundle/PaymentBundle/composer.json
  src/CoreShop/Bundle/PayumBundle/Action/AuthorizePaymentAction.php
  src/CoreShop/Bundle/PayumBundle/Action/CapturePaymentAction.php
  src/CoreShop/Bundle/PayumBundle/Action/ExecuteSameRequestWithPaymentDetailsAction.php
  src/CoreShop/Bundle/PayumBundle/Resources/config/services.yml
  src/CoreShop/Component/Core/Model/Payment.php
  src/CoreShop/Component/Core/Model/PaymentInterface.php
  src/CoreShop/Component/Order/Model/OrderPaymentInterface.php
  src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php
  src/CoreShop/Component/Payment/Model/Payment.php
  src/CoreShop/Component/Payment/Model/PaymentInterface.php
  src/CoreShop/Component/Payment/composer.json
Labels: enhancement

#1325 [Installer] change installer colors
  src/CoreShop/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
  src/CoreShop/Bundle/ResourceBundle/Installer/AbstractTranslationInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreClassInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDocumentsInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreGridConfigInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreImageThumbnailsInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcorePermissionInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreRoutesInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/SqlInstaller.php
Labels: enhancement

#1326 [3.0] change IndexableInterface and pass IndexInterface
  UPGRADE-3.0.x.md
  src/CoreShop/Behat/Context/Domain/FilterContext.php
  src/CoreShop/Behat/Model/Index/TestEnableIndex.php
  src/CoreShop/Behat/Model/Index/TestIndex.php
  src/CoreShop/Behat/Model/Index/TestIndexFields.php
  src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
  src/CoreShop/Component/Core/Model/Product.php
  src/CoreShop/Component/Index/Model/IndexableInterface.php
Labels: BC break, enhancement

#1328 [Reports] fix export params #839
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/abstract.js
Labels: bug

#1331 [2.2.0-RC.2] release
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1332 [2.1.5] prepare release
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE
