Repository coreshop/CoreShop, pull requests merged in 2020-05, with the labels that each got.

#1373 Fix customer address display on invoice
  src/CoreShop/Bundle/OrderBundle/Resources/views/OrderDocumentPrint/invoice.html.twig
Labels: enhancement

#1372 Backport fix getDataForEditmode #1361
  src/CoreShop/Component/Pimcore/DataObject/DataLoader.php
Labels: bug

#1375 [2.1.7] prepare release
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1352 [2.2.0] prepare release
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1389 [DataHub] fix integration
  src/CoreShop/Bundle/AddressBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/MoneyBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/StoreBundle/Resources/config/services/data_hub.yml
  src/CoreShop/Bundle/TaxationBundle/Resources/config/services/data_hub.yml
Labels: bug

#1386 [FrontendBundle] revert url-forward, doesn't work for all cases
  src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
  src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php
Labels: bug

#1382 [PimcoreBundle] fix dynamic selects with Javascript
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdown.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdownMultiple.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdownTrait.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/ItemSelector.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/SuperBoxSelect.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopDynamicDropdown.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopDynamicDropdownMultiple.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopItemSelector.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopSuperBoxSelect.js
Labels: bug

#1385 [ResourceBundle] Fix unique entity validator
  src/CoreShop/Bundle/ResourceBundle/Validator/Constraints/UniqueEntityValidator.php
Labels: bug

#1390 [CoreBundle] fix validation groups
  src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/PaymentType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/SummaryType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/GuestRegistrationType.php
Labels: bug

#1391 [CoreBundle] fix registration service
  src/CoreShop/Bundle/CoreBundle/Customer/RegistrationService.php
Labels: bug

#1396 [2.1.8] prepare release
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1397 [2.2.1] prepare release
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1398 [QuantityPriceRules] fix decimal precision display
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/productquantitypricerules/ranges.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/helpers.js
Labels: bug

#1236 [3.0] Allow to create a new Customer within the order-creation Process
  src/CoreShop/Bundle/AddressBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/country.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/country_salutation.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/state.js
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/zone.js
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/resource/currency.js
  src/CoreShop/Bundle/CustomerBundle/Form/Type/CustomerType.php
  src/CoreShop/Bundle/OrderBundle/Controller/AddressCreationController.php
  src/CoreShop/Bundle/OrderBundle/Controller/CustomerCreationController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderCreationController.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/OrderBundle/Event/AdminAddressCreationEvent.php
  src/CoreShop/Bundle/OrderBundle/Event/AdminCustomerCreationEvent.php
  src/CoreShop/Bundle/OrderBundle/Events.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/AdminAddressCreationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/AdminCustomerCreationType.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/create/address.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/create/customer.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/create/panel.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/create/step/address.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/units/builder.js
  src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/helpers.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/creation.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/item.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/selector/object.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/selector/selector.js
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/resource/taxRate.js
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/resource/taxRuleGroup.js
  src/CoreShop/Component/Address/Model/DefaultAddressAwareInterface.php
  src/CoreShop/Component/Core/Model/CustomerInterface.php
Labels: new feature

#1393 [3.0] introduce tax-display service
  src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/taxation.yml
  src/CoreShop/Bundle/CoreBundle/Twig/ProductTaxExtension.php
  src/CoreShop/Bundle/CoreBundle/Twig/TaxationDisplayProviderExtension.php
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/Macro/product_price.html.twig
  src/CoreShop/Component/Core/Taxation/DefaultTaxationDisplayProvider.php
  src/CoreShop/Component/Core/Taxation/TaxationDisplayProviderInterface.php
Labels: enhancement

#1399 [SEO] integration to dachcom-digital/pimcore-seo
  composer.json
  src/CoreShop/Behat/Context/Domain/SEOContext.php
  src/CoreShop/Bundle/CoreBundle/Command/MigrateCommand.php
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/CoreShopCoreExtension.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/commands.yml
  src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
  src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Extension/AbstractModelExtension.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDependantBundleInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services/installer.yml
  src/CoreShop/Component/Core/Model/CategoryInterface.php
  src/CoreShop/Component/Core/Model/ProductInterface.php
  src/CoreShop/Component/SEO/Extractor/LuceneSearchExtractor.php
  src/CoreShop/Component/SEO/Model/LuceneSearchAwareInterface.php
  src/CoreShop/Component/SEO/Model/LuceneSearchCategoriesAwareInterface.php
  src/CoreShop/Component/SEO/composer.json
Labels: enhancement, new feature

#1406 [CurrencyBundle] fix cache issue with money-currency type
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
Labels: bug

#1410 [RuleBundle] improve dirty detection
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/condition.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/nested.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/item.js
  src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/rule/item.js
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/public/pimcore/js/productQuantityPriceRules/object/item.js
  src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/action.js
  src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/condition.js
  src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/conditions/nested.js
  src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/item.js
Labels: bug

#1408 Fixed issue with saving address changes
  src/CoreShop/Component/Core/Customer/CustomerTransformHelper.php
Labels: bug
