Repository coreshop/CoreShop, pull requests merged in 2020-12, with the labels that each got.

#1534 [ResourceBundle] add Pimcore DeepCopy Subscriber to fix doctrine collections clone problem
  src/CoreShop/Bundle/ResourceBundle/EventListener/DeepCopySubscriber.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
Labels: bug

#1538 [DynmicDropdown] support class override and fix order by id
  src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php
Labels: bug

#1539 [composer2] make getVersion compatible
  src/CoreShop/Bundle/FrontendBundle/CoreShopFrontendBundle.php
  src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
  src/CoreShop/Bundle/MenuBundle/CoreShopMenuBundle.php
  src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
  src/CoreShop/Bundle/ResourceBundle/AbstractResourceBundle.php
  src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
  src/CoreShop/Bundle/SEOBundle/CoreShopSEOBundle.php
  src/CoreShop/Bundle/ThemeBundle/CoreShopThemeBundle.php
Labels: enhancement

#1537 [OptimisticLock] allow to optimistically lock Pimcore DataObjects
  bin/subtree-release
  bin/subtree-split
  composer.json
  features/optimistic_entity_lock/lock.feature
  src/CoreShop/Behat/Context/Setup/OptimisticEntityLockContext.php
  src/CoreShop/Behat/Context/Setup/PimcoreClassContext.php
  src/CoreShop/Behat/Context/Transform/PimcoreClassContext.php
  src/CoreShop/Behat/Model/Lock/OptimisticLock.php
  src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
  src/CoreShop/Behat/Resources/config/suites.yml
  src/CoreShop/Behat/Resources/config/suites/domain/optimistic_entity_lock.yml
  src/CoreShop/Bundle/OptimisticEntityLockBundle/CoreShopOptimisticEntityLockBundle.php
  src/CoreShop/Bundle/OptimisticEntityLockBundle/DependencyInjection/CoreShopOptimisticEntityLockExtension.php
  src/CoreShop/Bundle/OptimisticEntityLockBundle/EventListener/LockListener.php
  src/CoreShop/Bundle/OptimisticEntityLockBundle/Exception/OptimisticLockException.php
  src/CoreShop/Bundle/OptimisticEntityLockBundle/LICENSE.md
  src/CoreShop/Bundle/OptimisticEntityLockBundle/Manager/EntityLockManager.php
  src/CoreShop/Bundle/OptimisticEntityLockBundle/Manager/EntityLockManagerInterface.php
  src/CoreShop/Bundle/OptimisticEntityLockBundle/Model/OptimisticLockedInterface.php
  src/CoreShop/Bundle/OptimisticEntityLockBundle/README.md
  src/CoreShop/Bundle/OptimisticEntityLockBundle/Resources/config/services.yml
  src/CoreShop/Bundle/OptimisticEntityLockBundle/composer.json
  src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
  src/CoreShop/Bundle/ResourceBundle/composer.json
Labels: bug, enhancement, new feature

#1526 Fix checkout with addressAccessType COMPANY_ONLY
  src/CoreShop/Bundle/CoreBundle/Form/Type/AddressChoiceType.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/form.yml
Labels: bug

#1543 ignore failed payments in total amount check
  src/CoreShop/Bundle/OrderBundle/Controller/OrderPaymentController.php
Labels: bug

#1548 [Order] fix payment provider
  src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php
Labels: bug

#1547 [ProductBundle] fix UnitDefinition without id
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php
Labels: bug

#1544 fix addressAccessType check and improve view
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/address.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/addresses.html.twig
  src/CoreShop/Component/Core/Customer/Address/AddressAssignmentManager.php
Labels: bug, enhancement

#1549 Issues/concurrency
  src/CoreShop/Bundle/OptimisticEntityLockBundle/EventListener/LockListener.php
  src/CoreShop/Bundle/OptimisticEntityLockBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PayumBundle/EventListener/TransactionListener.php
  src/CoreShop/Bundle/PayumBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/PayumBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PayumBundle/Storage/LockingStorage.php
Labels: bug
