Repository coreshop/CoreShop, pull requests merged in 2020-01, with the labels that each got.

#1200 [#1198] fix item price for items without tax-rule
  src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
Labels: bug

#1205 [FrontendBundle] add trailing $ to routes
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml
Labels: bug

#1204 [CoreBundle] remove usage of addCsrfTokenToUrl
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/preview.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice/render.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/shipment/render.js
Labels: bug

#1208 [Tests] fix tests
  etc/_scripts/composer
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
Labels: bug

#1228 complete unclosed service declaration
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/product.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services/form.yml
Labels: bug

#1233 [Stan] fix issues
  src/CoreShop/Behat/Extension/CoverageExtension.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/AbstractProductFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/CarrierFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ShippingRuleGroupFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/TaxRuleGroupFixture.php
Labels: bug

#1231 [TRACKING] use single item price in order item extractor
  src/CoreShop/Component/Core/Tracking/Extractor/OrderItemExtractor.php
Labels: bug

#1232 [TRACKING] use single item price in order item extractor in CS 2.1
  src/CoreShop/Component/Core/Tracking/Extractor/OrderItemExtractor.php
Labels: bug

#1230 [2.0.12] prepare release
  CHANGELOG-2.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1229 [2.1.1] prepare release
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1241 fix: $indexIds is always an array, hence the condition is now empty n…
  src/CoreShop/Bundle/IndexBundle/Command/IndexCommand.php
Labels: bug

#1235 [ThemeBundle] fix Undefined index: default_resolvers
  src/CoreShop/Bundle/ThemeBundle/DependencyInjection/CoreShopThemeExtension.php
Labels: bug

#1242 fix: typo
  docs/03_Development/03_Products/01_CRUD.md
Labels: docs

#1239 [STAN] fixes
  etc/_scripts/phpstan
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Document/Select.php
  src/CoreShop/Component/Pimcore/DataObject/ClassDefinitionFieldReNamer.php
Labels: bug

#1238 [CurrencyBundle] fix money-currency type is rounding prices wrong
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
Labels: bug

#1248 [FrontendBundle] Change function from private to protected
  src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
Labels: enhancement

#1252 [CoreBundle] Change repository so that unit definition deletion works with multiple product models
  src/CoreShop/Bundle/CoreBundle/Controller/ProductValidationController.php
Labels: bug

#1250 [Order] fix throwing/catching right exceptions in purchasable calcula…
  src/CoreShop/Component/Order/Calculator/CompositePurchasableDiscountPriceCalculator.php
  src/CoreShop/Component/Order/Calculator/PurchasableCalculator.php
Labels: bug

#1251 [FrontendBundle] Remove duplicate condition in template
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_grid.html.twig
Labels: bug

#1253 Remove duplicate condition in template
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_grid.html.twig
Labels: bug
