Repository coreshop/CoreShop, pull requests merged in 2020-04, with the labels that each got.

#1334 [Order] don't allow order-revise when completed payment has been made
  src/CoreShop/Bundle/FrontendBundle/Controller/OrderController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
Labels: bug, enhancement

#1333 [Order] persist internal cancellation reasons
  src/CoreShop/Bundle/FrontendBundle/Controller/OrderController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/OrderBundle/Expiration/OrderExpiration.php
Labels: enhancement

#1338 [Pimcore] require min 6.6
  .github/workflows/behat.yml
  .travis.yml
  composer.json
  src/CoreShop/Bundle/AddressBundle/composer.json
  src/CoreShop/Bundle/ConfigurationBundle/composer.json
  src/CoreShop/Bundle/CoreBundle/composer.json
  src/CoreShop/Bundle/CurrencyBundle/composer.json
  src/CoreShop/Bundle/CustomerBundle/composer.json
  src/CoreShop/Bundle/IndexBundle/composer.json
  src/CoreShop/Bundle/MenuBundle/composer.json
  src/CoreShop/Bundle/MoneyBundle/composer.json
  src/CoreShop/Bundle/NotificationBundle/composer.json
  src/CoreShop/Bundle/OrderBundle/composer.json
  src/CoreShop/Bundle/PaymentBundle/composer.json
  src/CoreShop/Bundle/PayumBundle/composer.json
  src/CoreShop/Bundle/ProductBundle/composer.json
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/composer.json
  src/CoreShop/Bundle/ResourceBundle/composer.json
  src/CoreShop/Bundle/StoreBundle/composer.json
  src/CoreShop/Bundle/ThemeBundle/composer.json
  src/CoreShop/Bundle/TrackingBundle/composer.json
  src/CoreShop/Bundle/WorkflowBundle/composer.json
  src/CoreShop/Component/Locale/composer.json
  src/CoreShop/Component/Pimcore/composer.json
  src/CoreShop/Component/Resource/composer.json
Labels: enhancement

#1339 [SecurityValidator] only trigger when Pimcore Frontend request
  src/CoreShop/Bundle/CoreBundle/EventListener/CustomerSecurityValidationListener.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
Labels: bug

#1323 [3.0] remove php template helpers
  UPGRADE-3.0.x.md
  src/CoreShop/Bundle/AddressBundle/Resources/config/services.yml
  src/CoreShop/Bundle/AddressBundle/Templating/Helper/FormatAddressHelper.php
  src/CoreShop/Bundle/AddressBundle/Templating/Helper/FormatAddressHelperInterface.php
  src/CoreShop/Bundle/AddressBundle/Twig/FormatAddressExtension.php
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/CoreShopCoreExtension.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/checkout.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/customer.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/product.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/CoreBundle/Storage/CookieStorage.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/AddressAllocatorHelper.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/AddressAllocatorHelperInterface.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/CheckoutIdentifierHelper.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/CheckoutIdentifierHelperInterface.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/ConfigurationHelper.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/ConfigurationHelperInterface.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/ProductPriceHelper.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/ProductPriceHelperInterface.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/ProductQuantityPriceRuleRangesPriceHelper.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/ProductQuantityPriceRuleRangesPriceHelperInterface.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/ProductTaxHelper.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/ProductTaxHelperInterface.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/ValidPriceRulesHelper.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/ValidPriceRulesHelperInterface.php
  src/CoreShop/Bundle/CoreBundle/Twig/AddressAllocatorExtension.php
  src/CoreShop/Bundle/CoreBundle/Twig/CheckoutIdentifierExtension.php
  src/CoreShop/Bundle/CoreBundle/Twig/ConfigurationExtension.php
  src/CoreShop/Bundle/CoreBundle/Twig/ProductPriceExtension.php
  src/CoreShop/Bundle/CoreBundle/Twig/ProductQuantityPriceRuleRangesPriceExtension.php
  src/CoreShop/Bundle/CoreBundle/Twig/ProductTaxExtension.php
  src/CoreShop/Bundle/CoreBundle/Twig/ValidPriceRulesExtension.php
  src/CoreShop/Bundle/CurrencyBundle/Resources/config/services/twig.yml
  src/CoreShop/Bundle/CurrencyBundle/Templating/Helper/ConvertCurrencyHelper.php
  src/CoreShop/Bundle/CurrencyBundle/Templating/Helper/ConvertCurrencyHelperInterface.php
  src/CoreShop/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelper.php
  src/CoreShop/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelperInterface.php
  src/CoreShop/Bundle/CurrencyBundle/Twig/ConvertCurrencyExtension.php
  src/CoreShop/Bundle/CurrencyBundle/Twig/CurrencyExtension.php
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/Macro/currency.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/Macro/product_price.html.twig
  src/CoreShop/Bundle/InventoryBundle/Resources/config/services.yml
  src/CoreShop/Bundle/InventoryBundle/Templating/Helper/InventoryHelper.php
  src/CoreShop/Bundle/InventoryBundle/Templating/Helper/InventoryHelperInterface.php
  src/CoreShop/Bundle/InventoryBundle/Twig/InventoryExtension.php
  src/CoreShop/Bundle/MoneyBundle/Resources/config/services.yml
  src/CoreShop/Bundle/MoneyBundle/Templating/Helper/FormatMoneyHelper.php
  src/CoreShop/Bundle/MoneyBundle/Templating/Helper/FormatMoneyHelperInterface.php
  src/CoreShop/Bundle/MoneyBundle/Twig/FormatMoneyExtension.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/OrderBundle/Templating/Helper/OrderStateHelper.php
  src/CoreShop/Bundle/OrderBundle/Templating/Helper/OrderStateHelperInterface.php
  src/CoreShop/Bundle/OrderBundle/Twig/OrderStateExtension.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Templating/Helper/ProductQuantityPriceRuleRangesHelper.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Templating/Helper/ProductQuantityPriceRuleRangesHelperInterface.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Twig/ProductQuantityPriceRuleRangesExtension.php
Labels: BC break

#1341 [GithubAction] add stan test
  .github/workflows/stan.yml
  .travis.yml
  app/config/config_test.yml
  etc/_config/php.ini
  etc/_scripts/behat
  etc/_scripts/composer
  etc/_scripts/ecs
  etc/_scripts/phpstan
  etc/_scripts/phpunit
  etc/_scripts/twig
  etc/_scripts/yaml
  etc/_setup/install
  etc/scrutinizer/install
  etc/suites/application
  etc/suites/codestyle
  etc/suites/stan
  etc/travis/install
  etc/travis/script
  phpstan.neon
  src/CoreShop/Component/Core/Order/Calculator/PurchasableProductDiscountPriceCalculator.php
  src/CoreShop/Component/Order/Calculator/CompositePurchasableDiscountPriceCalculator.php
  src/CoreShop/Component/Order/Calculator/PurchasableCalculator.php
  src/CoreShop/Component/Order/Calculator/PurchasableDiscountPriceCalculatorInterface.php
  src/CoreShop/Component/Order/Calculator/PurchasablePriceCalculator.php
  src/CoreShop/Component/Order/Exception/NoPurchasableDiscountPriceFoundException.php
Labels: enhancement

#1337 [PimcoreBundle] fix dynamic dropdown extensions
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdown.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdownMultiple.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/ItemSelector.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/SuperBoxSelect.php
Labels: bug

#1345 [3.0] twig remove all get calls
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_item.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_items.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_rules.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_summary.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/_widget.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/summary.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_grid.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_list.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_menu-left.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_menu.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_category_select.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_multiselect.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_relational_multiselect.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_relational_select.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_select.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/index.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary/_item.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary/_list.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary/_rules.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary/_summary.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/Macro/currency.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/order_detail.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/paginator.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/_header.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/address.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/addresses.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/orders.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Mail/order-confirmation.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/_preview.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/detail.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/ProductQuantityPriceRanges/quantity_price_ranges_volume.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Quote/show.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Wishlist/summary.html.twig
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/twig.yml
Labels: enhancement

#1346 [OrderBundle] show price rules without tax in backend
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js
Labels: enhancement

#1348 [DynamicDropdown] add dependency resolving
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdown.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdownMultiple.php
  src/CoreShop/Bundle/PimcoreBundle/CoreExtension/ItemSelector.php
Labels: bug

#1349 [3.0] introduce class translations
  src/CoreShop/Bundle/AddressBundle/Resources/install/pimcore/admin-translations.yml
  src/CoreShop/Bundle/AddressBundle/Resources/install/pimcore/classes/CoreShopAddress.json
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/admin-translations.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCompany.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCustomer.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderItem.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderShipment.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderShipmentItem.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopCategory.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/admin-translations.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCompany.json
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomer.json
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomerGroup.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/admin-translations.yml
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderInvoice.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderInvoiceItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderShipment.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderShipmentItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/fieldcollections/CoreShopAdjustment.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/fieldcollections/CoreShopProposalCartPriceRuleItem.json
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/admin-translations.yml
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopCategory.json
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopManufacturer.json
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopProduct.json
  src/CoreShop/Component/Core/Customer/Address/AddressAccessOptionsProvider.php
Labels: enhancement

#1350 [CoreBundle][2.1] Fix name of country combo
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/store/item.js
Labels: bug

#1353 [ThemeBundle] introduce theme inheritance
  src/CoreShop/Bundle/ThemeBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ThemeBundle/DependencyInjection/CoreShopThemeExtension.php
  src/CoreShop/Bundle/ThemeBundle/Exception/CircularDependencyFoundException.php
  src/CoreShop/Bundle/ThemeBundle/Service/InheritanceLocator.php
Labels: new feature

#1351 [2.1.6] prepare release
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1355 [CoreBundle] add missing alias for taxed product price calculator
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/product.yml
Labels: bug

#1356 [Migration] move migration before other migration in order to avoid missing db columns
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20191122074930.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200213132916.php
Labels: bug

#1358 Revert "[Payment] decouple Payment from Payum and consider decimal factor"
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200224164328.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Payment.orm.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.yml
  src/CoreShop/Bundle/PaymentBundle/composer.json
  src/CoreShop/Bundle/PayumBundle/Action/AuthorizePaymentAction.php
  src/CoreShop/Bundle/PayumBundle/Action/CapturePaymentAction.php
  src/CoreShop/Bundle/PayumBundle/Action/ExecuteSameRequestWithPaymentDetailsAction.php
  src/CoreShop/Bundle/PayumBundle/Resources/config/services.yml
  src/CoreShop/Component/Core/Model/Payment.php
  src/CoreShop/Component/Core/Model/PaymentInterface.php
  src/CoreShop/Component/Order/Model/OrderPaymentInterface.php
  src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php
  src/CoreShop/Component/Payment/Model/Payment.php
  src/CoreShop/Component/Payment/Model/PaymentInterface.php
  src/CoreShop/Component/Payment/composer.json
Labels: BC break

#1361 [Pimcore] fix getDataForEditmode
  src/CoreShop/Component/Pimcore/DataObject/DataLoader.php
Labels: bug

#1359 [ThemeBundle] fix for inheritance locator when no theme is set
  src/CoreShop/Bundle/ThemeBundle/Service/InheritanceLocator.php
Labels: bug

#1363 [ThemeBundle] fix pimcore bc-break
  src/CoreShop/Bundle/ThemeBundle/EventListener/ThemeRequestListener.php
  src/CoreShop/Bundle/ThemeBundle/Resources/config/services.yml
Labels: bug

#1360 [Order] introduce paymentTotal Property to store the rounded payment value with a precision of 2
  docs/03_Development/20_Currency_Fractions/README.md
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200424071747.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200424071752.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200427113101.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200427113206.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopCart.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuote.json
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/helpers.js
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_summary.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary/_summary.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/Macro/currency.html.twig
  src/CoreShop/Bundle/MoneyBundle/Formatter/MoneyFormatter.php
  src/CoreShop/Bundle/MoneyBundle/Templating/Helper/FormatMoneyHelper.php
  src/CoreShop/Bundle/MoneyBundle/Templating/Helper/FormatMoneyHelperInterface.php
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopCart.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuote.json
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/payment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/OrderBundle/StateResolver/OrderPaymentStateResolver.php
  src/CoreShop/Bundle/ThemeBundle/Service/InheritanceLocator.php
  src/CoreShop/Component/Core/Order/Processor/CartPaymentProcessor.php
  src/CoreShop/Component/Currency/Formatter/MoneyFormatterInterface.php
  src/CoreShop/Component/Order/Model/Cart.php
  src/CoreShop/Component/Order/Model/CartInterface.php
  src/CoreShop/Component/Order/Model/Sale.php
  src/CoreShop/Component/Order/Model/SaleInterface.php
  src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php
  src/CoreShop/Component/Order/Transformer/AbstractCartToSaleTransformer.php
  src/CoreShop/Component/Payment/Model/PayableInterface.php
Labels: bug

#1366 [Order] use Javascript intl for currency format
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/helpers.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/order/detail/blocks/carriage.js
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractCartCreationController.php
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
  src/CoreShop/Bundle/OrderBundle/Controller/CartController.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/detail/blocks/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/invoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/payment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/editInvoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/shipment.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/products.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/totals.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/header.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/helpers.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/panel.js
Labels: enhancement

#1365 [Product] serialize stopPropogation property
  src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.AbstractPriceRule.yml
Labels: bug

#1367 [FrontendBundle] allow preview from admin-mode and redirect to right URL if wrong
  src/CoreShop/Bundle/CoreBundle/Controller/ProductPreviewController.php
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
  src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/PimcoreRepository.php
  src/CoreShop/Component/Core/Model/CategoryInterface.php
  src/CoreShop/Component/Core/Model/PimcoreStoresAwareInterface.php
  src/CoreShop/Component/Core/Model/ProductInterface.php
  src/CoreShop/Component/Resource/Pimcore/Model/PimcoreModelInterface.php
Labels: enhancement

#1370 [Product] fix null value for pricing #1362
  src/CoreShop/Bundle/ProductBundle/Form/Type/Unit/ProductUnitDefinitionPriceType.php
  src/CoreShop/Component/Product/Model/ProductUnitDefinitionPrice.php
Labels: bug

#1368 [CoreBundle] only show restore-inheritance when actually inheritable
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopStoreValues.js
Labels: bug, enhancement
