Repository coreshop/CoreShop, pull requests merged in 2020-07, with the labels that each got.

#1439 [Core] fix calculation of discounts with tax rounding issues
  features/domain/cart/rules/discount_amount_action_tax_rounding.feature
  src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php
Labels: bug

#1441 [2.0] Voucher Credit and Tax rounding issue
  features/cart/rules/discount_amount_action_tax_rounding.feature
  features/cart/rules/voucher_credit_action.feature
  src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200617120130.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/css/core.css
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/img/voucher.svg
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/doctrine/model/CartPriceRuleVoucherCode.orm.yml
  src/CoreShop/Component/Core/Cart/Rule/Action/VoucherCreditActionProcessor.php
  src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php
  src/CoreShop/Component/Order/Model/CartPriceRuleVoucherCode.php
  src/CoreShop/Component/Order/Model/CartPriceRuleVoucherCodeInterface.php
  src/CoreShop/Component/Order/Modifier/VoucherModifier.php
Labels: bug, enhancement

#1443 [2.2][OrderBundle] Values should be zero, if amount should not be defined
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/AmountConfigurationType.php
Labels: bug, enhancement

#1444 [2.2][Core] create default address if customer doesn't have one
  src/CoreShop/Component/Core/Customer/Address/AddressAssignmentManager.php
Labels: bug, enhancement

#1442 [2.2][FrontendBundle] apply confirm and pay transition for orders with value of 0
  src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
Labels: bug, enhancement

#1440 assert default address type
  src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/checkout.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/public/static/js/shop.js
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/address.html.twig
Labels: bug

#1446 [2.2.3] prepare release
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1447 [ProductBundle] fix serialization of translation labels in product-price rules
  src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.AbstractPriceRule.yml
Labels: bug

#1451 fix voucher code generator
  src/CoreShop/Component/Order/Generator/CartPriceRuleVoucherCodeGenerator.php
Labels: bug

#1454 [OrderBundle] don't remove certain elements from toolbar, just hide them
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/list.js
Labels: bug

#1455 [CoreBundle] fix installation of address format
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php
Labels: bug

#1456 [OrderBundle] check if generation of a certain amount of codes is possible before actually generating them
  features/cart/rules/voucher_code_generation.feature
  src/CoreShop/Behat/Context/Domain/CartPriceRuleVoucherCodeContext.php
  src/CoreShop/Behat/Context/Setup/CartPriceRuleVoucherCodeContext.php
  src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
  src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
  src/CoreShop/Behat/Resources/config/suites/domain/cart.yml
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200715071804.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
  src/CoreShop/Bundle/OrderBundle/Controller/CartPriceRuleController.php
  src/CoreShop/Bundle/OrderBundle/Doctrine/ORM/CartPriceRuleVoucherRepository.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/validation/CartPriceRuleVoucherGenerator.yml
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/item.js
  src/CoreShop/Bundle/OrderBundle/Validator/Constraints/VoucherAmount.php
  src/CoreShop/Bundle/OrderBundle/Validator/Constraints/VoucherAmountValidator.php
  src/CoreShop/Bundle/ResourceBundle/Form/Helper/ErrorSerializer.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
  src/CoreShop/Component/Order/Exception/FailedCodeGenerationException.php
  src/CoreShop/Component/Order/Generator/CartPriceRuleVoucherCodeGenerator.php
  src/CoreShop/Component/Order/Generator/CodeGeneratorChecker.php
  src/CoreShop/Component/Order/Generator/CodeGeneratorCheckerInterface.php
  src/CoreShop/Component/Order/Generator/CodeGeneratorLetterResolver.php
  src/CoreShop/Component/Order/Repository/CartPriceRuleVoucherRepositoryInterface.php
Labels: bug, enhancement

#1462 [Core, Order] fix surchage amount processor and remove apply-on
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Action/SurchargeAmountConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/actions/surchargeAmount.js
  src/CoreShop/Component/Core/Cart/Rule/Action/SurchargeAmountActionProcessor.php
Labels: bug

#1461 [OrderBundle] fix usage of inherited values in backend-cart/order controllers
  src/CoreShop/Bundle/OrderBundle/Controller/AbstractCartCreationController.php
  src/CoreShop/Bundle/OrderBundle/Controller/CartEditController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderCreationController.php
Labels: bug

#1465 Fix Ext Item Selector
  src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/ext/ItemSelector.js
Labels: bug

#1452 [EntityMerger] reset state of newData
  src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php
Labels: bug

#1468 [CoreBundle] don't validate 0 for Minimum and Maximum Quantity to Order
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/AddToCartMaximumQuantityValidator.php
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/AddToCartMinimumQuantityValidator.php
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/CartMaximumQuantityValidator.php
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/CartMinimumQuantityValidator.php
  src/CoreShop/Bundle/CoreBundle/Validator/QuantityValidatorService.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/validation/Cart.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/validation/CartItem.yml
Labels: bug, enhancement

#1469 [2.1.9] prepare release
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1471 [2.2.4] prepare release
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE
