Repository coreshop/CoreShop, pull requests merged in 2020-02, with the labels that each got.

#1258 change assets:install for fresh installations
  docs/03_Development/01_Extending_Guide/04_Extending_Rule_Actions.md
  docs/03_Development/01_Extending_Guide/05_Extending_Rule_Conditions.md
Labels: docs

#1264 [Installer] update logo
  src/CoreShop/Bundle/CoreBundle/Command/InstallCommand.php
Labels: enhancement

#1259 [IndexBundle] fix index columns form
  src/CoreShop/Bundle/IndexBundle/Form/Type/Worker/MysqlWorkerTableIndexType.php
Labels: bug

#1267 [Cart] introduce cart-context resolver to allow better extendability of the context used for the cart
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/context.yml
  src/CoreShop/Component/Core/Cart/CartContextResolver.php
  src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartItemsWholesaleProcessor.php
  src/CoreShop/Component/Order/Cart/CartContextResolver.php
  src/CoreShop/Component/Order/Cart/CartContextResolverInterface.php
Labels: enhancement

#1261 [Country] don't call the request based resolvers every time
  src/CoreShop/Bundle/AddressBundle/Resources/config/services.yml
  src/CoreShop/Component/Address/Context/RequestBased/CachedCountryContext.php
  src/CoreShop/Component/Address/Context/RequestBased/GeoLiteBasedRequestResolver.php
Labels: bug

#1268 [2.1.2] prepare release
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1270 [2.1.3] prepare release
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1273 [CoreBundle] allow store-values to be reset and inherit again
  src/CoreShop/Bundle/CoreBundle/Controller/ProductController.php
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Bundle/CoreBundle/EventListener/ProductStoreValuesAdminGetListener.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_product.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopStoreValues.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Configuration.php
Labels: bug, enhancement

#1281 [ThemeBundle] fix default theme-resolvers
  src/CoreShop/Bundle/ThemeBundle/DependencyInjection/CoreShopThemeExtension.php
Labels: bug

#1284 Company Feature
  src/CoreShop/Bundle/CoreBundle/Controller/CustomerTransformerController.php
  src/CoreShop/Bundle/CoreBundle/Customer/RegistrationService.php
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CoreBundle/EventListener/CustomerCompanyRelationListener.php
  src/CoreShop/Bundle/CoreBundle/Form/Extension/AddressTypeExtension.php
  src/CoreShop/Bundle/CoreBundle/Menu/MainMenuBuilder.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200211120529.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_customer.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/customer.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/settings.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCompany.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCustomer.json
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/css/core.css
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/img/customer_to_company_assign_to_existing_white.svg
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/img/customer_to_company_assign_to_new_white.svg
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/img/customer_white.svg
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/customer/abstractCustomerModifier.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/customer/customerToExistingCompanyAssignment.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/customer/customerToNewCompanyAssignment.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/AddressAllocatorHelper.php
  src/CoreShop/Bundle/CoreBundle/Templating/Helper/AddressAllocatorHelperInterface.php
  src/CoreShop/Bundle/CoreBundle/Twig/AddressAllocatorExtension.php
  src/CoreShop/Bundle/CustomerBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CustomerBundle/Pimcore/Repository/CompanyRepository.php
  src/CoreShop/Bundle/CustomerBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/admin-translations.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCompany.json
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomer.json
  src/CoreShop/Bundle/CustomerBundle/Resources/public/pimcore/img/company.svg
  src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/address.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/addresses.html.twig
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Address/Model/AddressesAwareInterface.php
  src/CoreShop/Component/Address/Model/AddressesAwareTrait.php
  src/CoreShop/Component/Core/Customer/Address/AddressAccessOptionsProvider.php
  src/CoreShop/Component/Core/Customer/Address/AddressAssignmentManager.php
  src/CoreShop/Component/Core/Customer/Address/AddressAssignmentManagerInterface.php
  src/CoreShop/Component/Core/Customer/Allocator/CustomerAddressAllocator.php
  src/CoreShop/Component/Core/Customer/Allocator/CustomerAddressAllocatorInterface.php
  src/CoreShop/Component/Core/Customer/CustomerTransformHelper.php
  src/CoreShop/Component/Core/Customer/CustomerTransformHelperInterface.php
  src/CoreShop/Component/Core/Model/Company.php
  src/CoreShop/Component/Core/Model/CompanyInterface.php
  src/CoreShop/Component/Core/Model/Customer.php
  src/CoreShop/Component/Core/Model/CustomerInterface.php
  src/CoreShop/Component/Customer/Model/Company.php
  src/CoreShop/Component/Customer/Model/CompanyInterface.php
  src/CoreShop/Component/Customer/Model/Customer.php
  src/CoreShop/Component/Customer/Model/CustomerInterface.php
  src/CoreShop/Component/Customer/Repository/CompanyRepositoryInterface.php
Labels: enhancement, new feature

#1254 [CoreExtensions] fix issue with CoreShop CoreExtensions Recycle Bin
  features/recycle_bin/store_values.feature
  src/CoreShop/Behat/Context/Domain/RecycleBinContext.php
  src/CoreShop/Behat/Context/Setup/RecycleBinContext.php
  src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
  src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
  src/CoreShop/Behat/Resources/config/suites.yml
  src/CoreShop/Behat/Resources/config/suites/domain/recycle_bin.yml
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php
  src/CoreShop/Component/Pimcore/BCLayer/CustomRecyclingMarshalInterface.php
Labels: bug

#1255 [Validation] add configurable validation group to forms
  src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/CarrierType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/PaymentType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/SummaryType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/CustomerRegistrationType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/GuestRegistrationType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/ProductPriceRule/Condition/QuantityConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Shipping/Rule/Action/AdditionAmountActionConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Shipping/Rule/Action/DiscountAmountActionConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Shipping/Rule/Action/PriceActionConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/form_extension.yml
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionCategorySelectType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionMultiselectType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionRangeType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionSelectType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterPreConditionNestedType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterUserConditionNestedType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Getter/BrickGetterFormType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Getter/ClassificationStoreGetterFormType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Getter/FieldCollectionGetterFormType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/IndexColumnType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Interpreter/ExpressionInterpreterFormType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Interpreter/IteratorInterpreterType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Interpreter/NestedInterpreterType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Interpreter/ObjectPropertyInterpreterFormType.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Action/DiscountAmountConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Action/DiscountPercentConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Action/SurchargeAmountConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Action/SurchargePercentConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/AmountConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/NestedConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/TimespanConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/VoucherConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/forms.yml
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Action/DiscountAmountConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Action/DiscountPercentConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Action/PriceConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Condition/ProductPriceNestedConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Condition/ProductSpecificPriceNestedConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Condition/TimespanConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Form/Type/ProductQuantityPriceRuleType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/AdditionPercentActionConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/DiscountPercentActionConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Common/ShippingRuleConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/AmountConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/DimensionConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/NestedConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/PostcodeConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/WeightConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services/form.yml
Labels: enhancement

#1292 [CoreBundle] fix shipping rule action discount-amount
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/form.yml
Labels: bug

#1291 Implement Username/Email Login Identifier
  CHANGELOG-2.2.x.md
  docs/03_Development/12_Customers/03_Registration_Service.md
  docs/03_Development/12_Customers/04_Registration_Types.md
  docs/03_Development/12_Customers/05_Company_Extension.md
  docs/03_Development/12_Customers/README.md
  src/CoreShop/Behat/Context/Transform/CustomerContext.php
  src/CoreShop/Bundle/CoreBundle/Customer/RegistrationService.php
  src/CoreShop/Bundle/CoreBundle/EventListener/CustomerSecurityValidationListener.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200211120529.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/customer.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
  src/CoreShop/Bundle/CoreBundle/Security/ObjectUserProvider.php
  src/CoreShop/Bundle/CustomerBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CustomerBundle/DependencyInjection/CoreShopCustomerExtension.php
  src/CoreShop/Bundle/CustomerBundle/Form/Type/CustomerLoginType.php
  src/CoreShop/Bundle/CustomerBundle/Form/Type/RequestResetPasswordType.php
  src/CoreShop/Bundle/CustomerBundle/Pimcore/Repository/CustomerRepository.php
  src/CoreShop/Bundle/CustomerBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/config/validation/Customer.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/translations/validators.de.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/translations/validators.en.yml
  src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services/validators.yml
  src/CoreShop/Bundle/ResourceBundle/Validator/Constraints/UniqueEntityValidator.php
  src/CoreShop/Component/Customer/Model/Customer.php
  src/CoreShop/Component/Customer/Repository/CustomerRepositoryInterface.php
Labels: enhancement

#1293 [Core] fix bug where we calculated item-discount and item-discount-prices
  features/cart/cart_item_taxes.feature
  features/cart/cart_item_taxes_gross.feature
  src/CoreShop/Behat/Context/Domain/CartContext.php
  src/CoreShop/Behat/Resources/config/suites/domain/cart.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopCartItem.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderItem.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuoteItem.json
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_item.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary/_item.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/order_detail.html.twig
  src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
Labels: bug

#1295 [2.1.4] prepare release
  CHANGELOG-2.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1296 [2.2.0-RC.1] prepare release
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1302 [AddressBundle] introduce filter-active action and filter store-base countries by those
  src/CoreShop/Bundle/AddressBundle/Controller/CountryController.php
  src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/AddressBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/store/item.js
Labels: bug

#1301 [ThemeBundle] fix configuration for default resolvers
  src/CoreShop/Bundle/ThemeBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ThemeBundle/DependencyInjection/CoreShopThemeExtension.php
Labels: bug

#1300 [IndexBundle] index ui improvements
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/fields.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/item.js
Labels: bug, enhancement

#1303 [IndexBundle] allow configuring if versions should be indexed or not
  features/index/index_version.feature
  src/CoreShop/Behat/Context/Setup/IndexContext.php
  src/CoreShop/Behat/Context/Setup/PimcoreClassContext.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200224160300.php
  src/CoreShop/Bundle/IndexBundle/EventListener/IndexObjectListener.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/IndexType.php
  src/CoreShop/Bundle/IndexBundle/Migrations/Version20200224161101.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/doctrine/model/Index.orm.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/serializer/Model.Index.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/item.js
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Index/Model/Index.php
  src/CoreShop/Component/Index/Model/IndexInterface.php
  src/CoreShop/Component/Index/Service/IndexUpdaterService.php
  src/CoreShop/Component/Index/Service/IndexUpdaterServiceInterface.php
Labels: bug, enhancement

#1304 [CoreBundle] fix typo in validation groups and fix guest-registration type
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/form.yml
Labels: bug
