Repository coreshop/CoreShop, pull requests merged in 2021-07, with the labels that each got.

#1657 [Rule] refactor Rule conditions and actions peristance
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20210614115749.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/doctrine/model/Filter.orm.yml
  src/CoreShop/Bundle/NotificationBundle/Resources/config/doctrine/model/NotificationRule.orm.yml
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/NestedConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/doctrine/model/CartPriceRule.orm.yml
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Condition/ProductPriceNestedConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Condition/ProductSpecificPriceNestedConfigurationType.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductPriceRule.orm.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductSpecificPriceRule.orm.yml
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/specificprice/object/item.js
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Form/Type/Rule/Condition/ProductQuantityPriceRuleNestedConfigurationType.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/doctrine/model/ProductQuantityPriceRule.orm.yml
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/public/pimcore/js/productQuantityPriceRules/object/item.js
  src/CoreShop/Bundle/ResourceBundle/Controller/ResourceController.php
  src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php
  src/CoreShop/Bundle/RuleBundle/Form/DataMapper/ActionsFormMapper.php
  src/CoreShop/Bundle/RuleBundle/Form/DataMapper/ConditionsFormMapper.php
  src/CoreShop/Bundle/RuleBundle/Form/Type/RuleActionCollectionType.php
  src/CoreShop/Bundle/RuleBundle/Form/Type/RuleActionType.php
  src/CoreShop/Bundle/RuleBundle/Form/Type/RuleConditionCollectionType.php
  src/CoreShop/Bundle/RuleBundle/Form/Type/RuleConditionType.php
  src/CoreShop/Bundle/RuleBundle/Resources/config/doctrine/model/Action.orm.yml
  src/CoreShop/Bundle/RuleBundle/Resources/config/doctrine/model/Condition.orm.yml
  src/CoreShop/Bundle/RuleBundle/Resources/config/serializer/Model.Action.yml
  src/CoreShop/Bundle/RuleBundle/Resources/config/serializer/Model.Condition.yml
  src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/abstract.js
  src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/action.js
  src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/condition.js
  src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/item.js
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/NestedConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Resources/config/doctrine/model/ShippingRule.orm.yml
  src/CoreShop/Component/Rule/Model/Action.php
  src/CoreShop/Component/Rule/Model/ActionInterface.php
  src/CoreShop/Component/Rule/Model/Condition.php
  src/CoreShop/Component/Rule/Model/ConditionInterface.php
Labels: BC break, bug, enhancement

#1662 [OrderBundle] fix pagination in voucher codes and add pagination for csv export
  src/CoreShop/Bundle/OrderBundle/Controller/CartPriceRuleController.php
  src/CoreShop/Bundle/OrderBundle/Doctrine/ORM/CartPriceRuleVoucherRepository.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/item.js
  src/CoreShop/Component/Order/Repository/CartPriceRuleVoucherRepositoryInterface.php
Labels: bug

#1664 [CoreBundle] remove zones from shipping rules installer
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ShippingRuleFixture.php
Labels: bug

#1668 [FrontendBundle] Print cart price rule label instead name if available
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary/_rules.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/order_detail.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Quote/show.html.twig
Labels: enhancement

#1673 [Index] Fix merge for index-conditions
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20210614115749.php
  src/CoreShop/Bundle/IndexBundle/Controller/FilterController.php
  src/CoreShop/Bundle/IndexBundle/Form/DataMapper/ConditionsFormMapper.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterPreConditionNestedType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterUserConditionNestedType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/FilterConditionType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/FilterPreConditionCollectionType.php
  src/CoreShop/Bundle/IndexBundle/Form/Type/FilterUserConditionCollectionType.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/doctrine/model/FilterCondition.orm.xml
  src/CoreShop/Bundle/IndexBundle/Resources/config/serializer/Model.Index.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/condition.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/nested.js
  src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php
  src/CoreShop/Component/Index/Model/FilterCondition.php
  src/CoreShop/Component/Index/Model/FilterConditionInterface.php
Labels: bug

#1672 [Order] fix voucher modifier with empty voucher code
  features/ui/frontend/checkout/checkout_with_cart_price_rule_free_shipping.feature
  src/CoreShop/Component/Order/Modifier/VoucherModifier.php
Labels: bug

#1676 [Order] add proper events for cart-item add and remove
  docs/03_Development/14_Events/README.md
  src/CoreShop/Component/Order/Cart/CartModifier.php
  src/CoreShop/Component/Order/CartEvents.php
Labels: enhancement

#1677 Introduce a folder creation service which loads the paths directly from the metadata
  src/CoreShop/Bundle/CoreBundle/Customer/CustomerManager.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/customer.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/OrderBundle/Controller/CustomerCreationController.php
  src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/order_invoice.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/order_shipment.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
  src/CoreShop/Component/Core/Customer/CustomerTransformHelper.php
  src/CoreShop/Component/Core/Customer/CustomerTransformHelperInterface.php
  src/CoreShop/Component/Core/Order/Committer/OrderCommitter.php
  src/CoreShop/Component/Core/Order/Committer/QuoteCommitter.php
  src/CoreShop/Component/Order/Transformer/OrderItemToInvoiceItemTransformer.php
  src/CoreShop/Component/Order/Transformer/OrderItemToShipmentItemTransformer.php
  src/CoreShop/Component/Order/Transformer/OrderToInvoiceTransformer.php
  src/CoreShop/Component/Order/Transformer/OrderToShipmentTransformer.php
  src/CoreShop/Component/Resource/Service/FolderCreationService.php
  src/CoreShop/Component/Resource/Service/FolderCreationServiceInterface.php
Labels: enhancement

#1665 [OrderBundle] introduce order-item-units to get rid of rounding issues
  features/domain/cart/cart_item_unit_taxes.feature
  features/domain/cart/cart_item_units.feature
  features/domain/payment/concurrency.feature
  src/CoreShop/Behat/Context/Domain/CartContext.php
  src/CoreShop/Behat/Context/Setup/CartContext.php
  src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderItem.json
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/OrderBundle/Form/DataMapper/CartItemQuantityDataMapper.php
  src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderItemUnit.json
  src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.ProductUnitDefinitions.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/coreExtension/data/coreShopRelations.js
  src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php
  src/CoreShop/Component/Core/Order/Modifier/CartItemQuantityModifier.php
  src/CoreShop/Component/Core/Order/Processor/CartCurrencyConversionProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartItemTaxProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php
  src/CoreShop/Component/Order/Distributor/IntegerDistributor.php
  src/CoreShop/Component/Order/Distributor/IntegerDistributorInterface.php
  src/CoreShop/Component/Order/Factory/OrderItemUnitFactory.php
  src/CoreShop/Component/Order/Factory/OrderItemUnitFactoryInterface.php
  src/CoreShop/Component/Order/Model/AdjustableTrait.php
  src/CoreShop/Component/Order/Model/ConvertedAdjustableTrait.php
  src/CoreShop/Component/Order/Model/Order.php
  src/CoreShop/Component/Order/Model/OrderInterface.php
  src/CoreShop/Component/Order/Model/OrderItem.php
  src/CoreShop/Component/Order/Model/OrderItemInterface.php
  src/CoreShop/Component/Order/Model/OrderItemUnit.php
  src/CoreShop/Component/Order/Model/OrderItemUnitInterface.php
  src/CoreShop/Component/Taxation/Collector/TaxCollectorInterface.php
Labels: new feature

#1678 [Slug] default generate slugs and use instead of static routes for product and category
  features/domain/category/category_link.feature
  features/domain/product/product_link.feature
  features/ui/frontend/product/view_product_via_link.feature
  src/CoreShop/Behat/Context/Cli/InstallerContext.php
  src/CoreShop/Behat/Context/Domain/LinkGeneratorContext.php
  src/CoreShop/Behat/Context/Ui/Domain/PaymentController.php
  src/CoreShop/Behat/Context/Ui/Frontend/ProductContext.php
  src/CoreShop/Behat/Page/Frontend/ProductPage.php
  src/CoreShop/Behat/Page/Frontend/SluggablePageTrait.php
  src/CoreShop/Bundle/CoreBundle/Faker/Commerce.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/AbstractProductFixture.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/CategoryFixture.php
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopCategory.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
  src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
  src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml
  src/CoreShop/Bundle/PimcoreBundle/EventListener/SluggableListener.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/admin-translations.yml
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopCategory.json
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopProduct.json
  src/CoreShop/Component/Pimcore/Slug/SluggableInterface.php
  src/CoreShop/Component/Pimcore/Slug/SluggableLinkGenerator.php
  src/CoreShop/Component/Product/Model/Category.php
  src/CoreShop/Component/Product/Model/CategoryInterface.php
  src/CoreShop/Component/Product/Model/Product.php
  src/CoreShop/Component/Product/Model/ProductInterface.php
Labels: enhancement

#1686 [CoreBundle] AbstractPimcoreMigration leftover
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190605141526.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200415152607.php
  src/CoreShop/Bundle/IndexBundle/Migrations/Version20200224161101.php
Labels: bug

#1684 [FrontendBundle] Macro "price" is not defined in template
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Wishlist/summary.html.twig
Labels: bug

#1681 [CoreBundle] Use right permission for tax rate
  src/CoreShop/Bundle/CoreBundle/Menu/MainMenuBuilder.php
Labels: bug

#1687 [Migrations] fix further issues
  src/CoreShop/Bundle/CoreBundle/Command/MigrateCommand.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200206155318.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200415151307.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200415151505.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200415152315.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200415160423.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20200617120130.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/migrations.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/commands.yml
  src/CoreShop/Component/Pimcore/DataObject/AbstractDefinitionUpdate.php
  src/CoreShop/Component/Pimcore/DataObject/ClassUpdate.php
  src/CoreShop/Component/Pimcore/DataObject/ClassUpdateInterface.php
Labels: bug

#1689 [Pimcore] Use Pimcore ^10.0
  composer.json
Labels: enhancement

#1693 [Shipping] Ability to hide carrier from checkout
  src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/CarrierRepository.php
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/CarrierFixture.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20210720212955.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/CarrierType.php
  src/CoreShop/Bundle/ShippingBundle/Resources/config/doctrine/model/Carrier.orm.xml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/serializer/Model.Carrier.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/validation/Carrier.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/carrier/item.js
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.it.yml
  src/CoreShop/Component/Shipping/Model/Carrier.php
  src/CoreShop/Component/Shipping/Model/CarrierInterface.php
Labels: enhancement

#1695 [IndexBundle] Fix sort column on condition
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20210721112600.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/doctrine/model/FilterCondition.orm.yml
  src/CoreShop/Component/Index/Model/FilterCondition.php
  src/CoreShop/Component/Index/Model/FilterConditionInterface.php
Labels: bug

#1701 [CoreBundle] add migration for slugs in category and product
  src/CoreShop/Bundle/CoreBundle/Command/MigrationGenerateCommand.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20210719072811.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20210727061308.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20210727061604.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/commands.yml
Labels: bug, enhancement

#1705 [CoreBundle] fix with datahub enabled
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/data_hub.yml
Labels: bug
