Repository coreshop/CoreShop, pull requests merged in 2021-11, with the labels that each got.

#1764 [OrderBundle] fix admin en translations
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
Labels: bug

#1766 [CoreBundle] remove duplicate paymentTotal and convertedPaymentTotal from class definition
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
Labels: bug

#1768 [Faker] use fakerphp/faker
  composer.json
  src/CoreShop/Bundle/CoreBundle/composer.json
Labels: bug

#1773 [Store select / multiselect] Support getOptions() via option provider
  src/CoreShop/Bundle/StoreBundle/CoreExtension/Store.php
  src/CoreShop/Bundle/StoreBundle/CoreExtension/StoreMultiselect.php
  src/CoreShop/Bundle/StoreBundle/CoreExtension/StoreOptionProvider.php
  src/CoreShop/Bundle/StoreBundle/Resources/config/services.yml
Labels: enhancement

#1769 [Index] remove dbal connection in AbstractListing
  src/CoreShop/Bundle/IndexBundle/Worker/AbstractListing.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
  src/CoreShop/Component/Index/Listing/ListingInterface.php
Labels: bug

#1776 [ResourceBundle] allow easier custom resources
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/CoreShopResourceExtension.php
Labels: enhancement

#1777 [ThemeBundle] remove sylius theme-aware-translator, that doesn't work well with Pimcore
  src/CoreShop/Bundle/ThemeBundle/CoreShopThemeBundle.php
  src/CoreShop/Bundle/ThemeBundle/DependencyInjection/Compiler/RemoveThemeAwareTranslatorPass.php
Labels: bug

#1778 [ThemeBundle] refactor theme-context to work with area-bricks
  src/CoreShop/Bundle/StoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ThemeBundle/Context/ThemeContext.php
  src/CoreShop/Bundle/ThemeBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ThemeBundle/Resources/pimcore/config.yml
  src/CoreShop/Bundle/ThemeBundle/Service/PimcoreDocumentPropertyResolver.php
  src/CoreShop/Bundle/ThemeBundle/Service/PimcoreSiteThemeResolver.php
  src/CoreShop/Bundle/ThemeBundle/Service/ThemeResolverInterface.php
  src/CoreShop/Component/Store/Context/RequestBased/PimcoreAreaBrickRenderResolver.php
Labels: bug, BC break

#1780 [User] remove md5 password and use password_hash
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopUserBundle/CoreShopUser.json
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomer.json
  src/CoreShop/Bundle/UserBundle/Resources/install/pimcore/classes/CoreShopUser.json
Labels: bug

#1782 fix: make IndexProcess compatible with the interface
  src/CoreShop/Bundle/IndexBundle/ProcessManager/IndexProcess.php
Labels: bug

#1783 [CoreBundle] fix saving stores in PaymentProvider
  src/CoreShop/Bundle/CoreBundle/Form/Extension/PaymentProviderTypeExtension.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/form_extension.yml
Labels: bug

#1785 fix: Error when creating new order manually
  src/CoreShop/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
Labels: bug

#1790 [Index] make ListingInterface a Pimcore PaginateListingInterface
  src/CoreShop/Bundle/IndexBundle/Worker/AbstractListing.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
  src/CoreShop/Bundle/OrderBundle/Context/SessionAndStoreBasedCartContext.php
  src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php
  src/CoreShop/Component/Index/Listing/ListingInterface.php
Labels: bug

#1791 After renaming formtypes with coreshop[], form elements where not fou…
  src/CoreShop/Bundle/FrontendBundle/Resources/public/static/js/shop.js
Labels: bug

#1792 [Installer] use settings-store-aware installer
  src/CoreShop/Bundle/CoreBundle/Installer.php
Labels: enhancement

#1793 [CustomerBundle] move RoleOptionsProvider from User to Customer Bundle
  src/CoreShop/Bundle/CustomerBundle/CoreExtension/Provider/RoleOptionsProvider.php
Labels: bug

#1796 [JMS] Update to 4.x bundle
  composer.json
  src/CoreShop/Bundle/ResourceBundle/composer.json
Labels: enhancement

#1795 [IndexBundle] fix for range conditions
  src/CoreShop/Behat/Context/Setup/IndexConditionContext.php
  src/CoreShop/Bundle/IndexBundle/Condition/Mysql/RangeRenderer.php
  src/CoreShop/Component/Index/Condition/RangeCondition.php
  src/CoreShop/Component/Index/Filter/RangeFilterConditionProcessor.php
Labels: bug

#1794 [Index] remove setCategory from IndexInterface
  src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
  src/CoreShop/Bundle/IndexBundle/Worker/AbstractListing.php
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
  src/CoreShop/Component/Index/Listing/ListingInterface.php
Labels: BC break

#1797 [Tracking] Composite increase performance
  src/CoreShop/Component/Tracking/Tracker/CompositeTracker.php
Labels: enhancement

#1770 [CoreExtensions] refactor how Doctrine Entities are cloned
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/product.yml
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
  src/CoreShop/Component/Core/Model/ProductInterface.php
  src/CoreShop/Component/Core/Model/ProductStoreValues.php
  src/CoreShop/Component/Core/Model/QuantityRange.php
  src/CoreShop/Component/Core/Product/Cloner/ProductQuantityPriceRulesCloner.php
  src/CoreShop/Component/Core/Product/Cloner/ProductUnitDefinitionsCloner.php
  src/CoreShop/Component/Core/Product/Cloner/UnitMatcher.php
  src/CoreShop/Component/Core/Product/Cloner/UnitMatcherInterface.php
  src/CoreShop/Component/Pimcore/BCLayer/CustomDataCopyInterface.php
  src/CoreShop/Component/Product/Model/ProductSpecificPriceRule.php
  src/CoreShop/Component/Product/Model/ProductUnitDefinition.php
  src/CoreShop/Component/Product/Model/ProductUnitDefinitions.php
  src/CoreShop/Component/ProductQuantityPriceRules/Model/ProductQuantityPriceRule.php
  src/CoreShop/Component/ProductQuantityPriceRules/Model/QuantityRange.php
  src/CoreShop/Component/Resource/Pimcore/Model/PimcoreModelInterface.php
  src/CoreShop/Component/Rule/Model/Condition.php
Labels: bug

#1800 fixes #1699 cart context returns latest cart even if multiple found
  src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/CartRepository.php
  src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php
Labels: bug

#1802 [PimcoreBundle] add coreshop:migration:migrate and coreshop:migration:generate
  src/CoreShop/Bundle/PimcoreBundle/Command/AppMigrateCommand.php
  src/CoreShop/Bundle/PimcoreBundle/Command/AppMigrationGenerateCommand.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
Labels: enhancement
