Repository coreshop/CoreShop, pull requests merged in 2021-06, with the labels that each got.

#1648 [FrontendBundle] fix having unique form-ids for cart add
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
Labels: bug

#1643 [IndexBundle] Add missing process conditions in docs
  docs/02_Bundles/Index_Bundle.md
Labels: docs

#1649 [Core] fix cloning and serializing (with DeepCopy) of UnitDefinitions…
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/security.yml
  src/CoreShop/Component/Core/Product/Cloner/ProductQuantityPriceRulesCloner.php
  src/CoreShop/Component/Core/Product/Cloner/ProductUnitDefinitionsCloner.php
  src/CoreShop/Component/Product/Model/ProductUnitDefinition.php
  src/CoreShop/Component/Rule/Model/Condition.php
Labels: bug

#1655 [IndexBundle] fix SelectFilterConditionFromMultiselectProcessor class
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/EventListener/BodyListener.php
  src/CoreShop/Component/Customer/Model/Customer.php
  src/CoreShop/Component/Customer/Model/CustomerInterface.php
  src/CoreShop/Component/Index/Filter/SelectFilterConditionFromMultiselectProcessor.php
Labels: bug

#1653 [ThemeBundle] fix loading of theme when in Pimcore Admin
  src/CoreShop/Bundle/ThemeBundle/Context/ThemeContext.php
  src/CoreShop/Bundle/ThemeBundle/Resources/config/services.yml
Labels: bug

#1645 Fix Firewall for URL path /
  config/packages/security.yaml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/security.yml
Labels: enhancement

#1652 [ResourceBundle] fix height for coreShopRelations type
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCompany.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCustomer.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderShipment.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomer.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderInvoice.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderShipment.json
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopProduct.json
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/coreExtension/data/coreShopRelation.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/coreExtension/data/coreShopRelations.js
Labels: bug

#1656 [Tracking] enable auto-configuration and auto-wiring with configuration
  src/CoreShop/Bundle/TrackingBundle/DependencyInjection/CoreShopTrackingExtension.php
Labels: bug

#1660 [Profiling] disable coreshop profiles in backend
  src/CoreShop/Bundle/AddressBundle/Collector/CountryCollector.php
  src/CoreShop/Bundle/AddressBundle/Resources/config/services/profiler.yml
  src/CoreShop/Bundle/CoreBundle/Collector/CurrencyCollector.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/profiler.yml
  src/CoreShop/Bundle/StoreBundle/Collector/StoreCollector.php
  src/CoreShop/Bundle/StoreBundle/DependencyInjection/CoreShopStoreExtension.php
  src/CoreShop/Bundle/StoreBundle/Resources/config/services/profiler.yml
Labels: enhancement
