Repository coreshop/CoreShop, pull requests merged in 2021-01, with the labels that each got.

#1551 add docu for product units
  docs/02_Components/Product_Unit.md
Labels: docs

#1554 [ResourceBundle] fix object-manager
  src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php
Labels: bug

#1556 [PimcoreBundle] fix sorting for DynamicDropdown
  src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php
Labels: bug

#1553 [Release] 2.2.7
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1558 [OptimisticEntityLockBundle] fix Version loading with Composer v3
  src/CoreShop/Bundle/OptimisticEntityLockBundle/CoreShopOptimisticEntityLockBundle.php
Labels: bug

#1559 [Release] 2.2.8
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1565 fix decoration
  src/CoreShop/Bundle/StoreBundle/Resources/config/services.yml
Labels: bug

#1568 [Mailer] remove usages of PimcoreBundle\MailerInterface and fix inter…
  src/CoreShop/Bundle/CoreBundle/Order/OrderMailProcessor.php
  src/CoreShop/Bundle/PimcoreBundle/Mail/MailProcessorInterface.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
Labels: bug

#1567 [Resource] Provide Pimcore driver for Stack Repository
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackRepositoryPass.php
Labels: bug

#1561 [Admin] use form.Panel instead of form.FieldSet (panel supports isDirty)
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/actions/storeMail.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/actions/price.js
Labels: enhancement

#1566 [ResourceBundle] check if instance is null before calling class_implements
  src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepository.php
Labels: bug

#1569 use full unit definition label in choice field
  src/CoreShop/Bundle/ProductBundle/Form/Type/Unit/ProductUnitDefinitionsChoiceType.php
Labels: bug

#1578 [Models] strict defining of model trait methods
  src/CoreShop/Component/Address/Model/Country.php
  src/CoreShop/Component/Address/Model/State.php
  src/CoreShop/Component/Product/Model/ProductUnit.php
  src/CoreShop/Component/Taxation/Model/TaxRate.php
Labels: enhancement

#1577 [OptimisticEntityLockBundle] fix version for Pimcore Extensions UI
  src/CoreShop/Bundle/OptimisticEntityLockBundle/CoreShopOptimisticEntityLockBundle.php
Labels: bug

#1576 [All] replace all usages of href with manyToOneRelation and multihref with manyToManyRelation
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCustomer.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopCart.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderShipment.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuote.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
  src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomer.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopCart.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderInvoice.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderInvoiceItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderItem.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderShipment.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuote.json
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/grid-config.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopSuperBoxSelect.js
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopProduct.json
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/object/elementHref.js
Labels: bug

#1580 [ResourceBundle] fix compatibility with Doctrine EventSubscriber
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/DoctrineTargetEntitiesResolverPass.php
Labels: bug

#1581 [Release] 2.2.9
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE
