Repository coreshop/CoreShop, pull requests merged in 2022-03, with the labels that each got.

#1879 [CurrencyBundle] fix exchange rate saving/deleting
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/exchangeRate/panel.js
Labels: bug

#1881 [Psalm] fix tests
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterIndexProductExtensionPass.php
  src/CoreShop/Bundle/FrontendBundle/DependencyInjection/CompilerPass/RegisterFrontendControllerPass.php
  src/CoreShop/Bundle/IndexBundle/Controller/IndexController.php
  src/CoreShop/Bundle/NotificationBundle/Controller/NotificationRuleController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
  src/CoreShop/Bundle/ResourceBundle/Controller/ResourceSettingsController.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/CoreShopRelation.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/CoreShopRelations.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterPimcoreResourcesPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterResourcesPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackClassesPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackRepositoryPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/CoreShopResourceExtension.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Driver/Pimcore/PimcoreDriver.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Extension/AbstractModelExtension.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreClassInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDependantBundleInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDocumentsInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreGridConfigInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreImageThumbnailsInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcorePermissionInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreRoutesInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/SqlInstaller.php
  src/CoreShop/Bundle/ShippingBundle/Controller/CarrierController.php
Labels: tests

#1883 FIX: coreshop_payment_provider editable select, wrong property name
  src/CoreShop/Bundle/PaymentBundle/Resources/config/services/pimcore.yml
Labels: bug

#1880 FIX: select from multiselect throws error if no value is pre-selected
  src/CoreShop/Component/Index/Filter/SelectFilterConditionFromMultiselectProcessor.php
Labels: bug

#1884 [ThemeBundle] improve loading theme when document cannot be loaded
  src/CoreShop/Bundle/ThemeBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ThemeBundle/Service/PimcoreDocumentPropertyResolver.php
Labels: bug

#1887 [ResourceBundle] fix entity-merger to delete collection entries
  src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php
Labels: bug

#1888 [ProductBundle] fix translations
  src/CoreShop/Bundle/ProductBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/ProductBundle/Resources/translations/admin.en.yml
Labels: bug

#1892 [IndexBundle] fixed issue 1891, fix totalCount for pagination
  src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
Labels: bug

#1893 Email field required on request reset password form
  src/CoreShop/Bundle/UserBundle/Form/Type/RequestResetPasswordType.php
Labels: bug

#1890 Category select template fix
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_category_select.html.twig
Labels: bug

#1899 FEATURE: category multiselect
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_category_multiselect.html.twig
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionCategoryMultiSelectType.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/css/index.css
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/category_multiselect.js
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Index/Filter/CategoryMultiSelectConditionProcessor.php
Labels: enhancement, new feature

#1900 FIX: extending condition proccesor adds empty tag
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterFilterConditionTypesPass.php
Labels: bug, enhancement

#1903 Error during serialization of OrderInvoice
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.OrderInvoice.yml
Labels: bug

#1902 [CoreBundle] don't load settings if user has no permission
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
Labels: bug

#1904 Generating invoice PDF fix
  src/CoreShop/Bundle/OrderBundle/Renderer/OrderDocumentPdfRenderer.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/controller.yml
Labels: bug

#1905 Fixed invoice, payment, shipment state condition in notifications
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/invoice/invoiceState.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/payment/paymentState.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/shipment/shipmentState.js
Labels: bug

#1910 Removed free shipping checkbog from carrier
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/CarrierFixture.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20220315131030.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/CarrierType.php
  src/CoreShop/Bundle/ShippingBundle/Resources/config/doctrine/model/Carrier.orm.xml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/serializer/Model.Carrier.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/validation/Carrier.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/carrier/item.js
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.it.yml
  src/CoreShop/Component/Shipping/Model/Carrier.php
  src/CoreShop/Component/Shipping/Model/CarrierInterface.php
Labels: enhancement

#1894 FIX: duplicated unit definition title in product view in admin
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductUnitDefinitions.js
Labels: enhancement

#1911 Fix xvfb error
  src/CoreShop/Bundle/OrderBundle/Renderer/Pdf/WkHtmlToPdf.php
Labels: bug

#1923 fix: paginator prev/next links point to first/last page
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/paginator.html.twig
Labels: bug

#1889 [Conversion] fix currency conversion
  src/CoreShop/Component/Core/Context/ShopperContext.php
  src/CoreShop/Component/Core/ProductQuantityPriceRules/Rule/Action/AmountDecreaseAction.php
  src/CoreShop/Component/Core/ProductQuantityPriceRules/Rule/Action/AmountIncreaseAction.php
  src/CoreShop/Component/Core/ProductQuantityPriceRules/Rule/Action/FixedAction.php
  src/CoreShop/Component/Core/Shipping/Rule/Action/AdditionAmountActionProcessor.php
  src/CoreShop/Component/Core/Shipping/Rule/Action/DiscountAmountActionProcessor.php
  src/CoreShop/Component/Core/Shipping/Rule/Action/PriceActionProcessor.php
  src/CoreShop/Component/Order/Calculator/PurchasableWholesalePriceCalculator.php
  src/CoreShop/Component/Order/Cart/CartContextResolver.php
  src/CoreShop/Component/Product/Rule/Action/DiscountAmountActionProcessor.php
  src/CoreShop/Component/Product/Rule/Action/DiscountPriceActionProcessor.php
  src/CoreShop/Component/Product/Rule/Action/PriceActionProcessor.php
Labels: bug

#1919 [FrontendBundle] fix configuration for controller names
  src/CoreShop/Bundle/FrontendBundle/DependencyInjection/CompilerPass/RegisterFrontendControllerPass.php
Labels: bug

#1918 [ThemeHelper] check if theme is not null before setting
  src/CoreShop/Bundle/ThemeBundle/Service/ThemeHelper.php
Labels: bug

#1925 [IndexBundle] don't lower-case interpreter types
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/iterator.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nested.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nestedlocalized.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nestedrelational.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/objectproperty.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/objecttype/abstract.js
Labels: bug

#1909 Category multiselect filter condition.
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionCategoryMultiSelectType.php
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/abstract.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/category_multiselect.js
  src/CoreShop/Component/Index/Filter/CategoryMultiSelectConditionProcessor.php
Labels: enhancement

#1927 [PimcoreBundle] make command "coreshop:app:migration:generate" not hidden
  src/CoreShop/Bundle/PimcoreBundle/Command/AppMigrationGenerateCommand.php
Labels: enhancement

#1928 [Installer] mark migrations as migrated in the installer
  src/CoreShop/Bundle/CoreBundle/Command/InstallCommand.php
  src/CoreShop/Bundle/CoreBundle/Installer.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/commands.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/pimcore_installer.yml
Labels: bug

#1926 [IndexBundle] fix saving quantity values for index conditions
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20220323072817.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/doctrine/model/FilterCondition.orm.xml
  src/CoreShop/Bundle/IndexBundle/Resources/config/serializer/Model.FilterCondition.yml
  src/CoreShop/Component/Index/Filter/BooleanFilterConditionProcessor.php
  src/CoreShop/Component/Index/Filter/MultiselectFilterConditionFromMultiselectProcessor.php
  src/CoreShop/Component/Index/Filter/MultiselectFilterConditionProcessor.php
  src/CoreShop/Component/Index/Filter/RangeFilterConditionProcessor.php
  src/CoreShop/Component/Index/Filter/RelationalMultiselectConditionProcessor.php
  src/CoreShop/Component/Index/Filter/RelationalSelectConditionProcessor.php
  src/CoreShop/Component/Index/Filter/SelectFilterConditionFromMultiselectProcessor.php
  src/CoreShop/Component/Index/Filter/SelectFilterConditionProcessor.php
  src/CoreShop/Component/Index/Model/FilterCondition.php
  src/CoreShop/Component/Index/Model/FilterConditionInterface.php
Labels: bug

#1924 Search filter
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_search.html.twig
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionSearchType.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/css/index.css
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/img/filter-search.svg
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/search.js
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Index/Filter/SearchConditionProcessor.php
Labels: enhancement

#1930 [NotificationBundle] fix reloading of Notification Conditions/Actions
  src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/rule/action.js
  src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/rule/condition.js
Labels: bug

#1931 [Permissions] fix menu for permissions and add missing Settings Permission
  src/CoreShop/Bundle/CoreBundle/Controller/SettingsController.php
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20220324073343.php
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/translations/admin.de.yaml
  src/CoreShop/Bundle/CustomerBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
Labels: bug

#1932 [Slug] fallback to ID if nameForSlug is null
  src/CoreShop/Component/Pimcore/Slug/SluggableInterface.php
  src/CoreShop/Component/Pimcore/Slug/SluggableSlugger.php
Labels: bug

#1901 [Stan] fix tests
  .github/workflows/behat.yml
  .gitignore
  composer.json
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterIndexProductExtensionPass.php
  src/CoreShop/Bundle/FrontendBundle/DependencyInjection/CompilerPass/RegisterFrontendControllerPass.php
  src/CoreShop/Bundle/IndexBundle/Controller/IndexController.php
  src/CoreShop/Bundle/NotificationBundle/Controller/NotificationRuleController.php
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
  src/CoreShop/Bundle/ResourceBundle/Controller/ResourceSettingsController.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterPimcoreResourcesPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterResourcesPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackClassesPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackRepositoryPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Driver/Pimcore/PimcoreDriver.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Extension/AbstractModelExtension.php
  src/CoreShop/Bundle/ResourceBundle/Installer/AbstractTranslationInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreClassInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDocumentsInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreGridConfigInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreImageThumbnailsInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcorePermissionInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreRoutesInstaller.php
  src/CoreShop/Bundle/ResourceBundle/Installer/SqlInstaller.php
  src/CoreShop/Bundle/ShippingBundle/Controller/CarrierController.php
Labels: enhancement

#1934 [ResourceBundle] fix creating static routes
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreRoutesInstaller.php
Labels: bug

#1935 [FrontendBundle] fix styling of reset-password-request submit button
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Register/password-reset-request.html.twig
Labels: bug

#1936 [ProductBundle] fix ProductUnitDefinition unmarshal
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php
Labels: bug

#1937 [Routing] fix route name coreshop_cart_create_quote
  src/CoreShop/Bundle/CoreBundle/Checkout/Step/SummaryCheckoutStep.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml
Labels: bug

#1938 Search filter dynamic name
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionSearchType.php
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/search.js
  src/CoreShop/Bundle/IndexBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Index/Filter/SearchConditionProcessor.php
Labels: enhancement

#1941 Profiler fix
  src/CoreShop/Bundle/CoreBundle/Collector/CurrencyCollector.php
Labels: bug

#1940 fix: PHP 8.1 deprecations
  src/CoreShop/Component/Registry/PriorityMap.php
Labels: bug

#1942 Fix redirect to profile if customer is present
  src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php
Labels: bug
