Repository coreshop/CoreShop, pull requests merged in 2022-04, with the labels that each got.

#1949 [MoneyBundle] allow Money to be nullable
  src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
  src/CoreShop/Bundle/MoneyBundle/Resources/public/pimcore/js/coreExtension/data/coreShopMoney.js
Labels: enhancement

#1950 Add submit buttons for voucher submit and form update in cart form
  src/CoreShop/Bundle/CoreBundle/Form/Extension/CartTypeExtension.php
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_summary.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_update.html.twig
  src/CoreShop/Bundle/OrderBundle/Form/Type/CartType.php
Labels: enhancement

#1954 [NotificationBundle] fix saving multiple emails
  src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/rule/actions/mail.js
Labels: bug

#1955 [CoreBundle] fix ProductStoreValuesRepository return type
  src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/ProductStoreValuesRepository.php
  src/CoreShop/Component/Core/Repository/ProductStoreValuesRepositoryInterface.php
Labels: bug

#1956 [FrontendBundle] fix add gift product to cart
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_update.html.twig
Labels: bug

#1958 [Release] 3.0.0-beta.3
  CHANGELOG-3.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1962 [Store] add Store Resolver for document save from Pimcore Admin
  src/CoreShop/Bundle/AddressBundle/Form/Type/AddressIdentifierChoiceType.php
  src/CoreShop/Bundle/AddressBundle/Form/Type/CountryChoiceType.php
  src/CoreShop/Bundle/AddressBundle/Form/Type/StateChoiceType.php
  src/CoreShop/Bundle/AddressBundle/Form/Type/ZoneChoiceType.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/AddressChoiceType.php
  src/CoreShop/Bundle/ResourceBundle/Controller/ResourceController.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/CarrierChoiceType.php
  src/CoreShop/Bundle/ShippingBundle/Form/Type/ShippingRuleChoiceType.php
  src/CoreShop/Bundle/StoreBundle/Form/Type/StoreChoiceType.php
  src/CoreShop/Bundle/TaxationBundle/Form/Type/TaxRateChoiceType.php
  src/CoreShop/Bundle/TaxationBundle/Form/Type/TaxRuleGroupChoiceType.php
  src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
  src/CoreShop/Component/Store/Context/RequestBased/PimcoreAdminSiteBasedRequestResolver.php
Labels: bug

#1965 [ResourceBundle] add feature to clone resources
  src/CoreShop/Bundle/IndexBundle/Form/Type/FilterType.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/item.js
  src/CoreShop/Bundle/ResourceBundle/Controller/ResourceController.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/CoreShopRelation.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/CoreShopRelations.php
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/helpers.js
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/item.js
  src/CoreShop/Bundle/ResourceBundle/Routing/Configuration.php
  src/CoreShop/Bundle/ResourceBundle/Routing/ResourceLoader.php
Labels: enhancement, new feature

#1967 [IndexBundle] fix Argument #2 ($values) must be of type array, string given
  src/CoreShop/Component/Index/Filter/MultiselectFilterConditionProcessor.php
  src/CoreShop/Component/Index/Filter/RelationalMultiselectConditionProcessor.php
Labels: bug

#1973 [CoreBundle] use themeHelper to resolve template in StoreMailActionPr…
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/notification.yml
  src/CoreShop/Component/Core/Notification/Rule/Action/Order/StoreMailActionProcessor.php
Labels: bug

#1977 [Condition] fix rules being active even if inactive when having no conditions
  src/CoreShop/Component/Rule/Condition/RuleConditionsValidationProcessor.php
Labels: bug
