Repository coreshop/CoreShop, pull requests merged in 2022-01, with the labels that each got.

#1830 add is_null in isNewEntity
  src/CoreShop/Component/Core/Customer/CustomerTransformHelper.php
Labels: bug

#1834 [IndexBundle] add boolean filter condition
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_boolean.html.twig
  src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionBooleanType.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/form.yml
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/boolean.js
  src/CoreShop/Component/Index/Filter/BooleanFilterConditionProcessor.php
Labels: new feature

#1833 [IndexBundle] add clear button for filter preSelect combos
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/multiselect.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/range.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/relational_multiselect.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/relational_select.js
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/select.js
Labels: new feature

#1836 [OrderBundle] fix session cart subscriber when no session is available
  src/CoreShop/Bundle/OrderBundle/EventListener/SessionCartSubscriber.php
Labels: bug

#1838 [ResourceBundle] fix resource list calling Pimcore Event and CoreShop Event to open object
  src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/list.js
Labels: bug

#1839 [Payment] fix for PayPal payment
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20220117153741.php
  src/CoreShop/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.xml
  src/CoreShop/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php
  src/CoreShop/Bundle/PayumBundle/Resources/config/services.yml
Labels: bug

#1840 Fix doctrine type in migration (followup of #1839)
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20220117153741.php
Labels: bug

#1845 [List] fix open CoreShop Entry and Pimcore DataObject
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/list.js
Labels: bug

#1843 [Cache] optimize Pimcore cache with doctrine entities
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php
  src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/PimcoreCachePass.php
  src/CoreShop/Bundle/ResourceBundle/EventListener/DeepCopyListener.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/CacheMarshallerInterface.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/CacheResourceMarshaller.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services/integrations/doctrine/orm.yml
Labels: bug

#1848 fix: Since symfony/http-kernel 5.1: Referencing controllers with a si…
  src/CoreShop/Bundle/FrontendBundle/Resources/views/layout-column.html.twig
Labels: bug

#1847 [IndexBundle] Migrate to SettingsStoreAwareInstaller
  src/CoreShop/Bundle/IndexBundle/Installer.php
  src/CoreShop/Bundle/IndexBundle/Migrations/Version20220121154623.php
Labels: enhancement

#1851 [Theme] fallback to SettableThemeContext
  src/CoreShop/Bundle/ThemeBundle/Context/ThemeContext.php
  src/CoreShop/Bundle/ThemeBundle/Resources/config/services.yml
Labels: bug
