Repository coreshop/CoreShop, pull requests merged in 2022-09, with the labels that each got.

#2065 [Pimcore UI] Make default Product Unit unselectable
  src/CoreShop/Bundle/ProductBundle/Controller/ProductUnitDefinitionsController.php
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductUnitDefinitions.js
  src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/units/builder.js
Labels: bug

#2072 [Bundle] adapt version number display
  src/CoreShop/Bundle/CoreBundle/CoreShopCoreBundle.php
  src/CoreShop/Bundle/CustomerBundle/CoreShopCustomerBundle.php
  src/CoreShop/Bundle/FrontendBundle/CoreShopFrontendBundle.php
  src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
  src/CoreShop/Bundle/MenuBundle/CoreShopMenuBundle.php
  src/CoreShop/Bundle/OptimisticEntityLockBundle/CoreShopOptimisticEntityLockBundle.php
  src/CoreShop/Bundle/PayumPaymentBundle/CoreShopPayumPaymentBundle.php
  src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
  src/CoreShop/Bundle/ResourceBundle/AbstractResourceBundle.php
  src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
  src/CoreShop/Bundle/SEOBundle/CoreShopSEOBundle.php
  src/CoreShop/Bundle/TestBundle/CoreShopTestBundle.php
  src/CoreShop/Bundle/ThemeBundle/CoreShopThemeBundle.php
Labels: enhancement

#2076 [PayumPaymentBundle] fix event based payment provider resolver
  src/CoreShop/Bundle/PayumPaymentBundle/Resources/config/services/payment.yml
Labels: bug

#2077 [PayumBundle] use Symfony PSR18Client instead of Guzzle 6
  src/CoreShop/Bundle/PayumBundle/Resources/config/services.yml
Labels: bug

#2070 [Release] 3.0.0
  CHANGELOG-3.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2084 [Wishlist] add tests and fix routing
  features/ui/frontend/wishlist/adding_product_to_wishlist.feature
  features/ui/frontend/wishlist/remove_product_from_wishlist.feature
  src/CoreShop/Behat/Context/Ui/Frontend/WishlistContext.php
  src/CoreShop/Behat/Page/Frontend/ProductPage.php
  src/CoreShop/Behat/Page/Frontend/ProductPageInterface.php
  src/CoreShop/Behat/Page/Frontend/WishlistPage.php
  src/CoreShop/Behat/Page/Frontend/WishlistPageInterface.php
  src/CoreShop/Behat/Resources/config/services/contexts/ui.yml
  src/CoreShop/Behat/Resources/config/services/pages.yml
  src/CoreShop/Behat/Resources/config/suites/ui.yml
  src/CoreShop/Behat/Resources/config/suites/ui/wishlist.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/_addToWishlist.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Wishlist/summary.html.twig
Labels: bug
