Repository coreshop/CoreShop, pull requests merged in 2022-02, with the labels that each got.

#1855 Password reset: Clearer form labels
  src/CoreShop/Bundle/CustomerBundle/Form/Type/ResetPasswordType.php
Labels: enhancement

#1857 [PimcoreBundle] added SluggableSlugger for SluggableListener
  src/CoreShop/Bundle/PimcoreBundle/EventListener/SluggableListener.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
  src/CoreShop/Component/Pimcore/Exception/SlugNotPossibleException.php
  src/CoreShop/Component/Pimcore/Slug/SluggableSlugger.php
  src/CoreShop/Component/Pimcore/Slug/SluggableSluggerInterface.php
Labels: new feature

#1858 [Pimcore] Definition Updater: check if we should use 'childs' or 'children'
  src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php
  src/CoreShop/Component/Pimcore/DataObject/AbstractDefinitionUpdate.php
  src/CoreShop/Component/Pimcore/DataObject/BrickDefinitionUpdate.php
  src/CoreShop/Component/Pimcore/DataObject/ClassUpdate.php
  src/CoreShop/Component/Pimcore/DataObject/ClassUpdateInterface.php
  src/CoreShop/Component/Pimcore/DataObject/FieldCollectionDefinitionUpdate.php
Labels: bug

#1863 [Core] address assignment manager should check for null
  src/CoreShop/Component/Core/Customer/Address/AddressAssignmentManager.php
Labels: bug

#1862 [IndexBundle] decimal should be 10,2
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Component/Index/Extension/DecimalIndexColumnTypeConfigExtension.php
Labels: bug

#1861 [IndexBundle] QuantityValue ID's are strings
  src/CoreShop/Bundle/IndexBundle/Form/Type/FilterConditionType.php
Labels: bug

#1867 [Taxation] add taxRate to TaxItemInterface
  src/CoreShop/Bundle/TaxationBundle/CoreExtension/TaxRate.php
  src/CoreShop/Bundle/TaxationBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/TaxationBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/TaxationBundle/Resources/install/pimcore/fieldcollections/CoreShopTaxItem.json
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/css/taxation.css
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/coreExtension/data/coreShopTaxRate.js
  src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopTaxRate.js
  src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
  src/CoreShop/Component/Taxation/Collector/TaxCollector.php
  src/CoreShop/Component/Taxation/Model/TaxItemInterface.php
Labels: enhancement

#1868 [CoreBundle] fix quote notification sending
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/QuoteListener.php
Labels: bug

#1869 [CoreBundle] fix quote notification sending 3.x
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/OrderWorkflowListener.php
  src/CoreShop/Bundle/CoreBundle/Form/Type/Notification/Condition/OrderSaleStateConfigurationType.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/notification.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/order/saleState.js
Labels: bug

#1870 [FrontendBundle] fix createQuoteAction
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/image-thumbnails.yml
  src/CoreShop/Component/Core/Order/Committer/OrderCommitter.php
  src/CoreShop/Component/Core/Order/Committer/QuoteCommitter.php
Labels: bug

#1844 Add isEqual() for product-specific price rules
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
  src/CoreShop/Component/Pimcore/BCLayer/EqualComparisonInterface.php
Labels: enhancement

#1874 Fix Version20190605141526
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20190605141526.php
Labels: bug

#1877 [CoreBundle] fix user-reset password notification sending
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/CustomerListener.php
Labels: bug
