Repository coreshop/CoreShop, pull requests merged in 2022-05, with the labels that each got.

#1979 Handle `null` addresses when persisting customers
  src/CoreShop/Bundle/CoreBundle/Customer/CustomerManager.php
Labels: bug

#1981 [ResourceBundle] fix ResourceSettingsController getConfigAction
  src/CoreShop/Bundle/ResourceBundle/Controller/ResourceSettingsController.php
Labels: bug

#1980 [CoreBundle] fix registered user validator
  src/CoreShop/Bundle/CoreBundle/Validator/Constraints/RegisteredUserValidator.php
Labels: bug

#1982 [Release] 2.2.13
  CHANGELOG-2.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#1984 fix: wiring non-existing User classes which were migrated to Customer…
  src/CoreShop/Bundle/CustomerBundle/Resources/config/services/form.yml
Labels: bug

#1988 Fix Typo in notifcation.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/notification.yml
Labels: bug

#1989 FIX grid view for orders/quotes/carts in admin
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/list.js
Labels: bug

#1991 remove variable variables sign
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
Labels: bug

#1992 Fix for order grid configs
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/grid-config.yml
Labels: bug

#1978 [Taxation] pass context into TaxCalculatorFactory
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/CoreBundle/Twig/ProductQuantityPriceRuleRangesPriceExtension.php
  src/CoreShop/Bundle/CoreBundle/Twig/ProductTaxExtension.php
  src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php
  src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartTaxProcessor.php
  src/CoreShop/Component/Core/Product/ProductTaxCalculatorFactory.php
  src/CoreShop/Component/Core/Product/ProductTaxCalculatorFactoryInterface.php
  src/CoreShop/Component/Core/Product/TaxedProductPriceCalculator.php
  src/CoreShop/Component/Core/Shipping/Calculator/TaxedCarrierPriceRuleCalculator.php
  src/CoreShop/Component/Core/Shipping/Taxation/TaxCalculationStrategyCartItems.php
  src/CoreShop/Component/Core/Shipping/Taxation/TaxCalculationStrategyTaxRule.php
  src/CoreShop/Component/Core/Taxation/CachedTaxCalculatorFactory.php
  src/CoreShop/Component/Core/Taxation/TaxCalculatorFactory.php
  src/CoreShop/Component/Core/Taxation/TaxCalculatorFactoryInterface.php
  src/CoreShop/Component/Shipping/Taxation/TaxCalculationStrategyInterface.php
Labels: enhancement, new feature

#1994 [CoreBundle] use TaxationDisplayProvider in CarrierChoiceType
  src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/CarrierChoiceType.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/checkout.yml
Labels: enhancement

#1993 FIX newsletter double opt in mail not sending
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/CustomerListener.php
Labels: bug

#1995 [CoreBundle] added newline before phoneNumber in CountryFixture
  src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php
Labels: bug

#1997 [CoreBundle] fix variant js, added variant select template
  src/CoreShop/Bundle/FrontendBundle/Resources/public/static/js/plugin/coreshop.plugin.variant.js
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/_variants.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/attributes/detail/_select.html.twig
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/attributes/detail/_text.html.twig
Labels: bug

#1999 [Checkout] change thank-you to work with token and fix strict samesite cookies
  src/CoreShop/Behat/Page/Frontend/Checkout/ThankYouPage.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20220509091354.php
  src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/error.html.twig
  src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php
  src/CoreShop/Bundle/PayumBundle/Action/Offline/ResolveNextRouteAction.php
  src/CoreShop/Bundle/PayumBundle/Action/ResolveNextRouteAction.php
  src/CoreShop/Bundle/PayumBundle/Controller/PaymentController.php
  src/CoreShop/Component/Order/Repository/OrderRepositoryInterface.php
Labels: enhancement, new feature, BC break

#1996 [Variant] add concrete return type to ui configuration
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/coreExtension/data/coreShopRelation.js
  src/CoreShop/Bundle/ResourceBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/translations/admin.en.yml
Labels: enhancement

#2000 [CoreBundle] fix event listeners for variants
  src/CoreShop/Bundle/VariantBundle/EventListener/MainVariantListener.php
  src/CoreShop/Bundle/VariantBundle/EventListener/ProductListener.php
Labels: bug

#2002 [Rule] use tags for TraceableRuleConditionsValidationProcessor
  src/CoreShop/Bundle/NotificationBundle/Resources/config/services.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/services/price-rules.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/services/specific-price-rules.yml
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/services/product-quantity-price-rules.yml
  src/CoreShop/Bundle/RuleBundle/DependencyInjection/Compiler/TraceableValidationProcessorPass.php
  src/CoreShop/Bundle/RuleBundle/DependencyInjection/CoreShopRuleExtension.php
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services/shipping-rules.yml
Labels: enhancement

#1915 feat: use the index for categories to allow fine tuning the menus
  src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/CategoryRepository.php
Labels: enhancement
