Repository coreshop/CoreShop, pull requests merged in 2022-11, with the labels that each got.

#2102 [CustomerAssignment] Fix typo when passing the company ID to the router
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/customer/customerToExistingCompanyAssignment.js
Labels: bug

#2111 [Checkout] introduce Payment Provider Validator to check if the selected one is still valid
  src/CoreShop/Bundle/CoreBundle/Checkout/Step/PaymentCheckoutStep.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/checkout.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/config/services/resolver.yml
  src/CoreShop/Component/Payment/Validator/PaymentProviderValidator.php
  src/CoreShop/Component/Payment/Validator/PaymentProviderValidatorInterface.php
Labels: bug

#2106 [IndexBundle] process Index Messages async
  config/packages/test/config.yaml
  src/CoreShop/Behat/Context/Setup/PimcoreClassContext.php
  src/CoreShop/Bundle/IndexBundle/EventListener/IndexObjectListener.php
  src/CoreShop/Bundle/IndexBundle/Messenger/Handler/IndexMessageHandler.php
  src/CoreShop/Bundle/IndexBundle/Messenger/IndexMessage.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/messenger.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/listeners.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/messenger.yml
Labels: enhancement

#2097 [ResourceBundle] class names with lower-case names
  src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CustomerBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ResourceBundle/Controller/ResourceSettingsController.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackClassesPass.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/WishlistBundle/DependencyInjection/Configuration.php
Labels: bug

#2112 [MessengerBundle] fixes
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/messenger.yml
  src/CoreShop/Bundle/MessengerBundle/Controller/ListMessagesController.php
  src/CoreShop/Bundle/MessengerBundle/Controller/MessageController.php
  src/CoreShop/Bundle/NotificationBundle/Resources/config/pimcore/messenger.yml
Labels: bug

#2113 [StorageList] fix storage-list priority
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
Labels: bug

#2116 [CartPiceRules] fix OrderItem not finding Order with CartItemPriceRules
  src/CoreShop/Component/Core/Order/Committer/OrderCommitter.php
  src/CoreShop/Component/Core/Order/Committer/QuoteCommitter.php
Labels: bug

#2119 [Release] 3.0.2
  CHANGELOG-3.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2125 feat: keep a reference to the just-removed Product
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
  src/CoreShop/Bundle/StorageListBundle/Controller/StorageListController.php
Labels: enhancement

#2127 [MessengerBundle] only allow to list ListableReceiverInterface
  src/CoreShop/Bundle/MessengerBundle/Controller/ListMessagesController.php
  src/CoreShop/Bundle/MessengerBundle/Exception/ReceiverNotListableException.php
  src/CoreShop/Bundle/MessengerBundle/Messenger/FailedMessageRejecter.php
  src/CoreShop/Bundle/MessengerBundle/Messenger/FailedMessageRepository.php
  src/CoreShop/Bundle/MessengerBundle/Messenger/FailedMessageRetryer.php
  src/CoreShop/Bundle/MessengerBundle/Messenger/MessageRepository.php
  src/CoreShop/Bundle/MessengerBundle/Messenger/ReceiversRepository.php
  src/CoreShop/Bundle/MessengerBundle/Messenger/ReceiversRepositoryInterface.php
  src/CoreShop/Bundle/MessengerBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/MessengerBundle/Resources/public/pimcore/js/list.js
Labels: bug

#2130 [MessengerBundle] standalone fixes
  src/CoreShop/Bundle/MessengerBundle/CoreShopMessengerBundle.php
  src/CoreShop/Bundle/MessengerBundle/Resources/public/pimcore/js/resource.js
Labels: bug

#2138 [MoneyBundle] fix issue with not-nullable types and null values
  src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
Labels: bug

#2140 [Resource] add return types for BigIntIntegerType
  src/CoreShop/Component/Resource/Doctrine/Type/BigIntIntegerType.php
Labels: enhancement

#2143 [LinkGeneration] introduce possibility to disable slugs and use fallb…
  config/config.yaml
  src/CoreShop/Bundle/CoreBundle/Pimcore/LinkGenerator/ResourceConfigurationLinkGenerator.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/routing.yml
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopCategory.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml
  src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/LinkGeneratorPass.php
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/link_generator.yaml
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopCategory.json
  src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopProduct.json
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/Slug/ResourceConfigurationSlugGenerator.php
  src/CoreShop/Bundle/VariantBundle/Resources/config/services.yml
  src/CoreShop/Component/Pimcore/DataObject/CompositeLinkGenerator.php
  src/CoreShop/Component/Pimcore/Exception/LinkGenerationNotPossibleException.php
  src/CoreShop/Component/Pimcore/Slug/SluggableLinkGenerator.php
  src/CoreShop/Component/Resource/Metadata/Registry.php
  src/CoreShop/Component/Resource/Metadata/RegistryInterface.php
Labels: enhancement

#2141 [Payum] use stable payum release
  composer.json
  src/CoreShop/Bundle/PayumBundle/composer.json
  src/CoreShop/Component/PayumPayment/composer.json
Labels: enhancement

#2137 fix: use asset() helper for logo image
  src/CoreShop/Bundle/OrderBundle/Resources/views/OrderDocumentPrint/header.html.twig
Labels: bug
