Repository coreshop/CoreShop, pull requests merged in 2023-11, with the labels that each got.

#2428 [StorageListBundle] make restore cart after checkout configurable
  features/ui/frontend/checkout/restore_old_cart_after_checkout.feature
  src/CoreShop/Behat/Resources/config/suites/ui/checkout.yml
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
  src/CoreShop/Component/StorageList/Core/Context/CustomerAndStoreBasedStorageListContext.php
Labels: enhancement

#2431 [OrderEdit] don't allow cancelled orders to be editable
  src/CoreShop/Component/Order/OrderEditPossible.php
Labels: enhancement

#2432 [Cart] fix wrong decoration of cart-context
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/context.yml
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
Labels: bug

#2440 add missing cast to (int) for $page variable
  src/CoreShop/Bundle/FrontendBundle/Controller/SearchController.php
Labels: bug

#2433 [Release] 3.1.4
  CHANGELOG-3.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2434 [Release] 3.2.0-beta.2
  CHANGELOG-3.1.x.md
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2435 [Release] 4.0.0-beta.4
  CHANGELOG-3.1.x.md
  CHANGELOG-3.2.x.md
  CHANGELOG-4.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2443 [ResourceBundle] remove request handler
  src/CoreShop/Bundle/ResourceBundle/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
Labels: enhancement

#2446 fix unit solidifier paths
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/workflow/variantUnitDefinitionSolidifier.js
Labels: bug

#2447 fix nested rule condition
  features/domain/product/price_rules/nested_not_condition.feature
  src/CoreShop/Behat/Context/Setup/ProductPriceRuleContext.php
  src/CoreShop/Component/Rule/Condition/NestedConditionChecker.php
Labels: bug

#2454 [ResourceBundle] fix custom resource registration
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/CoreShopResourceExtension.php
Labels: bug

#2449 [StorageListBundle] disable cache for StorageList and StorageListItem
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
  src/CoreShop/Bundle/StorageListBundle/EventListener/CacheListener.php
Labels: bug
