Repository coreshop/CoreShop, pull requests merged in 2023-12, with the labels that each got.

#2458 [CoreBundle] introduce Product Price Rule that is not combinable with Cart Price Voucher Rule
  composer.json
  features/ui/frontend/cart/voucher_code_not_combinable_with_cart_price_rule.feature
  src/CoreShop/Behat/Context/Setup/ProductPriceRuleContext.php
  src/CoreShop/Behat/Resources/config/suites/ui/cart.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/css/core.css
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/img/not_combinable.svg
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/pricerule/conditions/not_combinable.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/specificprice/conditions/not_combinable.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/OrderBundle/Controller/CartPriceRuleController.php
  src/CoreShop/Bundle/OrderBundle/Doctrine/ORM/CartPriceRuleRepository.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Component/Core/Product/Rule/Condition/NotCombinableWithCartPriceRuleVoucherConditionChecker.php
  src/CoreShop/Component/Order/Repository/CartPriceRuleRepositoryInterface.php
Labels: enhancement

#2464 [Core] Cart Item Discount Percent Gross Values
  features/domain/cart/rules/cart_item/discount_percent_gross_action.feature
  features/domain/cart/rules/cart_item/discount_percent_net_action.feature
  src/CoreShop/Component/Core/CartItem/Rule/Action/DiscountPercentActionProcessor.php
Labels: bug

#2470 [Core] defaultUnitQuantity should never be null
  src/CoreShop/Component/Core/Order/Modifier/CartItemQuantityModifier.php
Labels: bug

#2468 [PimcoreBundle] add cache.system to ExpressionLanguage
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
Labels: bug

#2475 [User] implement symfony "getUserIdentifier"
  src/CoreShop/Component/User/Model/User.php
Labels: bug

#2476 [StorageList] implement \Countable
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/_widget.html.twig
  src/CoreShop/Component/Order/Model/Order.php
  src/CoreShop/Component/StorageList/Model/StorageList.php
  src/CoreShop/Component/StorageList/Model/StorageListInterface.php
  src/CoreShop/Component/Wishlist/Model/Wishlist.php
Labels: enhancement

#2480 [FrontendBundle] check for isSubmitted before calling isValid
  src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php
Labels: bug

#2481 allow pending payments in checkout workflow
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_payment.yml
  src/CoreShop/Bundle/OrderBundle/StateResolver/OrderPaymentStateResolver.php
  src/CoreShop/Bundle/PayumBundle/Action/ConfirmOrderAction.php
  src/CoreShop/Bundle/PayumBundle/Action/ResolveNextRouteAction.php
  src/CoreShop/Bundle/PayumBundle/Extension/UpdateOrderStateExtension.php
Labels: enhancement

#2485 use null coalescing operator
  src/CoreShop/Component/Order/Cart/Rule/Condition/VoucherConditionChecker.php
Labels: bug

#2482 [Release] 3.1.5
  CHANGELOG-3.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2484 [Release] 4.0.0
  CHANGELOG-3.1.x.md
  CHANGELOG-3.2.x.md
  CHANGELOG-4.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2490 [Docs] Update docusaurus
  docs/composer.lock
  docs/docs/01_Getting_Started/02_Upgrade_Notes.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/themes/coreshop/config.json
  docs/themes/coreshop/css/coreshop-core.min.css
  docs/themes/coreshop/css/coreshop-generic.min.css
  docs/themes/coreshop/fonts/robotoslab-bold.eot
  docs/themes/coreshop/fonts/robotoslab-bold.svg
  docs/themes/coreshop/fonts/robotoslab-bold.ttf
  docs/themes/coreshop/fonts/robotoslab-bold.woff
  docs/themes/coreshop/fonts/robotoslab-bold.woff2
  docs/themes/coreshop/fonts/robotoslab-light.eot
  docs/themes/coreshop/fonts/robotoslab-light.svg
  docs/themes/coreshop/fonts/robotoslab-light.ttf
  docs/themes/coreshop/fonts/robotoslab-light.woff
  docs/themes/coreshop/fonts/robotoslab-light.woff2
  docs/themes/coreshop/fonts/robotoslab-regular.eot
  docs/themes/coreshop/fonts/robotoslab-regular.svg
  docs/themes/coreshop/fonts/robotoslab-regular.ttf
  docs/themes/coreshop/fonts/robotoslab-regular.woff
  docs/themes/coreshop/fonts/robotoslab-regular.woff2
  docs/themes/coreshop/img/favicon.png
  docs/themes/coreshop/img/logo-white.svg
  docs/themes/coreshop/js/build/pimcore.js
  docs/themes/coreshop/js/build/pimcore.min.js
  docs/themes/coreshop/js/source/cireshio.js
  docs/themes/coreshop/js/source/coreshop_code_section.js
  docs/themes/coreshop/js/source/coreshop_image_lightbox.js
  docs/themes/coreshop/js/source/coreshop_video.js
  docs/themes/coreshop/js/source/html5shiv-3.7.3.min.js
  docs/themes/coreshop/less/_boxes.less
  docs/themes/coreshop/less/_code.less
  docs/themes/coreshop/less/_highlight-style.less
  docs/themes/coreshop/less/_theme.less
  docs/themes/coreshop/less/_variables.less
  docs/themes/coreshop/less/coreshop-core.less
  docs/themes/coreshop/less/coreshop-generic.less
  docs/themes/coreshop/templates/content.php
  docs/themes/coreshop/templates/home.php
  docs/themes/coreshop/templates/layout/00_layout.php
  docs/themes/coreshop/templates/layout/05_page.php
  docs/themes/coreshop/templates/partials/change_version.php
  docs/themes/coreshop/templates/partials/disqus.php
  docs/themes/coreshop/templates/partials/edit_on.php
  docs/themes/coreshop/templates/partials/navbar_content.php
  docs/themes/coreshop/templates/partials/version_info.php
Labels: docs

#2491 [MessengerBundle] Use <pre> to format raw message HTML in info window and make window a bit wider as well
  src/CoreShop/Bundle/MessengerBundle/Resources/public/pimcore/js/list.js
Labels: enhancement

#2489 Update Select.php
  src/CoreShop/Bundle/ResourceBundle/CoreExtension/Document/Select.php
Labels: bug

#2494 [ClassDefinitionPath] allow update of field-definitions instead of replace
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/DependencyInjection/CoreShopClassDefinitionPatchExtension.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/PatchField.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/PatchFieldInterface.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/Patcher.php
Labels: enhancement
