Repository coreshop/CoreShop, pull requests merged in 2023-04, with the labels that each got.

#2246 [StorageListBundle] fix loading 'coreshop.context.cart'
  src/CoreShop/Bundle/StorageListBundle/CoreShopStorageListBundle.php
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/Compiler/RegisterAllStorageListsPass.php
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
Labels: bug

#2242 Check first if metatitle is not null before setting it SEO TitleExtractor
  src/CoreShop/Component/SEO/Extractor/TitleExtractor.php
Labels: bug, wrong-branch

#2244 Fix deprecation format
  src/CoreShop/Bundle/AddressBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/ConfigurationBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/CurrencyBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/CustomerBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/FixtureBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/FrontendBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/IndexBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/InventoryBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/LocaleBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/MenuBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/MoneyBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/NotificationBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/PaymentBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/PayumBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/ProductBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/RuleBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/SEOBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/SequenceBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/StoreBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/TaxationBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/ThemeBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/TrackingBundle/Resources/config/services_alias.yml
  src/CoreShop/Bundle/WorkflowBundle/Resources/config/services_alias.yml
Labels: wrong-branch

#2238 [Shipping] don't include shipping total in amount shipping condition
  features/domain/shipping/shipping_rules/amount_total_condition.feature
  src/CoreShop/Behat/Context/Domain/CartContext.php
  src/CoreShop/Behat/Context/Setup/ShippingContext.php
  src/CoreShop/Behat/Resources/config/suites/domain/shipping.yml
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/AmountConfigurationType.php
  src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/shippingrule/conditions/amount.js
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/ShippingBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Shipping/Model/ShippableInterface.php
  src/CoreShop/Component/Shipping/Rule/Condition/AmountConditionChecker.php
Labels: bug

#2253 [OrderBundle] introduce not-combinable price rule condition
  features/domain/cart/rules/not_combinable_condition.feature
  src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20230418082816.php
  src/CoreShop/Bundle/OrderBundle/Doctrine/ORM/CartPriceRuleRepository.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/CartPriceRuleType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/NotCombinableConfigurationType.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/doctrine/model/CartPriceRule.orm.xml
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.CartPriceRule.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/forms.yml
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/css/order.css
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/img/not_combinable.svg
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/conditions/not_combinable.js
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/item.js
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml
  src/CoreShop/Component/Core/Order/Processor/CartRuleAutoProcessor.php
  src/CoreShop/Component/Order/Cart/Rule/Condition/NotCombinableConditionChecker.php
  src/CoreShop/Component/Order/Model/CartPriceRule.php
  src/CoreShop/Component/Order/Model/CartPriceRuleInterface.php
Labels: enhancement

#2254 Use shipping address of logged in customer for tax calculation
  src/CoreShop/Component/Core/Provider/ContextBasedDefaultTaxAddressProvider.php
Labels: enhancement

#2258 [Order] don't add CartItemPriceRule if not applicable
  src/CoreShop/Component/Order/Cart/Rule/Action/CartItemActionProcessor.php
Labels: bug

#2250 [Cache] disabling caching of StorageLists for better concurrency
  composer.json
  src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
  src/CoreShop/Bundle/StorageListBundle/EventListener/CacheListener.php
  src/CoreShop/Component/Order/Context/CartContext.php
Labels: bug

#2260 [Pimcore] add locale to SlugGenerationEvent
  src/CoreShop/Component/Pimcore/Event/SlugGenerationEvent.php
  src/CoreShop/Component/Pimcore/Slug/DataObjectSiteSlugGenerator.php
Labels: enhancement
