Repository coreshop/CoreShop, pull requests merged in 2023-05, with the labels that each got.

#2265 Performance optimization
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/SequenceBundle/Doctrine/ORM/SequenceRepository.php
  src/CoreShop/Bundle/StorageListBundle/EventListener/SessionSubscriber.php
  src/CoreShop/Component/Core/Order/Committer/OrderCommitter.php
  src/CoreShop/Component/Order/Factory/OrderFactory.php
  src/CoreShop/Component/Sequence/Generator/SequenceGenerator.php
  src/CoreShop/Component/StorageList/Manager/StorageListPimcoreModelManager.php
Labels: bug

#2266 [WishlistBundle] make wishlist easier usable outside of CoreShop
  docker-compose.yaml
  src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/WishlistRepository.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/CoreShopResourceExtension.php
  src/CoreShop/Bundle/WishlistBundle/Pimcore/Repository/WishlistRepository.php
  src/CoreShop/Bundle/WishlistBundle/Resources/install/pimcore/classes/CoreShopWishlist.json
  src/CoreShop/Bundle/WishlistBundle/Resources/install/pimcore/classes/CoreShopWishlistItem.json
Labels: bug

#2268 [Release] 3.0.5
  CHANGELOG-3.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2267 [Wishlist] Wishlist Expiry for single use
  src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/WishlistRepository.php
  src/CoreShop/Bundle/WishlistBundle/Pimcore/Repository/WishlistRepository.php
  src/CoreShop/Component/Wishlist/Repository/WishlistRepositoryInterface.php
Labels: bug

#2269 [StorageList] add default session based context resolver
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
  src/CoreShop/Bundle/WishlistBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/WishlistBundle/Resources/config/services.yml
  src/CoreShop/Component/StorageList/Context/SessionBasedListContext.php
Labels: bug, enhancement

#2274 [Guzzle] use ^1.0 for guzzle adapter
  composer.json
  src/CoreShop/Bundle/PayumBundle/composer.json
  src/CoreShop/Bundle/PayumPaymentBundle/composer.json
Labels: enhancement

#2277 [FrontendBundle] throw 404 when Reset-Token not found
  src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php
Labels: bug

#2279 [ClassDefinitionPatchBundle] introduce new Bundle to allow patching Pimcore Class Definitions
  bin/subtree-release
  bin/subtree-split
  composer.json
  docs/02_Bundles/ClassDefinitionPatch_Bundle.md
  docs/02_Bundles/img/patch.png
  docs/02_Bundles/index.md
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/Command/PatchCommand.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/Console/ColorConsoleDiffFormatter.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/Console/ConsoleDiffer.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/CoreShopClassDefinitionPatchBundle.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/DependencyInjection/CoreShopClassDefinitionPatchExtension.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/LICENSE.md
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/Patch.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/PatchField.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/PatchFieldInterface.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/PatchInterface.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/Patcher.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/PatcherInterface.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/Patches.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/PatchesInterface.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/README.md
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/composer.json
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/gpl-3.0.txt
  src/CoreShop/Bundle/CoreBundle/CoreShopCoreBundle.php
  src/CoreShop/Bundle/CoreBundle/composer.json
  src/CoreShop/Component/Pimcore/DataObject/AbstractDefinitionUpdate.php
  src/CoreShop/Component/Pimcore/DataObject/BrickDefinitionUpdate.php
  src/CoreShop/Component/Pimcore/DataObject/ClassUpdate.php
  src/CoreShop/Component/Pimcore/DataObject/FieldCollectionDefinitionUpdate.php
Labels: new feature

#2294 improve unlinking files in pdf generation
  src/CoreShop/Bundle/OrderBundle/Renderer/Pdf/WkHtmlToPdf.php
Labels: bug
