Repository coreshop/CoreShop, pull requests merged in 2023-02, with the labels that each got.

#2197 set corret store value attributes
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
Labels: bug

#2200 [IndexBundle] check recursively child elements
  src/CoreShop/Bundle/IndexBundle/Messenger/Handler/IndexMessageHandler.php
Labels: bug

#2201 [FrontendBundle] fix only showing customer orders and not cars too
  src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
  src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php
  src/CoreShop/Component/Order/Repository/OrderRepositoryInterface.php
Labels: bug

#2203 [FrontendBundle] sort orders by orderDate and not ID
  src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php
Labels: bug

#2187 [CoreBundle] fix column names for coreshop_carrier_store table
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20230127064907.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Carrier.orm.xml
Labels: bug

#2204 [PimcoreBundle] fix implementation loader
  src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterImplementationLoaderPass.php
Labels: bug

#2207 improve payment detail rendering
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/editPayment.js
Labels: enhancement

#2215 2213: Fix Grid Column Config
  src/CoreShop/Bundle/CoreBundle/Pimcore/GridColumnConfig/Operator/StorePrice.php
Labels: bug

#2219 [Release] 3.0.4
  CHANGELOG-3.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2223 [Core] fix StoreMailActionProcessor
  src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreGridConfigInstaller.php
  src/CoreShop/Component/Core/Notification/Rule/Action/Order/StoreMailActionProcessor.php
Labels: bug

#2224 [FrontendBundle] Checkout allow to pass query params from step to step
  src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
Labels: enhancement
