Repository coreshop/CoreShop, pull requests merged in 2023-10, with the labels that each got.

#2385 [Release] 3.1.2
  CHANGELOG-3.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2387 [Cart] fix using right context for performance increase
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/context.yml
Labels: bug

#2389 [ResourceBundle] fix cache marshalling issues with CoreShop Doctrine …
  src/CoreShop/Bundle/ResourceBundle/EventListener/DeepCopySubscriber.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
Labels: bug

#2391 [Release] 4.0.0-beta.2
  CHANGELOG-4.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2393 [Messenger] fix menu in standalone mode
  src/CoreShop/Bundle/MessengerBundle/Resources/public/pimcore/js/resource_standalone.js
Labels: bug

#2398 [Cache] cache improvements - decorate Pimcore CoreCacheHandler
  .gitignore
  features/domain/cache/check_cache_size.feature
  src/CoreShop/Behat/Context/Domain/CacheContext.php
  src/CoreShop/Behat/Context/Setup/CacheContext.php
  src/CoreShop/Behat/Context/Transform/CacheContext.php
  src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
  src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
  src/CoreShop/Behat/Resources/config/services/contexts/transform.yml
  src/CoreShop/Behat/Resources/config/suites/domain.yml
  src/CoreShop/Behat/Resources/config/suites/domain/cache.yml
  src/CoreShop/Bundle/ResourceBundle/Cache/CoreCacheHandlerDecorator.php
  src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/PimcoreCachePass.php
  src/CoreShop/Bundle/ResourceBundle/EventListener/DeepCopySubscriber.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/CacheResourceMarshaller.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
Labels: bug

#2400 [Release] 3.1.3
  CHANGELOG-3.1.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2402 [Release] 3.2.0-beta.1
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2403 [Release] 4.0.0-beta.3
  CHANGELOG-4.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2412 cast trackingCode as string
  src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.OrderShipment.yml
Labels: bug

#2407 fix comment delete request
  src/CoreShop/Bundle/OrderBundle/Controller/OrderCommentController.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/routing.yml
Labels: bug

#2413 [Pimcore11] remove o_ column usages
  src/CoreShop/Bundle/CoreBundle/Report/CarriersReport.php
  src/CoreShop/Bundle/CoreBundle/Report/CategoriesReport.php
  src/CoreShop/Bundle/CoreBundle/Report/PaymentProvidersReport.php
  src/CoreShop/Bundle/WishlistBundle/Pimcore/Repository/WishlistRepository.php
  src/CoreShop/Component/StorageList/Repository/CustomerExpiryRepositoryTrait.php
Labels: bug

#2414 [Pimcore11] fix return type for getChildCategories
  src/CoreShop/Component/Product/Model/Category.php
  src/CoreShop/Component/Product/Model/CategoryInterface.php
Labels: bug

#2415 can not save sore shop settings
  src/CoreShop/Bundle/CoreBundle/Controller/ConfigurationController.php
Labels: bug

#2423 [Pimcore] require Pimcore 11.1 as minimum
  .github/workflows/behat.yml
  .github/workflows/behat_ui.yml
  .github/workflows/packages_bundles.yml
  .github/workflows/packages_components.yml
  .github/workflows/static.yml
  README.md
  composer.json
Labels: enhancement

#2422 [Core] add unit to GiftProductAction
  features/domain/cart/rules/gift_product_with_unit_action.feature
  src/CoreShop/Behat/Context/Domain/CartContext.php
  src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php
Labels: bug

#2426 Fix error in the filter functionality for multiselects
  src/CoreShop/Component/Index/Filter/CategoryMultiSelectConditionProcessor.php
  src/CoreShop/Component/Index/Filter/MultiselectFilterConditionFromMultiselectProcessor.php
  src/CoreShop/Component/Index/Filter/MultiselectFilterConditionProcessor.php
  src/CoreShop/Component/Index/Filter/RelationalMultiselectConditionProcessor.php
Labels: bug
