Repository coreshop/CoreShop, pull requests merged in 2023-01, with the labels that each got.

#2171 [IndexBundle] process children within same Handler
  psalm.xml
  src/CoreShop/Bundle/IndexBundle/Messenger/Handler/IndexMessageHandler.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/services/messenger.yml
Labels: enhancement

#2174 Do not allow negative or 0 cart item quantity
  src/CoreShop/Component/Core/Order/Modifier/CartItemQuantityModifier.php
Labels: bug

#2172 use correct parent for virtual object active state
  src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
Labels: bug

#2169 Prevent error when adding new store without currency
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
Labels: bug

#2167 [Reports] Add index for CoreShopOrder.orderDate to improve report performance
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
Labels: enhancement

#2177 [Checkout] add pre-payment event
  config/packages/test/config.yaml
  src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
  src/CoreShop/Component/Order/CheckoutEvents.php
Labels: enhancement

#2188 [Release] 3.0.3
  CHANGELOG-3.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2193 [Payum] don't use dev version
  src/CoreShop/Bundle/PayumBundle/composer.json
  src/CoreShop/Bundle/PayumPaymentBundle/composer.json
Labels: bug

#2195 [ShippingBundle] allow min.amount from to be 0
  src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/AmountConfigurationType.php
Labels: bug

#2196 [Core] allow decoration of StackRepository
  src/CoreShop/Bundle/CoreBundle/Controller/ProductValidationController.php
  src/CoreShop/Bundle/CoreBundle/Report/ProductsReport.php
  src/CoreShop/Bundle/ProductBundle/Controller/ProductUnitDefinitionsController.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepository.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepositoryInterface.php
  src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php
Labels: enhancement
