Repository coreshop/CoreShop, pull requests merged in 2024-10, with the labels that each got.

#2720 [Pimcore] introduce the Printable
  src/CoreShop/Bundle/OrderBundle/Renderer/PimcoreOrderDocumentPdfRenderer.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/pdf.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/print.yaml
  src/CoreShop/Component/Order/Model/OrderDocumentInterface.php
  src/CoreShop/Component/Order/Model/OrderInvoice.php
  src/CoreShop/Component/Order/Model/OrderShipment.php
  src/CoreShop/Component/Pimcore/Print/PimcorePrintablePdfRenderer.php
  src/CoreShop/Component/Pimcore/Print/PrintableInterface.php
  src/CoreShop/Component/Pimcore/Print/PrintablePdfRendererInterface.php
  src/CoreShop/Component/Pimcore/composer.json
Labels: enhancement, new feature

#2723 [Pimcore] introduce LocalizedFallbackHelper
  src/CoreShop/Component/Pimcore/DataObject/LocalizedFallbackHelper.php
Labels: enhancement

#2722 [Payum] 2.6 compatibility
  src/CoreShop/Behat/Resources/config/services.yml
  src/CoreShop/Bundle/PayumBundle/CoreGatewayFactory.php
  src/CoreShop/Bundle/PayumBundle/CoreGatewayFactoryBuilder.php
  src/CoreShop/Bundle/PayumBundle/Resources/config/services.yml
Labels: enhancement

#2724 [Printable] further improvements to new printable feature
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/print.yaml
  src/CoreShop/Component/Pimcore/Print/PersistedPrintableInterface.php
  src/CoreShop/Component/Pimcore/Print/PersistedPrintablePdfRenderer.php
  src/CoreShop/Component/Pimcore/Print/PimcorePrintablePdfRenderer.php
  src/CoreShop/Component/Pimcore/Print/PropertyPersistedPrintableTrait.php
Labels: enhancement

#2727 [Store] fix cached store context
  src/CoreShop/Component/Store/Context/RequestBased/CachedStoreContext.php
Labels: bug

#2732 [Release] 3.2.14
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2735 [FrontendBundle] disable by default
  src/AppKernel.php
  src/BehatKernel.php
  src/CoreShop/Bundle/CoreBundle/CoreShopCoreBundle.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20241018060845.php
  src/Kernel.php
Labels: BC break

#2737 [Release] 4.1.0-RC2
  CHANGELOG-4.1.x.md
  docs/01_Getting_Started/00_Installation.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2741 Update CartController - remove Argument Injection
  src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
Labels: bug

#2743 [PayumBundle] remove payment_state processing to confirm orders
  src/CoreShop/Bundle/PayumBundle/Action/ConfirmOrderAction.php
  src/CoreShop/Bundle/PayumBundle/Extension/UpdateOrderStateExtension.php
Labels: bug, BC break
