Repository coreshop/CoreShop, pull requests merged in 2024-12, with the labels that each got.

#2760 Added action price casting to int
  src/CoreShop/Component/Product/Rule/Action/PriceActionProcessor.php
Labels: bug

#2762 [ResourceBundle/OrderBundle] fix order grid-configs and add a new CoreShop Resource Field Getter Operator
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/grid-config.yml
  src/CoreShop/Bundle/ResourceBundle/Installer/Configuration/GridConfigConfiguration.php
  src/CoreShop/Bundle/ResourceBundle/Pimcore/GridColumnConfig/ResourceFieldGetter.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services/grid.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/object/gridcolumn/operator/coreshop_resource_field_getter.js
Labels: bug, enhancement

#2766 [Store] optimize Store Context resolving with fallback and admin/non-admin
  src/CoreShop/Bundle/StoreBundle/Resources/config/services.yml
  src/CoreShop/Component/Store/Context/RequestBased/PimcoreAdminSiteBasedRequestResolver.php
  src/CoreShop/Component/Store/Context/RequestBased/SiteBasedRequestResolver.php
  src/CoreShop/Component/Store/Context/SiteBasedResolver.php
  src/CoreShop/Component/Store/Context/SiteBasedResolverInterface.php
Labels: bug

#2769 [Store] optimize Store Context resolving with fallback and admin/non-admin also for area bricks
  src/CoreShop/Bundle/StoreBundle/Resources/config/services.yml
  src/CoreShop/Component/Store/Context/RequestBased/PimcoreAreaBrickRenderResolver.php
Labels: bug

#2768 [ResourceBundle] Version Marshalling for FieldCollections
  src/CoreShop/Bundle/ResourceBundle/DeepCopy/PimcoreFieldCollectionDefinitionMatcher.php
  src/CoreShop/Bundle/ResourceBundle/DeepCopy/PimcoreFieldCollectionDefinitionReplaceFilter.php
  src/CoreShop/Bundle/ResourceBundle/EventListener/DeepCopySubscriber.php
Labels: bug

#2772 [CoreBundle] allow to pass site to link generation
  src/CoreShop/Bundle/CoreBundle/Pimcore/LinkGenerator/DataObjectLinkGenerator.php
Labels: enhancement
