Repository coreshop/CoreShop, pull requests merged in 2024-05, with the labels that each got.

#2624 [OrderBundle] fix range condition with notInRangeMessage
  composer.json
  src/CoreShop/Bundle/FrontendBundle/Resources/translations/messages.de.yaml
  src/CoreShop/Bundle/FrontendBundle/Resources/translations/messages.en.yaml
  src/CoreShop/Bundle/FrontendBundle/composer.json
  src/CoreShop/Bundle/OrderBundle/Resources/config/validation/CartPriceRuleVoucherGenerator.yml
Labels: bug

#2622 [ResourceBundle] Fix EntityMerger and cascade-merging
  docker-compose.yaml
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Country.orm.xml
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/ProductStoreValues.orm.xml
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/ProductUnitDefinitionPrice.orm.xml
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Store.orm.xml
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductSpecificPriceRule.orm.xml
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinition.orm.xml
  src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinitionPrice.orm.xml
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/doctrine/model/ProductQuantityPriceRule.orm.xml
  src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php
Labels: bug

#2629 [Release] 3.2.8
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2638 Fix JS Error due to missing global function ts()
  src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/fields.js
Labels: bug

#2634 Prevent PHP error for store without currency
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
Labels: bug

#2639 [Release] 4.0.7
  CHANGELOG-4.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2640 [PaymentBundle] fix null title for payment provider
  src/CoreShop/Bundle/PaymentBundle/Form/Type/PaymentProviderChoiceType.php
Labels: bug

#2493 [JMS] allow v5
  .github/workflows/behat.yml
  .github/workflows/behat_ui.yml
  .github/workflows/packages_bundles.yml
  .github/workflows/packages_components.yml
  .github/workflows/static.yml
  .gitignore
  composer.json
  src/CoreShop/Bundle/CustomerBundle/Resources/config/serializer/Model.Customer.yml
  src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
  src/CoreShop/Bundle/ResourceBundle/composer.json
Labels: enhancement

#2644 [Pimcore] CoreShop 3 compatibility only with Pimcore 10.6
  Dockerfile
  composer.json
  src/CoreShop/Bundle/AddressBundle/composer.json
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/composer.json
  src/CoreShop/Bundle/ConfigurationBundle/composer.json
  src/CoreShop/Bundle/CurrencyBundle/composer.json
  src/CoreShop/Bundle/CustomerBundle/composer.json
  src/CoreShop/Bundle/FixtureBundle/composer.json
  src/CoreShop/Bundle/FrontendBundle/composer.json
  src/CoreShop/Bundle/IndexBundle/composer.json
  src/CoreShop/Bundle/InventoryBundle/composer.json
  src/CoreShop/Bundle/LocaleBundle/composer.json
  src/CoreShop/Bundle/MenuBundle/composer.json
  src/CoreShop/Bundle/MessengerBundle/composer.json
  src/CoreShop/Bundle/MoneyBundle/composer.json
  src/CoreShop/Bundle/NotificationBundle/composer.json
  src/CoreShop/Bundle/OptimisticEntityLockBundle/composer.json
  src/CoreShop/Bundle/OrderBundle/composer.json
  src/CoreShop/Bundle/PaymentBundle/composer.json
  src/CoreShop/Bundle/PayumBundle/composer.json
  src/CoreShop/Bundle/PayumPaymentBundle/composer.json
  src/CoreShop/Bundle/PimcoreBundle/composer.json
  src/CoreShop/Bundle/ProductBundle/composer.json
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/composer.json
  src/CoreShop/Bundle/ResourceBundle/composer.json
  src/CoreShop/Bundle/RuleBundle/composer.json
  src/CoreShop/Bundle/SEOBundle/composer.json
  src/CoreShop/Bundle/SequenceBundle/composer.json
  src/CoreShop/Bundle/ShippingBundle/composer.json
  src/CoreShop/Bundle/StoreBundle/composer.json
  src/CoreShop/Bundle/TaxationBundle/composer.json
  src/CoreShop/Bundle/TestBundle/composer.json
  src/CoreShop/Bundle/ThemeBundle/composer.json
  src/CoreShop/Bundle/TrackingBundle/composer.json
  src/CoreShop/Bundle/UserBundle/composer.json
  src/CoreShop/Bundle/WorkflowBundle/composer.json
  src/CoreShop/Component/Address/composer.json
  src/CoreShop/Component/Configuration/composer.json
  src/CoreShop/Component/Core/composer.json
  src/CoreShop/Component/Currency/composer.json
  src/CoreShop/Component/Customer/composer.json
  src/CoreShop/Component/Index/composer.json
  src/CoreShop/Component/Inventory/composer.json
  src/CoreShop/Component/Locale/composer.json
  src/CoreShop/Component/Notification/composer.json
  src/CoreShop/Component/Order/composer.json
  src/CoreShop/Component/Pimcore/composer.json
  src/CoreShop/Component/Product/composer.json
  src/CoreShop/Component/ProductQuantityPriceRules/composer.json
  src/CoreShop/Component/Resource/composer.json
  src/CoreShop/Component/Rule/composer.json
  src/CoreShop/Component/SEO/composer.json
  src/CoreShop/Component/Sequence/composer.json
  src/CoreShop/Component/Shipping/composer.json
  src/CoreShop/Component/StorageList/composer.json
  src/CoreShop/Component/Store/composer.json
  src/CoreShop/Component/Taxation/composer.json
  src/CoreShop/Component/User/composer.json
  src/CoreShop/Component/Wishlist/composer.json
Labels: bug

#2645 [Release] 3.2.9
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE
