Repository coreshop/CoreShop, pull requests merged in 2024-01, with the labels that each got.

#2498 assert range sort for qpr
  src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/doctrine/model/ProductQuantityPriceRule.orm.xml
Labels: bug

#2499 [OrderEdit] allow 0 quantity
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
  src/CoreShop/Bundle/OrderBundle/Form/DataMapper/BackendCartItemQuantityDataMapper.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/OrderItemType.php
  src/CoreShop/Bundle/OrderBundle/Form/Type/OrderType.php
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/order_edit.yml
  src/CoreShop/Component/Core/Order/Modifier/CartItemQuantityModifier.php
Labels: enhancement

#2501 use coreshop.form.factory in product unit definitions extension
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
Labels: bug

#2496 Class patches array
  psalm.xml
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/Patch.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/PatchInterface.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/Patcher.php
Labels: bug, enhancement

#2506 [Release] 3.2.1
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2512 [DataHub] only enable queries for selected entities
  src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/IndexBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/PaymentBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ProductBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ShippingBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/StoreBundle/DependencyInjection/Configuration.php
  src/CoreShop/Component/Resource/DataHub/DoctrineProvider.php
Labels: bug, enhancement

#2510 [CartManager] create unique key for cart items
  src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php
  src/CoreShop/Bundle/StorageListBundle/Resources/config/services.yml
  src/CoreShop/Component/StorageList/Manager/StorageListPimcoreModelManager.php
Labels: bug

#2518 add address identifier repository to subscribed services
  src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
Labels: bug

#2514 add guest condition
  README.md
  features/domain/cart/rules/guest_condition.feature
  features/domain/payment_provider/payment_provider_rules/guest_condition.feature
  features/domain/product/price_rules/guest_condition.feature
  features/domain/product/specific_price_rules/guest_condition.feature
  features/domain/shipping/shipping_rules/guest_condition.feature
  src/CoreShop/Behat/Context/Setup/CartContext.php
  src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
  src/CoreShop/Behat/Context/Setup/CustomerContext.php
  src/CoreShop/Behat/Context/Setup/PaymentContext.php
  src/CoreShop/Behat/Context/Setup/ProductPriceRuleContext.php
  src/CoreShop/Behat/Context/Setup/ProductSpecificPriceRuleContext.php
  src/CoreShop/Behat/Context/Setup/ShippingContext.php
  src/CoreShop/Behat/Context/Transform/CustomerContext.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/payment.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/product-quantity-price-rules.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/shipping.yml
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/css/core.css
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/img/guest.svg
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/cart/pricerules/conditions/guest.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/payment/rules/conditions/guest.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/pricerule/conditions/guest.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/specificprice/conditions/guest.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/productquantitypricerules/conditions/guest.js
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/conditions/guest.js
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.en.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.it.yml
  src/CoreShop/Bundle/CoreBundle/Resources/translations/admin.sv.yml
  src/CoreShop/Component/Core/Cart/Rule/Condition/GuestConditionChecker.php
  src/CoreShop/Component/Core/Payment/Rule/Condition/GuestConditionChecker.php
  src/CoreShop/Component/Core/Product/Rule/Condition/GuestConditionChecker.php
  src/CoreShop/Component/Core/Shipping/Rule/Condition/GuestConditionChecker.php
Labels: enhancement

#2520 [Core] add caching for recursive variant checking
  src/CoreShop/Bundle/CoreBundle/EventListener/RecursiveVariantCacheInvalidationEventListener.php
  src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/ProductRepository.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
  src/CoreShop/Component/Core/Cart/Rule/Condition/ProductsConditionChecker.php
  src/CoreShop/Component/Core/CartItem/Rule/Condition/ProductsConditionChecker.php
  src/CoreShop/Component/Core/Payment/Rule/Condition/ProductsConditionChecker.php
  src/CoreShop/Component/Core/Product/Rule/Condition/ProductsConditionChecker.php
  src/CoreShop/Component/Core/Repository/ProductVariantRepositoryInterface.php
  src/CoreShop/Component/Core/Rule/Condition/ProductVariantsCheckerTrait.php
  src/CoreShop/Component/Core/Shipping/Rule/Condition/ProductsConditionChecker.php
Labels: bug, enhancement

#2521 [Release] 3.2.2
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2522 [Release] 4.0.2
  CHANGELOG-3.2.x.md
  CHANGELOG-4.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2527 [Release] 3.2.3
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2528 [Core] Fixes in DataObject Extensions and Subscribed Services
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
  src/CoreShop/Bundle/FrontendBundle/Controller/OrderController.php
  src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php
Labels: bug
