Repository coreshop/CoreShop, pull requests merged in 2024-08, with the labels that each got.

#2678 [Product] don't allow Price and DiscountPrice Rule for unit prices
  src/CoreShop/Component/Product/Rule/Action/DiscountPriceActionProcessor.php
  src/CoreShop/Component/Product/Rule/Action/PriceActionProcessor.php
Labels: bug

#2677 [OrderBundle] use context language for OrderState Operator
  composer.json
  src/CoreShop/Bundle/OrderBundle/Pimcore/GridColumnConfig/Operator/OrderState.php
Labels: bug

#2679 Variant Creator
  docs/01_Getting_Started/00_Installation.md
  docs/03_Bundles/Variant_Bundle.md
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/broker.js
  src/CoreShop/Bundle/VariantBundle/Controller/VariantController.php
  src/CoreShop/Bundle/VariantBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/VariantBundle/Messenger/CreateVariantMessage.php
  src/CoreShop/Bundle/VariantBundle/Messenger/Handler/CreateVariantMessageHandler.php
  src/CoreShop/Bundle/VariantBundle/Resources/config/pimcore/admin.yml
  src/CoreShop/Bundle/VariantBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/VariantBundle/Resources/config/pimcore/messenger.yml
  src/CoreShop/Bundle/VariantBundle/Resources/config/pimcore/routing.yml
  src/CoreShop/Bundle/VariantBundle/Resources/config/services.yml
  src/CoreShop/Bundle/VariantBundle/Resources/public/pimcore/js/resource.js
  src/CoreShop/Bundle/VariantBundle/Resources/translations/admin.de.yaml
  src/CoreShop/Bundle/VariantBundle/Resources/translations/admin.en.yaml
  src/CoreShop/Bundle/VariantBundle/Service/VariantGeneratorService.php
  src/CoreShop/Bundle/VariantBundle/Service/VariantGeneratorServiceInterface.php
  src/CoreShop/Component/Variant/Model/AttributeGroup.php
  src/CoreShop/Component/Variant/Model/AttributeGroupInterface.php
Labels: enhancement, new feature

#2681 [Release] 3.2.12
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2682 [Release] 4.0.9
  CHANGELOG-4.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2686 [Currency/Money] implement Pimcore Grid Column
  src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
  src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopMoneyCurrency.js
  src/CoreShop/Bundle/MoneyBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopMoney.js
Labels: enhancement

#2684 [StorageList] make sure to remove StorageList from Session on Logout
  phpstan-package.neon
  src/CoreShop/Bundle/StorageListBundle/Core/EventListener/SessionStoreStorageListLogoutSubscriber.php
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
  src/CoreShop/Bundle/WishlistBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Component/StorageList/Core/Context/SessionAndStoreBasedStorageListContext.php
Labels: bug

#2690 [InventoryBundle] add stock label renderer and hide onHand field
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
  src/CoreShop/Bundle/InventoryBundle/Pimcore/Renderer/StockOnHandRenderer.php
  src/CoreShop/Bundle/InventoryBundle/Resources/config/services.yml
  src/CoreShop/Bundle/InventoryBundle/Resources/views/pimcore/stock_text.html.twig
Labels: enhancement

#2695 respect user language for grid filter labels (#2694)
  .github/workflows/behat_ui.yml
  src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/GridController.php
Labels: bug
