Repository coreshop/CoreShop, pull requests merged in 2024-11, with the labels that each got.

#2747 [Core] allow multiple store-values
  src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
  src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/ProductStoreValuesRepository.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20241105123053.php
  src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/ProductStoreValues.orm.xml
  src/CoreShop/Component/Core/Model/ProductStoreValues.php
  src/CoreShop/Component/Core/Model/ProductStoreValuesInterface.php
  src/CoreShop/Component/Core/Repository/ProductStoreValuesRepositoryInterface.php
Labels: enhancement

#2750 [CoreBundle] fix quantity price rules customerGroups condition
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/productquantitypricerules/conditions/guest.js
Labels: bug

#2752 [Release] 3.2.15
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2753 [Release] 4.0.12
  CHANGELOG-4.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2756 [Resource] fallback locale could be null for newly created entities
  src/CoreShop/Component/Resource/Model/TranslatableTrait.php
Labels: bug

#2754 [PimcoreBundle] fix MultiSelect (check for existing store)
  src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/ext/MultiSelect.js
Labels: bug

#2757 [priceNull - 3.2] - add listener for null/empty price on field
  src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/storevalues/items/price.js
Labels: enhancement

#2758 fix: CheckoutManager::getNextStep return type
  src/CoreShop/Component/Order/Checkout/CheckoutManager.php
Labels: bug
