Repository coreshop/CoreShop, pull requests merged in 2024-04, with the labels that each got.

#2602 [CoreBundle] fix CartTextProcessor priority and CartManagers setParent for cart-item
  src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
  src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php
Labels: bug

#2592 [Release] 3.2.7
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2603 Index error if product does not have a store
  src/CoreShop/Component/Core/Index/Extensions/ProductClassExtension.php
Labels: bug

#2604 make ObjectInterpreter compatible with "Advanced Many-To-Many Object Relation" Type
  src/CoreShop/Component/Index/Interpreter/ObjectInterpreter.php
Labels: enhancement

#2609 make password reset notification store aware
  src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/CustomerListener.php
Labels: bug

#2611 [MessengerBundle] add permission and check for permissions
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20240421093551.php
  src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/MessengerBundle/Controller/ListMessagesController.php
  src/CoreShop/Bundle/MessengerBundle/Controller/MessageController.php
  src/CoreShop/Bundle/MessengerBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/MessengerBundle/Migrations/Version20240421093216.php
  src/CoreShop/Bundle/MessengerBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Bundle/MessengerBundle/Resources/config/services.yml
  src/CoreShop/Bundle/MessengerBundle/Resources/translations/admin.de.yml
  src/CoreShop/Bundle/MessengerBundle/Resources/translations/admin.en.yml
Labels: bug, enhancement

#2612 [Composer] conflict twig/twig: ^3.9.0
  composer.json
Labels: bug, enhancement

#2613 [Workflows] update to latest versions
  .github/workflows/behat.yml
  .github/workflows/behat_ui.yml
  .github/workflows/codestyles.yml
  .github/workflows/docs.yml
  .github/workflows/gitsplit.yml
  .github/workflows/packages_bundles.yml
  .github/workflows/packages_components.yml
  .github/workflows/static.yml
Labels: enhancement

#2619 Notification Rules doesn't have state/transitions in DEV mode
  src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
Labels: bug

#2606 [Core] fix priorities between bundles
  src/CoreShop/Bundle/CoreBundle/CoreShopCoreBundle.php
  src/CoreShop/Bundle/FrontendBundle/CoreShopFrontendBundle.php
  src/Kernel.php
Labels: bug

#2620 reimplement existing data check in ProductQuantityPriceRulesCloner
  src/CoreShop/Component/Core/Product/Cloner/ProductQuantityPriceRulesCloner.php
Labels: bug
