Repository coreshop/CoreShop, pull requests merged in 2024-02, with the labels that each got.

#2530 [MessengerBundle] make FailedMessageDetails and MessageDetails JsonSerializable
  src/CoreShop/Bundle/MessengerBundle/Messenger/FailedMessageDetails.php
  src/CoreShop/Bundle/MessengerBundle/Messenger/MessageDetails.php
Labels: bug

#2536 [ResourceBundle] auto registration of pimcore models
  docs/03_Bundles/Resource_Bundle/index.md
  docs/03_Development/03_Products/05_Multiple_Product_DataObjects.md
  features/domain/pimcore/pimcore_model_resource_autoregistration.feature
  src/CoreShop/Behat/Context/Domain/ResourceContext.php
  src/CoreShop/Behat/Model/Car.php
  src/CoreShop/Behat/Resources/config/services.yml
  src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
  src/CoreShop/Behat/Resources/config/suites/domain/pimcore.yml
  src/CoreShop/Bundle/ResourceBundle/Attribute/AsPimcoreModel.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Configuration.php
  src/CoreShop/Bundle/ResourceBundle/DependencyInjection/CoreShopResourceExtension.php
  src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
  src/CoreShop/Component/Resource/Reflection/ClassReflection.php
  src/CoreShop/Component/Resource/composer.json
Labels: enhancement

#2542 [CoreBundle] fix priority of coreshop_payment_token route
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20240211090209.php
  src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml
Labels: bug

#2543 [Frontend] create order-token if not yet exists
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20240211095530.php
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20240211095804.php
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
  src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopWishlistBundle/CoreShopWishlist.json
  src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
  src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
Labels: bug

#2544 [ProductBundle] default return empty array instead of null in preGetData
  src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
Labels: bug

#2547 [Release] 3.2.4
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2548 [Release] 4.0.3
  CHANGELOG-3.2.x.md
  CHANGELOG-4.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2550 [Migration] fix Staticroute Migration for Pimcore 10
  src/CoreShop/Bundle/CoreBundle/Migrations/Version20240211090209.php
  src/CoreShop/Bundle/CoreBundle/Security/AccessVoter.php
Labels: bug

#2551 [Release] 3.2.5
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2557 [OrderBundle] register OrderDocumentPrintController in controller.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
  src/CoreShop/Bundle/OrderBundle/Resources/config/services/controller.yml
Labels: bug

#2558 [OrderBundle] cast return values for getWkHtmlToPdfBinary and getXvfb…
  src/CoreShop/Bundle/OrderBundle/Renderer/Pdf/WkHtmlToPdf.php
Labels: bug

#2560 [Tests] add test for stock tracked products in checkout
  features/ui/frontend/checkout/checkout_with_stock_tracked_product.feature
Labels: tests

#2559 [Tests] test only latest pimcore with highest deps for 3.2
  .github/workflows/behat.yml
  .github/workflows/behat_ui.yml
  .github/workflows/packages_bundles.yml
  .github/workflows/packages_components.yml
  .github/workflows/static.yml
Labels: tests

#2567 Increase MessengerBundle Receivers combobox width
  src/CoreShop/Bundle/MessengerBundle/Resources/public/pimcore/js/list.js
Labels: enhancement

#2565 Updated CachedStoreContext.php
  src/CoreShop/Component/Store/Context/RequestBased/CachedStoreContext.php
Labels: enhancement

#2569 improved installation instructions
  docs/01_Getting_Started/00_Installation.md
Labels: docs
