Repository coreshop/CoreShop, pull requests merged in 2024-03, with the labels that each got.

#2573 [Core] fix price calculation with immutables and adjustments
  features/domain/cart/rules/cart_item/amount_condition.feature
  features/domain/cart/rules/cart_item/discount_amount_action.feature
  features/domain/cart/rules/cart_item/discount_over_100_percent.feature
  features/domain/cart/rules/cart_item/discount_percent_condition.feature
  features/domain/cart/rules/cart_item/discount_percent_gross_action.feature
  features/domain/cart/rules/cart_item/discount_percent_net_action.feature
  features/ui/frontend/checkout/checkout_with_cart_price_rule_surcharge.feature
  src/CoreShop/Behat/Context/Domain/CartContext.php
  src/CoreShop/Behat/Context/Setup/StoreContext.php
  src/CoreShop/Behat/Context/Ui/Frontend/CheckoutContext.php
  src/CoreShop/Behat/Page/Frontend/Checkout/ThankYouPage.php
  src/CoreShop/Behat/Page/Frontend/Checkout/ThankYouPageInterface.php
  src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/order_detail.html.twig
  src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php
  src/CoreShop/Component/Core/CartItem/Rule/Applier/CartItemRuleApplier.php
  src/CoreShop/Component/Core/Order/Processor/CartItemsImmutableProcessor.php
  src/CoreShop/Component/Core/Order/Processor/CartSubtotalProcessor.php
  src/CoreShop/Component/Order/Cart/Rule/Action/CartItemActionProcessor.php
  src/CoreShop/Component/Order/Model/AdjustableInterface.php
  src/CoreShop/Component/Order/Model/AdjustableTrait.php
  src/CoreShop/Component/Order/Model/Order.php
  src/CoreShop/Component/Order/Model/OrderInterface.php
Labels: bug

#2577 [Release] 3.2.6
  CHANGELOG-3.2.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2578 [Release] 4.0.4
  CHANGELOG-4.0.x.md
  src/CoreShop/Bundle/CoreBundle/Application/Version.php
Labels: RELEASE

#2584 [Core] Pimcore 11.1 and 11.2 compatibility and psalm update
  .env
  .github/workflows/behat.yml
  .github/workflows/behat_ui.yml
  .github/workflows/packages_bundles.yml
  .github/workflows/packages_components.yml
  .github/workflows/static.yml
  behat-bootstrap.php
  bin/console
  composer.json
  phpstan.neon
  psalm.xml
  public/index.php
  public/index_test.php
  public/index_test_precision.php
  src/CoreShop/Behat/Context/Setup/StoreContext.php
  src/CoreShop/Behat/Service/Setup.php
  src/CoreShop/Bundle/ClassDefinitionPatchBundle/composer.json
  src/CoreShop/Bundle/CoreBundle/Command/InstallCommand.php
  src/CoreShop/Bundle/CoreBundle/EventListener/CustomerOrderDeletionListener.php
  src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/ProductRepository.php
  src/CoreShop/Bundle/FrontendBundle/Controller/CurrencyController.php
  src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php
  src/CoreShop/Bundle/ResourceBundle/Form/Helper/ErrorSerializer.php
  src/CoreShop/Component/Core/Index/Extensions/ProductClassExtension.php
  src/CoreShop/Component/Order/Generator/CartPriceRuleVoucherCodeGenerator.php
  src/CoreShop/Component/ProductQuantityPriceRules/Model/ProductQuantityPriceRule.php
  src/CoreShop/Component/StorageList/Repository/CustomerExpiryRepositoryTrait.php
  src/CoreShop/Component/Store/Model/StoresAwareTrait.php
  src/CoreShop/Component/Variant/Model/Resolved/ResolvedAttribute.php
Labels: enhancement

#2588 [NoteService] implement deadlock retry strategy
  src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
  src/CoreShop/Bundle/WorkflowBundle/History/StateHistoryLogger.php
  src/CoreShop/Component/Pimcore/DataObject/NoteService.php
Labels: bug

#2590 always set default unit quantity in gift product action
  features/ui/frontend/checkout/checkout_with_cart_price_rule_gift_item_that_is_stock_tracked.feature
  src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php
Labels: bug
